### ISSUE TITLE
Unable to Send or Create Media using Hologic HD uncompressed image

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#1061]
### Expected behavior
Very large uncompressed multi-frame image can be sent, stored and written to media 

### Actual behavior
Exceptions are thrown

### Steps to reproduce the behavior
Using sample SCU application try sending the test image attached.  An Exception is thrown
Error storing file. Exception Details:
Dicom.DicomFileException: An attempt was made to move the file pointer before the beginning of the file.
 ---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at Dicom.IO.FileByteSource.GetBuffer(UInt32 count) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\IO\FileByteSource.cs:line 150
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\IO\Reader\DicomReader.cs:line 676
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\IO\Reader\DicomReader.cs:line 232
   at Dicom.IO.Reader.DicomReader.Read(IByteSource source, IDicomReaderObserver observer, Func`2 stop) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\IO\Reader\DicomReader.cs:line 75
   at Dicom.IO.Reader.DicomFileReader.DoParse(IByteSource source, IDicomReaderObserver fileMetasetInfoObserver, IDicomReaderObserver datasetObserver, Func`2 stop, DicomTransferSyntax& syntax, DicomFileFormat& fileFormat) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\IO\Reader\DicomFileReader.cs:line 333
   at Dicom.IO.Reader.DicomFileReader.Parse(IByteSource source, IDicomReaderObserver fileMetasetInfoObserver, IDicomReaderObserver datasetObserver, Func`2 stop) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\IO\Reader\DicomFileReader.cs:line 153
   at Dicom.IO.Reader.DicomFileReader.Read(IByteSource source, IDicomReaderObserver fileMetaInfo, IDicomReaderObserver dataset, Func`2 stop) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\IO\Reader\DicomFileReader.cs:line 102
   at Dicom.DicomFile.Open(String fileName, Encoding fallbackEncoding, Func`2 stop, FileReadOption readOption) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\DicomFile.cs:line 235
   --- End of inner exception stack trace ---
   at Dicom.DicomFile.Open(String fileName, Encoding fallbackEncoding, Func`2 stop, FileReadOption readOption) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\DicomFile.cs:line 260
   at Dicom.Network.DicomCStoreRequest..ctor(String fileName, DicomPriority priority) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\Network\DicomCStoreRequest.cs:line 74

### fo-dicom version and OS/platform
Version 4.0.5 .NET 4.5.2 Windows 10 64 bit.

I have a file that is de-identified, but even compressed it will not let me attach it.  Let me know how I can get the file to you for evaluation and testing.

Thanks again for the help.

**Comment by gofal** [comment]
Hi, yes, I would need the file in order to reproduce and evaluate the exception.
The stacktrace of the exception is a very good hint, but not enough to solve the issue, I am affraid.

**Comment by gofal** [comment]
I created a link on onedrive. you should be able to upload here: https://1drv.ms/u/s!AufDe3vFQC-ahOEJNi_z1f0I-EIKxg?e=P2P5HL

**Comment by gofal** [comment]
otherwise there are free services for a limites number of files and a limited time, like "wetransfer" or "transfernow". just google it..

**Comment by BobSter3000** [comment]
@gofal The image has been uploaded.  Thanks again for all the hard work you and your team put into this project.

**Comment by gofal** [comment]
Hm, I have no problems opening the image using the tool Dicom.Dump.exe included in fo-dicom projects:
![image](https://user-images.githubusercontent.com/6769246/87007488-a8523f00-c1c2-11ea-8cc9-5116bec4615c.png)

And then I opened the sample applications from github.com/fo-dicom/fo-dicom-samples and sent the image with the storescu project to the storescp project. No problem happened.

**Comment by gofal** [comment]
Can you reproduce the problem with this anonymized and compressed image, too?

maybe the original file was corrupt and the anonymizer/compressor implicitly fixted the file?

**Comment by BobSter3000** [comment]
@gofal  I apologize, I sent the compressed image, which works correctly.  The C-Store SCU and Media Write tool, both throw exceptions.  If using the Media Write sample application for testing, disable the auto validation.  I think I tried a SCP and it also threw the same exception.  When the image is compressed there are no issues.  Interesting enough the Dump Utility does not have an issue opening the file, and it can even compress it.  I just posted the correct image.  Thanks again for the help

**Comment by gofal** [comment]
found the reason. the file has 2.5GB. the content of the pixeldata is bigger than 2GB. There are methods like `stream.seek(...` that are used to jump to the end of the content. For these methods `int` are used. That causes the problem.
I can use uint instead of int, but then there will be a definite limit with 4GB file.
Before the cange I managed to reproduce the IOException in Dicom.Dump, in CStoreSCU sample and in MediaWriter sample. After the change of using uint instead of int I managed to process the image in all of these three applications without exception.

I will do some more tests and then commit the change soon.

**Comment by BobSter3000** [comment]
Awesome, I honestly have never seen a DICOM image anywhere near 4GB anyway.  It is just recently I came across this one and just happened to see it when a device did not accept any compression transfer syntaxes.  Again, thanks for the help, this is great work.

**Comment by gofal** [comment]
agree. currently Breast Thomosynthesis might be the biggest data around in real live.
There is a definition for WSI in DICOM to store high resolution pathology images splited in tiles and with a pre-calculated pyramid in several zoom-levels. These files would have many GB each. But for some reason industry did not use it so far and every vendor still uses proprietary file formats.
