### ISSUE TITLE
Why delete on save?

### ISSUE THREAD

**Issue by mocsharp** [fo-dicom/fo-dicom#1067]
We are running into an issue with unable to delete when Save is called

`
at System.IO.FileSystem.DeleteFile(String fullPath)
   at Dicom.DicomFile.Save(String fileName, DicomWriteOptions options)
`

https://github.com/fo-dicom/fo-dicom/blob/47a771a35472a0ec64d6b47e8284e4c92cb994f4/DICOM/DicomFile.cs#L131

Is there any reason to always Delete instead of asking user for an arg to overwrite or not?
Thanks!

**Comment by amoerie** [comment]
What kind of issue are you running into? Please provide more details.

I'm unaware of the reasoning behind the implementation, perhaps @gofal can tell you more about this.

**Comment by gofal** [comment]
I am not sure, but as i understand the code, this File.Delete is called, because in case where the DicomService class receives a CStoreRequest, then the file is not held in memory, but stored into a temporary file. TemporaryFiles in Windows are created with 0bytes length, as soon as you call `Path.GetTempFileName()`. So before saving, the file is deleted if there is one.

If you do not want to override a file if it already existing, then you could check `if (! File.Exists(filename) ) dicomFile.Save(filename); ` it yourself.
