### ISSUE TITLE
JsonException when using DicomJsonConverter with Bolero remoting (FSharp + Blazor)

### ISSUE THREAD

**Issue by henkdemarie** [fo-dicom/fo-dicom#1220]
This is a minor issue, i have a work-around
I am making an App that sends and receives DicomDatasets in Json format to and from the server, using Bolero (FSharp + Blazor)
With Bolero, you can use additional custom JsonConverters, with JsonSerializerOptions, similar to Blazor.
This should automatically take care of all the (de)serialization that is needed for sending messages with SignalR, via Bolero remoting
I have added the DicomJsonConverter on both  the server and  the client side:
Server:
```
type Startup() =
    member this.ConfigureServices(services: IServiceCollection) =
        ...
        services
            .AddRemoting<MyCFindService>(fun (options: JsonSerializerOptions) -> 
                options.Converters.Add(DicomJsonConverter()))
                ...
```
Client:
```
module Program =
    [<EntryPoint>]
    let Main args =
        let builder = WebAssemblyHostBuilder.CreateDefault(args)
        ...
        builder.Services.AddRemoting(builder.HostEnvironment, fun (options: JsonSerializerOptions) -> 
            options.Converters.Add(DicomJsonConverter()))
        |> ignore
        ...
```
But i get the following JsonException, when i send a request to the server from the client:
```
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HMBTO4Q1T966", Request id "0HMBTO4Q1T966:0000000A": An unhandled exception was thrown by the application.

System.Text.Json.JsonException: The converter 'FellowOakDicom.Serialization.DicomJsonConverter' read too much or not enough. Path: $.Item3 | LineNumber: 0 | BytePositionInLine: 389.
   at System.Text.Json.ThrowHelper.ThrowJsonException_SerializationConverterRead(JsonConverter converter)
   at System.Text.Json.Serialization.JsonConverter`1.VerifyRead(JsonTokenType tokenType, Int32 depth, Int64 bytesConsumed, Boolean isValueConverter, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.TryRead[TArg](ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo, TArg& arg)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.ReadConstructorArgumentsWithContinuation(ReadStack& state, Utf8JsonReader& reader, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at <StartupCode$Bolero-Server>.$Remoting.InvokeForClientSide@110.Invoke(Unit unitVar)
   at Ply.TplPrimitives.ContinuationStateMachine`1.System-Runtime-CompilerServices-IAsyncStateMachine-MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
Searching for information on this exception i found the following article:
https://gmanvel.medium.com/system-text-json-jsonexception-read-too-much-or-not-enough-61a15952af5d,
witch states that a custom JsonConverter should not only check the readers TokenType, but also compare its CurrentDepth to its original depth, in its Read method.
Looking to the source of FellowOakDicom.Serialization.DicomJsonConverter is see that only the readers TokenType is checked.
Could this be the cause of the exception?

In the meantime i have the following work-around:
I wrap DicomJsonConverter:
```
type JSonDicomConverter(?writeTagsAsKeywords, ?autoValidate) =
    inherit DicomJsonConverter(defaultArg writeTagsAsKeywords false, defaultArg autoValidate true)

    override __.Read(reader, _, _) =
        DicomJson.ConvertJsonToDicom(reader.GetString(), defaultArg autoValidate true)

    override __.Write(writer, dataset, options) =
        DicomJson.ConvertDicomToJson(dataset, defaultArg writeTagsAsKeywords false, options.WriteIndented)
        |> writer.WriteStringValue
```
I also have to override Write, otherwise i get:
```
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in System.Text.Json.dll but was not handled in user code: 'Cannot get the value of a token type 'StartObject' as a string.'
   at System.Text.Json.Utf8JsonReader.GetString()
   at DmwlTools.Shared.JSonDicomConverter.Read(Utf8JsonReader& reader, Type _arg1, JsonSerializerOptions _arg2) in E:\henk\f#\DmwlTools\src\DmwlTools.Shared\Json.fs:line 12
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.TryRead[TArg](ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo, TArg& arg)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.ReadConstructorArgumentsWithContinuation(ReadStack& state, Utf8JsonReader& reader, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```

Fellow Oak DICOM version: 5.0.0
OS: Windows 10
Platform: net5.0

**Comment by gofal** [comment]
can you reproduce this exception with various different images (e.g. the sample images stored in fo-dicom's unittest-project https://github.com/fo-dicom/fo-dicom/tree/development/Tests/FO-DICOM.Tests/Test%20Data)? Or is this exception only releated with the structure of one of your images?
It would be great to reproduce this exception in a unittest before fixing it.

**Comment by henkdemarie** [comment]
It occurs when serializing/deserializing DicomDatasets without images.
What im doing is sending a very small dataset for a
DicomCFindRequest (created with DicomQueryRetrieveLevel.NotApplicatble),
only containing a
ScheduledProcedureStepSequence[0].ScheduledProcedureStepStartDate.
Hoping to get DicomCFindResponses and sending back their Commands and
Datasets in a tuple (cfind, so also no images).
So Serialization happens on both sides

**Comment by henkdemarie** [comment]
Sorry it took a while, i wrote a test.
but i see this is already merged to another issue and solved in the next version.
Thanks for looking into this.

**Comment by henkdemarie** [comment]
`#r "nuget: fo-dicom, 5.0.0"
#r "nuget: FSharp.SystemTextJson, 0.17.4"

open FellowOakDicom
open FellowOakDicom.Serialization
open System
open System.IO
open System.Text.Json
open System.Text.Json.Serialization

// Example Response type, with nested DicomDatasets

type Response = DicomDataset array array

// A custom DicomJsonConverter type,
// that inherits from/wraps DicomJsonConverter,
// needed for a successful test-

type CustomDicomJsonConverter(?writeTagsAsKeywords, ?autoValidate) =
    inherit DicomJsonConverter(?writeTagsAsKeywords = writeTagsAsKeywords, ?autoValidate = autoValidate)

    override __.Read(reader, _, _) =
        DicomJson.ConvertJsonToDicom(reader.GetString(), ?autoValidate = autoValidate)

    override __.Write(writer, dataset, options) =
        DicomJson.ConvertDicomToJson(
            dataset,
            ?writeTagsAsKeywords = writeTagsAsKeywords,
            formatIndented = options.WriteIndented
        )
        |> writer.WriteStringValue

// Helper function for adding converters to JsonSerializerOptions

let addConverter converter options =
    let options = JsonSerializerOptions(options = options)
    options.Converters.Add converter
    options

// The test function

let runTest response options =
    async {
        let stream = new MemoryStream()

        do!
            JsonSerializer.SerializeAsync<Response>(stream, response, options)
            |> Async.AwaitTask

        stream.Position <- int64 0

        return!
            JsonSerializer
                .DeserializeAsync<Response>(stream, options)
                .AsTask()
            |> Async.AwaitTask
    }

// Create an example Response

let command = DicomDataset()

let dataset =
    DicomDataset()
        .AddOrUpdate(DicomTag.StudyDate, DateTime.Now.Date)

let response: Response =
    [| [| command; dataset |]
       [| command; dataset |]
       [| command; dataset |] |]

// Create different JsonSerializerOptions

let optionsDefault =
    JsonSerializerOptions()
    |> addConverter (JsonFSharpConverter())

let optionsWithCustomDicomJsonConverter =
    optionsDefault
    |> addConverter (CustomDicomJsonConverter())

let optionsWithDicomJsonConverter =
    optionsDefault
    |> addConverter (DicomJsonConverter())

// Run the tests

//Test with the custom DicomJsonConverter
runTest response optionsWithCustomDicomJsonConverter
|> Async.RunSynchronously
|> printfn "Test result 1:\n%A\n"
// Test result 1:
//[|[|seq []; seq [(0008,0020) DA Study Date]|];
//  [|seq []; seq [(0008,0020) DA Study Date]|];
//  [|seq []; seq [(0008,0020) DA Study Date]|]|]

//Test with the normal DicomJsonConverter
runTest response optionsWithDicomJsonConverter
|> Async.RunSynchronously
|> printfn "Test result 2:\n%A\n"
// System.AggregateException: One or more errors occurred. (The converter 'FellowOakDicom.Serialization.DicomJsonConverter' read too much or not enough.
// ...
`
