### ISSUE TITLE
Error on use C-Store SCP in WPF project

### ISSUE THREAD

**Issue by HosseinMoazzam** [fo-dicom/fo-dicom#1265]
**Describe the bug**
I used C-Store SCP in **_C# console project_** and **_there is no errors_** in use of it and the image correctly send by client and receive by the server at the specific path; but when I use C-Store SCP code in a **_WPF project_**, there is one **_exception_**: 
System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 172.30.202.55:104 (Server IP : Server Port) 
in the client code and the image does not send.

**To Reproduce**
The code is the same samples of C-Store SCP as Server and C-Store SCU as client, and these work well in C# console project. But while I use the C-Store SCP code in a C# WPF project as running server, I got System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 172.30.202.55:104 (Server IP: Server Port) in the client code (C-Store SCU), and the image does not send.

Output Project in VS 2019:
`Error storing file. Exception Details:
System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 172.30.202.55:1004
   at Dicom.Network.Client.States.DicomClientCompletedState.<GetNextStateAsync>d__8.MoveNext() in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\Network\Client\States\DicomClientCompletedState.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dicom.Network.Client.DicomClient.<Transition>d__98.MoveNext() in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\Network\Client\DicomClient.cs:line 239
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.Client.States.DicomClientConnectState.<GetNextStateAsync>d__5.MoveNext() in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\Network\Client\States\DicomClientConnectState.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dicom.Network.Client.DicomClient.<Transition>d__98.MoveNext() in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\Network\Client\DicomClient.cs:line 239
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dicom.Network.Client.States.DicomClientIdleState.<SendAsync>d__5.MoveNext() in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\Network\Client\States\DicomClientIdleState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dicom.Network.Client.DicomClient.<SendAsync>d__117.MoveNext() in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\Network\Client\DicomClient.cs:line 333
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WindowsFormsApplication1.Form1.<button1_Click>d__5.MoveNext() in D:\Programs\Csh\DICOM Images\PACS SCU (Client)\Form1.cs:line 85`

**Expected behavior**
The DCM image correctly send by client and receive by server as run in C# console project.

**Environment**
Fo-dicom Desktop version=4.0.7
OS: (Windows 10 x64)
Platform: (.NET Framework 4.7.2)

**Comment by gofal** [comment]
It is hard to say without seeing your actual code.

But one thing that comes into my mind: Console is single-threaded while WPF is multithreaded. 
So, in Console application you create the DicomServer, then you hold the instance in memory and then wait in a endless loop until the app is closed. And all the time you are holding the dicomserver instance.
In WPF the main method is executed and starts a WPF form. then the wpf form is living while the main method finishes. If you create the dicomserver in your main-method, then this method finishes and the dicomserver is garbage collected. I also run a dicomserver in WPF. i do have a class inheriting from BackgroundWorker, start this in a separate thread and hold a reference to that thread as class variable in WPF form.

Please show the code, so that we can help you better. or forge the samples-project, push the canges you made, then I can take a look at the code.

**Comment by gofal** [comment]
Did that hint help you? Please provide more information. I will close this issue now meanwhile, but feel free to reopen it if the problem still exists and you provide more information

**Comment by HosseinMoazzam** [comment]
> Did that hint help you? Please provide more information. I will close this issue now meanwhile, but feel free to reopen it if the problem still exists and you provide more information

Thanks for your hint. The problem solved.
