### ISSUE TITLE
association request does not contain message id

### ISSUE THREAD

**Issue by SwordLieLai** [fo-dicom/fo-dicom#1288]
when device send association request that does not contain message id  Tag: (0000,0110),  method PerformDimseAsync in DicomService execute code _Logger.Info("{logId} <- {dicomMessage}", LogID, dimse.ToString(Options.LogDimseDatasets));_ will rhrow the exception,  beaucse DicomMessage ToString need to get message id tag value.

Exception info:
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 <- Association request:
Calling AE Title:          FLC1028
Called AE Title:           worklist
Remote host:               10.1.61.247
Remote port:               49313
Implementation Class:      Implementation Class UID [1.3.12.2.1107.5.3.4]
Implementation Version:    Siemens_FLC_80
Maximum PDU Length:        64234
Async Ops Invoked:         1
Async Ops Performed:       1
Presentation Contexts:     2
  Presentation Context:     1 [Proposed]
       Abstract Syntax:     Verification SOP Class
       Transfer Syntax:     Explicit VR Little Endian
       Transfer Syntax:     Implicit VR Little Endian: Default Transfer Syntax for DICOM
       Transfer Syntax:     Explicit VR Big Endian (Retired)
  Presentation Context:     3 [Proposed]
       Abstract Syntax:     Modality Worklist Information Model - FIND
       Transfer Syntax:     Explicit VR Little Endian
       Transfer Syntax:     Implicit VR Little Endian: Default Transfer Syntax for DICOM
       Transfer Syntax:     Explicit VR Big Endian (Retired)
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|Receive dicom association request, CalledAE:worklist, CallingAE:FLC1028, IP:10.1.61.247.
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|Receive client node FLC1028 dicom association request.
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> Association accept:
Calling AE Title:          FLC1028
Called AE Title:           worklist
Remote host:               10.1.61.247
Remote port:               49313
Implementation Class:      Implementation Class UID [1.3.12.2.1107.5.3.4]
Implementation Version:    Siemens_FLC_80
Maximum PDU Length:        64234
Async Ops Invoked:         1
Async Ops Performed:       1
Presentation Contexts:     2
  Presentation Context:     1 [Accept]
       Abstract Syntax:     Verification SOP Class
       Transfer Syntax:     Explicit VR Little Endian
  Presentation Context:     3 [Accept]
       Abstract Syntax:     Modality Worklist Information Model - FIND
       Transfer Syntax:     Explicit VR Little Endian
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 <- C-Find request [124]
2021-12-01 10:49:46.8916|WARN|CfSoft.DcmService.Core.DcmLogger|C-Find request do not contain message id dicom tag, calling ae:FLC1028
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|Worklist request condition -- modality:CR.
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.8916|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9072|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9228|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9384|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9540|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9696|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:46.9852|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0008|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Pending
2021-12-01 10:49:47.0164|INFO|CfSoft.DcmService.Core.DcmLogger|FLC1028 -> C-Find response [124]: Success
2021-12-01 10:49:47.4220|ERROR|CfSoft.DcmService.Core.DcmLogger|Exception processing P-Data-TF PDU: Dicom.DicomDataException: Tag: (0000,0110) not found in dataset
   at Dicom.DicomDataset.ValidateDicomTag(DicomTag tag, DicomItem& item)
   at Dicom.DicomDataset.GetSingleValue[T](DicomTag tag)
   at Dicom.Network.DicomMessage.ToString()
   at Dicom.Network.DicomMessage.ToString(Boolean printDatasets)
   at Dicom.Network.DicomService.<PerformDimseAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__62.MoveNext()
2021-12-01 10:49:47.5156|ERROR|CfSoft.DcmService.Core.DcmLogger|Exception processing PDU: Dicom.DicomDataException: Tag: (0000,0110) not found in dataset
   at Dicom.DicomDataset.ValidateDicomTag(DicomTag tag, DicomItem& item)
   at Dicom.DicomDataset.GetSingleValue[T](DicomTag tag)
   at Dicom.Network.DicomMessage.ToString()
   at Dicom.Network.DicomMessage.ToString(Boolean printDatasets)
   at Dicom.Network.DicomService.<PerformDimseAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__61.MoveNext()
2021-12-01 10:49:47.5312|ERROR|CfSoft.DcmService.Core.DcmLogger|Connection width AE: FLC1028, IP: 10.1.61.247 close throw a exception: Dicom.DicomDataException: Tag: (0000,0110) not found in dataset
   at Dicom.DicomDataset.ValidateDicomTag(DicomTag tag, DicomItem& item)
   at Dicom.DicomDataset.GetSingleValue[T](DicomTag tag)
   at Dicom.Network.DicomMessage.ToString()
   at Dicom.Network.DicomMessage.ToString(Boolean printDatasets)
   at Dicom.Network.DicomService.<PerformDimseAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__61.MoveNext()
2021-12-01 10:49:47.5312|INFO|CfSoft.DcmService.Core.DcmLogger|Connection closed

version:  4.0.7
OS: windows server 2008 R2
Platform: .NET Framework 4.6.1

**Comment by amoerie** [comment]
So the error only occurs if LogDimseDatasets is true? 
Isn't message ID a required DICOM tag though?

**Comment by SwordLieLai** [comment]
> So the error only occurs if LogDimseDatasets is true? Isn't message ID a required DICOM tag though?

Even LogDimseDatasets is false, it still call DicomMessage.ToString() Method.
![image](https://user-images.githubusercontent.com/29753973/145807856-8c79b167-cb0f-4590-b29d-1cd50ffb42f3.png)
DicomMessage.ToString() is called by PerformDimseAsync
![image](https://user-images.githubusercontent.com/29753973/145808199-c62b98a7-e57e-45c5-a9c3-43c82c545d4f.png)

Is a good idea that the logger throw a exception and affect the real code? Should we let the code continue to execute then throw exception in a place where really use message id tag to do some meanful thing?

**Comment by gofal** [comment]
totally agree. while of course the messageid is mandatory, a logging-message should not throw an exception and break the application. 
about the note, that this exception then only should throw if you have turned on full logging. I took a quick look into the code. There is a log of string building done that is not necessary, because logging may be turned off, but still all the messages are built in memory. This gives some room for optimization.

**Comment by gofal** [comment]
created a separate issue #1314 for optimizing the building of log-strings
