### ISSUE TITLE
With 5.0.2 the C-Echo is not returning due to an exception in the handle association

### ISSUE THREAD

**Issue by MarcoK80** [fo-dicom/fo-dicom#1343]
Hi, since version 5.0.2 (works in version 5.0.0) a normal C-Echo to a test server do not return and the server shows:

[DEBUG] [IDLE] --> [CONNECTING]
[DEBUG] [CONNECTING] --> [REQUESTING ASSOCIATION]
[INFO] PluginAET -> Association request:
Calling AE Title:       ReceiverPluginAET
Called AE Title:        PluginAET
Remote host:            localhost
Remote port:            1234
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.2
Maximum PDU Length:     0
Async Ops Invoked:      0
Async Ops Performed:    0
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[ERROR] Exception processing PDU: FellowOakDicom.Network.DicomNetworkException: Pdu[type=01, length=211] (offset=211, bytes=1, field="Item-Type") Requested offset out of range!
   at FellowOakDicom.Network.RawPDU.CheckOffset(Int32 bytes, String name)
   at FellowOakDicom.Network.RawPDU.ReadByte(String name)
   at FellowOakDicom.Network.AAssociateRQ.Read(RawPDU raw)
   at FellowOakDicom.Network.DicomService.<ListenAndProcessPDUAsync>d__71.MoveNext()
[INFO] Connection closed

Code used for client:
```
 var dicomClient = DicomClientFactory.Create(myPluginHostName, myPluginPort, false, myReceiverAET, mypluginAET);
                    dicomClient.NegotiateAsyncOps();
                    await dicomClient.AddRequestAsync(new DicomCEchoRequest()).ConfigureAwait(false);

                    await dicomClient.SendAsync().ConfigureAwait(false);
                    
```

ServerCode
```
 public class QRService : DicomService, IDicomServiceProvider, IDicomCStoreProvider, IDicomCEchoProvider
    {
        private static string StoragePath = @".\DICOMStorage";

        private static readonly DicomTransferSyntax[] AcceptedTransferSyntaxes = new DicomTransferSyntax[]
            {
                DicomTransferSyntax.ExplicitVRLittleEndian,
                DicomTransferSyntax.ExplicitVRBigEndian,
                DicomTransferSyntax.ImplicitVRLittleEndian
            };

        private static readonly DicomTransferSyntax[] AcceptedImageTransferSyntaxes = new DicomTransferSyntax[]
            {
                // Lossless
                DicomTransferSyntax.JPEGLSLossless,
                DicomTransferSyntax.JPEG2000Lossless,
                DicomTransferSyntax.JPEGProcess14SV1,
                DicomTransferSyntax.JPEGProcess14,
                DicomTransferSyntax.RLELossless,

                // Lossy
                DicomTransferSyntax.JPEGLSNearLossless,
                DicomTransferSyntax.JPEG2000Lossy,
                DicomTransferSyntax.JPEGProcess1,
                DicomTransferSyntax.JPEGProcess2_4,

                // Uncompressed
                DicomTransferSyntax.ExplicitVRLittleEndian,
                DicomTransferSyntax.ExplicitVRBigEndian,
                DicomTransferSyntax.ImplicitVRLittleEndian
            };

        public string CallingAE { get; protected set; }
        public string CalledAE { get; protected set; }
        public IPAddress RemoteIP { get; private set; }

        public QRService(INetworkStream stream, Encoding fallbackEncoding, ILogger logger, ILogManager logManager, INetworkManager networkManager, ITranscoderManager transcoderManager) : base(stream, fallbackEncoding, logger, logManager, networkManager, transcoderManager)
        {
            var pi = stream.GetType().GetProperty("Socket", BindingFlags.NonPublic | BindingFlags.Instance);
            if (pi != null)
            {
                var endPoint = ((Socket)pi.GetValue(stream, null)).RemoteEndPoint as IPEndPoint;
                RemoteIP = endPoint.Address;
            }
            else
            {
                RemoteIP = new IPAddress(new byte[] { 127, 0, 0, 1 });
            }
            if (!Directory.Exists(StoragePath))
            {
                Directory.CreateDirectory(StoragePath);
            }
        }

        public Task<DicomCEchoResponse> OnCEchoRequestAsync(DicomCEchoRequest request)
        {
            Logger.Info($"Received verification request from AE {CallingAE} with IP: {RemoteIP}");
            return Task.FromResult(new DicomCEchoResponse(request, DicomStatus.Success));
        }

        public void OnConnectionClosed(Exception exception)
        {
        }

        public void OnReceiveAbort(DicomAbortSource source, DicomAbortReason reason)
        {
            //log the abort reason
            Logger.Info($"Received abort from {source}, reason is {reason}");
        }

        public Task OnReceiveAssociationReleaseRequestAsync()
        {
            return SendAssociationReleaseResponseAsync();
        }

        public Task OnReceiveAssociationRequestAsync(DicomAssociation association)
        {
            CallingAE = association.CallingAE;
            CalledAE = association.CalledAE;

            Console.WriteLine($"Received association request from AE: {CallingAE} with IP: {RemoteIP} ");

            if (QRServer.AETitle != CalledAE)
            {
                Logger.Warn($"Association with {CallingAE} rejected since called aet {CalledAE} is unknown");
                return SendAssociationRejectAsync(DicomRejectResult.Permanent, DicomRejectSource.ServiceUser, DicomRejectReason.CalledAENotRecognized);
            }

            foreach (var pc in association.PresentationContexts)
            {
                if (pc.AbstractSyntax == DicomUID.Verification)
                {
                    pc.SetResult(DicomPresentationContextResult.Accept);
                }
                else if (pc.AbstractSyntax == DicomUID.PatientRootQueryRetrieveInformationModelFind
                    || pc.AbstractSyntax == DicomUID.PatientRootQueryRetrieveInformationModelMove
                    || pc.AbstractSyntax == DicomUID.StudyRootQueryRetrieveInformationModelFind
                    || pc.AbstractSyntax == DicomUID.StudyRootQueryRetrieveInformationModelMove)
                {
                    Logger.Info($"Requested abstract syntax {pc.AbstractSyntax} from {CallingAE} supported, using AcceptedTransferSyntaxes");
                    pc.AcceptTransferSyntaxes(AcceptedTransferSyntaxes);
                }
                else if (pc.AbstractSyntax == DicomUID.PatientRootQueryRetrieveInformationModelGet
                    || pc.AbstractSyntax == DicomUID.StudyRootQueryRetrieveInformationModelGet)
                {
                    Logger.Info($"Requested abstract syntax {pc.AbstractSyntax} from {CallingAE} supported, using AcceptedImageTransferSyntaxes");
                    pc.AcceptTransferSyntaxes(AcceptedImageTransferSyntaxes);
                }
                else if (pc.AbstractSyntax.StorageCategory != DicomStorageCategory.None)
                {
                    Logger.Info($"Requested abstract syntax {pc.AbstractSyntax} from {CallingAE} supported, using AcceptedImageTransferSyntaxes");
                    pc.AcceptTransferSyntaxes(AcceptedImageTransferSyntaxes);
                }
                else
                {
                    Logger.Warn($"Requested abstract syntax {pc.AbstractSyntax} from {CallingAE} not supported");
                    pc.SetResult(DicomPresentationContextResult.RejectAbstractSyntaxNotSupported);
                }
            }

            Logger.Info($"Accepted association request from {CallingAE}");
            return SendAssociationAcceptAsync(association);
        }

        public Task<DicomCStoreResponse> OnCStoreRequestAsync(DicomCStoreRequest request)
        {
            var studyUid = request.Dataset.GetSingleValue<string>(DicomTag.StudyInstanceUID);
            var instUid = request.SOPInstanceUID.UID;

            var path = Path.GetFullPath(StoragePath);
            path = Path.Combine(path, studyUid);

            if (!Directory.Exists(path)) Directory.CreateDirectory(path);

            path = Path.Combine(path, instUid) + ".dcm";

            request.File.Save(path);

            return Task.FromResult(new DicomCStoreResponse(request, DicomStatus.Success));
        }

        public Task OnCStoreRequestExceptionAsync(string tempFileName, Exception e)
        {
            // let library handle logging and error response
            return Task.CompletedTask;
        }
    }

    public static class QRServer
    {
        private static IDicomServer _server;

        public static string AETitle { get; set; }

        public static void Start(int port, string aet)
        {
            AETitle = aet;
            _server = DicomServerFactory.Create<QRService>(port);
        }

        public static void Stop()
        {
            _server.Dispose();
        }
    }
```

**Comment by amoerie** [comment]
Hi @MarcoK80 

If I make a sample .NET Core program with the following csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="fo-dicom" Version="5.0.2" />
    </ItemGroup>

</Project>

```

and the following Program.cs:

```csharp
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Text;
using FellowOakDicom;
using FellowOakDicom.Imaging.Codec;
using FellowOakDicom.Log;
using FellowOakDicom.Network;
using FellowOakDicom.Network.Client;

var ip = "127.0.0.1";
var port = 104;
var callingAE = "TestSCU";
var calledAE = "TestSCP";

QRServer.Start(port, calledAE);
try
{
    var dicomClient = DicomClientFactory.Create(ip, port, false, callingAE, calledAE);
    dicomClient.NegotiateAsyncOps();
    await dicomClient.AddRequestAsync(new DicomCEchoRequest()).ConfigureAwait(false);
    await dicomClient.SendAsync().ConfigureAwait(false);
}
finally
{
    QRServer.Stop();
}

public class QRService : DicomService, IDicomServiceProvider, IDicomCStoreProvider, IDicomCEchoProvider
{
    private static string StoragePath = @".\DICOMStorage";

    private static readonly DicomTransferSyntax[] AcceptedTransferSyntaxes = new DicomTransferSyntax[]
    {
        DicomTransferSyntax.ExplicitVRLittleEndian,
        DicomTransferSyntax.ExplicitVRBigEndian,
        DicomTransferSyntax.ImplicitVRLittleEndian
    };

    private static readonly DicomTransferSyntax[] AcceptedImageTransferSyntaxes = new DicomTransferSyntax[]
    {
        // Lossless
        DicomTransferSyntax.JPEGLSLossless,
        DicomTransferSyntax.JPEG2000Lossless,
        DicomTransferSyntax.JPEGProcess14SV1,
        DicomTransferSyntax.JPEGProcess14,
        DicomTransferSyntax.RLELossless,

        // Lossy
        DicomTransferSyntax.JPEGLSNearLossless,
        DicomTransferSyntax.JPEG2000Lossy,
        DicomTransferSyntax.JPEGProcess1,
        DicomTransferSyntax.JPEGProcess2_4,

        // Uncompressed
        DicomTransferSyntax.ExplicitVRLittleEndian,
        DicomTransferSyntax.ExplicitVRBigEndian,
        DicomTransferSyntax.ImplicitVRLittleEndian
    };

    public string CallingAE { get; protected set; }
    public string CalledAE { get; protected set; }
    public IPAddress RemoteIP { get; private set; }

    public QRService(INetworkStream stream, Encoding fallbackEncoding, ILogger logger, ILogManager logManager, INetworkManager networkManager, ITranscoderManager transcoderManager)
        : base(stream, fallbackEncoding, logger, logManager, networkManager, transcoderManager)
    {
        var pi = stream.GetType().GetProperty("Socket", BindingFlags.NonPublic | BindingFlags.Instance);
        if (pi != null)
        {
            var endPoint = ((Socket)pi.GetValue(stream, null)).RemoteEndPoint as IPEndPoint;
            RemoteIP = endPoint.Address;
        }
        else
        {
            RemoteIP = new IPAddress(new byte[] { 127, 0, 0, 1 });
        }

        if (!Directory.Exists(StoragePath))
        {
            Directory.CreateDirectory(StoragePath);
        }
    }

    public Task<DicomCEchoResponse> OnCEchoRequestAsync(DicomCEchoRequest request)
    {
        Logger.Info($"Received verification request from AE {CallingAE} with IP: {RemoteIP}");
        return Task.FromResult(new DicomCEchoResponse(request, DicomStatus.Success));
    }

    public void OnConnectionClosed(Exception exception) { }

    public void OnReceiveAbort(DicomAbortSource source, DicomAbortReason reason)
    {
        //log the abort reason
        Logger.Info($"Received abort from {source}, reason is {reason}");
    }

    public Task OnReceiveAssociationReleaseRequestAsync()
    {
        return SendAssociationReleaseResponseAsync();
    }

    public Task OnReceiveAssociationRequestAsync(DicomAssociation association)
    {
        CallingAE = association.CallingAE;
        CalledAE = association.CalledAE;

        Console.WriteLine($"Received association request from AE: {CallingAE} with IP: {RemoteIP} ");

        if (QRServer.AETitle != CalledAE)
        {
            Logger.Warn($"Association with {CallingAE} rejected since called aet {CalledAE} is unknown");
            return SendAssociationRejectAsync(DicomRejectResult.Permanent, DicomRejectSource.ServiceUser, DicomRejectReason.CalledAENotRecognized);
        }

        foreach (var pc in association.PresentationContexts)
        {
            if (pc.AbstractSyntax == DicomUID.Verification)
            {
                pc.SetResult(DicomPresentationContextResult.Accept);
            }
            else if (pc.AbstractSyntax == DicomUID.PatientRootQueryRetrieveInformationModelFind
                     || pc.AbstractSyntax == DicomUID.PatientRootQueryRetrieveInformationModelMove
                     || pc.AbstractSyntax == DicomUID.StudyRootQueryRetrieveInformationModelFind
                     || pc.AbstractSyntax == DicomUID.StudyRootQueryRetrieveInformationModelMove)
            {
                Logger.Info($"Requested abstract syntax {pc.AbstractSyntax} from {CallingAE} supported, using AcceptedTransferSyntaxes");
                pc.AcceptTransferSyntaxes(AcceptedTransferSyntaxes);
            }
            else if (pc.AbstractSyntax == DicomUID.PatientRootQueryRetrieveInformationModelGet
                     || pc.AbstractSyntax == DicomUID.StudyRootQueryRetrieveInformationModelGet)
            {
                Logger.Info($"Requested abstract syntax {pc.AbstractSyntax} from {CallingAE} supported, using AcceptedImageTransferSyntaxes");
                pc.AcceptTransferSyntaxes(AcceptedImageTransferSyntaxes);
            }
            else if (pc.AbstractSyntax.StorageCategory != DicomStorageCategory.None)
            {
                Logger.Info($"Requested abstract syntax {pc.AbstractSyntax} from {CallingAE} supported, using AcceptedImageTransferSyntaxes");
                pc.AcceptTransferSyntaxes(AcceptedImageTransferSyntaxes);
            }
            else
            {
                Logger.Warn($"Requested abstract syntax {pc.AbstractSyntax} from {CallingAE} not supported");
                pc.SetResult(DicomPresentationContextResult.RejectAbstractSyntaxNotSupported);
            }
        }

        Logger.Info($"Accepted association request from {CallingAE}");
        return SendAssociationAcceptAsync(association);
    }

    public Task<DicomCStoreResponse> OnCStoreRequestAsync(DicomCStoreRequest request)
    {
        var studyUid = request.Dataset.GetSingleValue<string>(DicomTag.StudyInstanceUID);
        var instUid = request.SOPInstanceUID.UID;

        var path = Path.GetFullPath(StoragePath);
        path = Path.Combine(path, studyUid);

        if (!Directory.Exists(path)) Directory.CreateDirectory(path);

        path = Path.Combine(path, instUid) + ".dcm";

        request.File.Save(path);

        return Task.FromResult(new DicomCStoreResponse(request, DicomStatus.Success));
    }

    public Task OnCStoreRequestExceptionAsync(string tempFileName, Exception e)
    {
        // let library handle logging and error response
        return Task.CompletedTask;
    }
}

public static class QRServer
{
    private static IDicomServer _server;

    public static string AETitle { get; set; }

    public static void Start(int port, string aet)
    {
        AETitle = aet;
        _server = DicomServerFactory.Create<QRService>(port);
    }

    public static void Stop()
    {
        _server.Dispose();
    }
}
```

I get the following output:

```
[DEBUG] [IDLE] --> [CONNECTING]
[DEBUG] [CONNECTING] --> [REQUESTING ASSOCIATION]
[INFO] TestSCP -> Association request:
Calling AE Title:       TestSCU
Called AE Title:        TestSCP
Remote host:            127.0.0.1
Remote port:            104
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.2
Maximum PDU Length:     0
Async Ops Invoked:      0
Async Ops Performed:    0
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] TestSCU <- Association request:
Calling AE Title:       TestSCU
Called AE Title:        TestSCP
Remote host:            127.0.0.1
Remote port:            61438
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.2
Maximum PDU Length:     262144
Async Ops Invoked:      0
Async Ops Performed:    0
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
Received association request from AE: TestSCU with IP: 127.0.0.1
[INFO] Accepted association request from TestSCU
[INFO] TestSCU -> Association accept:
Calling AE Title:       TestSCU
Called AE Title:        TestSCP
Remote host:            127.0.0.1
Remote port:            61438
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.2
Maximum PDU Length:     262144
Async Ops Invoked:      0
Async Ops Performed:    0
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] TestSCP <- Association accept:
Calling AE Title:       TestSCU
Called AE Title:        TestSCP
Remote host:            127.0.0.1
Remote port:            104
Implementation Class:   Unknown [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.2
Maximum PDU Length:     262144
Async Ops Invoked:      0
Async Ops Performed:    0
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[DEBUG] [REQUESTING ASSOCIATION] Association is accepted
[DEBUG] [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
[DEBUG] [SENDING REQUESTS] Sending DICOM requests
[INFO] TestSCP -> C-Echo request [1]
[INFO] TestSCU <- C-Echo request [1]
[INFO] Received verification request from AE TestSCU with IP: 127.0.0.1
[INFO] TestSCU -> C-Echo response [1]: Success
[INFO] TestSCP <- C-Echo response [1]: Success
[DEBUG] [SENDING REQUESTS] All requests are done, going to linger association now...
[DEBUG] [SENDING REQUESTS] --> [LINGERING ASSOCIATION]
[DEBUG] [LINGERING ASSOCIATION] Linger timed out after 50ms, releasing association
[DEBUG] [LINGERING ASSOCIATION] --> [RELEASING ASSOCIATION]
[INFO] TestSCP -> Association release request
[INFO] TestSCU <- Association release request
[INFO] TestSCU -> Association release response
[INFO] TestSCP <- Association release response
[DEBUG] [RELEASING ASSOCIATION] Association release response received, disconnecting...
[INFO] Connection closed
[DEBUG] [RELEASING ASSOCIATION] --> [COMPLETED]
[DEBUG] [COMPLETED] DICOM client completed without errors
[DEBUG] [COMPLETED] Cleaning up
[INFO] Connection closed
[DEBUG] [COMPLETED] --> [IDLE]
[DEBUG] [IDLE] No requests to send, staying idle
```

So now the question is, what is different in your code? Something network related?

**Comment by MarcoK80** [comment]
Thx. We have tested now a lot:
1. With the FO-Dicom solution and a xunit and also Microsoft Test project and the same code > Runs and works
2. With a new test project within our solution > Runs and works
3. With the existing migrated test project to 5.0.2 > Not running well
4. With the existing migrated test project to 5.0.0 > Runs

We will continue testing to find the issue.

**Comment by amoerie** [comment]
Ok good to hear. If you can reproduce the issue in a unit test or with a sample program (for example if it can only be simulated with a remote machine) please let us know, and I might be of help with the investigation.

**Comment by gofal** [comment]
closing this issue due to inactivity. If you still have this issue with latest version of fo-dicom, please reopen this issue and provide actual information.
