### ISSUE TITLE
RenderImage failing in GetLUTDescriptor

### ISSUE THREAD

**Issue by colebabiuchsenior** [fo-dicom/fo-dicom#1369]
The attached image will not succeed when we call RenderImage().  

To reproduce, I wrote a unit test that creates a new DicomImage and calls RenderImage() i.e.
var dicomImage = new DicomImage(@"<path to file>").RenderImage();

During the RenderImage, it fails inside of GetLUTDescriptor since the VOILUTSequence does not contain any items
![image](https://user-images.githubusercontent.com/94083075/161337561-3dd0b042-5949-4bfa-ad4c-04a55325dca5.png)

We have tried this on several versions of fo-dicom including 5.0.2 
[5a178acc-32ba-4af4-8ef9-a26401a923d8.zip](https://github.com/fo-dicom/fo-dicom/files/8400745/5a178acc-32ba-4af4-8ef9-a26401a923d8.zip)

**Comment by mrbean-bremen** [comment]
Looks like you have a VOI LUT sequence with no items. This case seems not to be handled. A VOI LUT Sequence without items is not allowed in the DICOM standard, so this is not exactly a bug. But as it may happen anyway (I think I have seen some data like this), it shall be handled - probably by just being ignored. The same goes for Modality LUT Sequence.

**Comment by colebabiuchsenior** [comment]
Awesome! Thank you very much.

**Comment by colebabiuchsenior** [comment]
Hello everyone.  I saw that version 5.0.3 was recently released, but when I test it with that version I am still getting the same error that I was in 5.0.2.  Was the fix for this this item included in that release?

**Comment by mrbean-bremen** [comment]
That's strange - yes, it was included. Can you show us the callstack for this issue from 5.0.3?

**Comment by colebabiuchsenior** [comment]
This is the callstack from within our code:

   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Dicom.Imaging.LUT.VOISequenceLUT.GetLUTDescriptor()
   at Dicom.Imaging.LUT.VOISequenceLUT.Recalculate()
   at Dicom.Imaging.LUT.VOISequenceLUT..ctor(GrayscaleRenderOptions options)
   at Dicom.Imaging.Render.GenericGrayscalePipeline..ctor(GrayscaleRenderOptions options)
   at Dicom.Imaging.DicomImage.CreatePipelineData(DicomDataset dataset, DicomPixelData pixelData)
   at Dicom.Imaging.DicomImage.EstablishPipeline()
   at Dicom.Imaging.DicomImage.GetFrameIndex(Int32 frame)
   at Dicom.Imaging.DicomImage.RenderImage(Int32 frame)
   at ImageProcessing.DicomImageExtensions.RenderBitmap(DicomImage dicomImage, Int32 frame) in D:\Azure Dev Ops\FSCurrent\Solutions\StudyShare\src\BuildingBlocks\ImageProcessing\ImageProcessing\DicomImageExtensions.cs:line 27
   at ImageProcessing.JpegConverter.ConvertFrameToImage(DicomImage dicomImage, Int32 frame) in D:\Azure Dev Ops\FSCurrent\Solutions\StudyShare\src\BuildingBlocks\ImageProcessing\ImageProcessing\JpegConverter.cs:line 85
   at ImageProcessing.JpegConverter.ConvertFrame(DicomImage dicomImage, Int32 frame, String jpegPath) in D:\Azure Dev Ops\FSCurrent\Solutions\StudyShare\src\BuildingBlocks\ImageProcessing\ImageProcessing\JpegConverter.cs:line 70

**Comment by mrbean-bremen** [comment]
Thanks! I will have a closer look tomorrow, won't have more time today.

**Comment by mrbean-bremen** [comment]
Hm, I don't understand how this can happen with the current code - a `VOISequenceLUT` object simply won't be created if the VOI LUT has no items. Unfortunately, the callstack is the same as for the previous version.
I also downloaded the 5.0.3 package and verified that the fix is in, and checked that the unittests verify the behavior, so I'm a bit lost here...
Are you sure the correct version is used in your code?

**Comment by colebabiuchsenior** [comment]
Thanks for double-checking that the fix is the current code.  I'm assuming that although NuGet is saying that it is using 5.0.3, there must be a cached version that it's using somewhere.
![image](https://user-images.githubusercontent.com/94083075/170342759-5ef58fcb-358a-464c-9622-ad4226284c23.png)

I will keep looking on my end to see if NuGet and/or Visual Studio is caching it somewhere.  I really appreciate you following up and taking a look for me.

Thanks!

**Comment by mrbean-bremen** [comment]
I won't exclude that this can somehow still happen in 5.0.3, I just have no idea how. I also called `var dicomImage = new DicomImage(@"your_image.dcm").RenderImage();` with the image you have uploaded, and it works without problems under .NET Core 3.1, .NET 6 and .NET 4.6.2. 
If you can reproduce the problem using the same code with the same data in the same environment, something else must be different on your side.
