### ISSUE TITLE
5.0.3 is unable to deserialize JSON from 4.0.8

### ISSUE THREAD

**Issue by jussimattila** [fo-dicom/fo-dicom#1487]
**Describe the bug**
Our production databases consists of data produced with fo-dicom 4.0.8. We are now upgrading to 5.0.3, but have noticed that some JSON data is not deserialized anymore, after switching to use `DicomJson.ConvertJsonToDicom` in 5.0.3.

**To Reproduce**
Deserialize a specific DICOM JSON created by fo-dicom 4.0.8 with fo-dicom v5.0.3 to get the exception
```
System.Text.Json.JsonException: invalid: StartArray expected at position 3714, instead found String
   at FellowOakDicom.Serialization.Utf8JsonReaderExtensions.Assume(Utf8JsonReader& reader, JsonTokenType tokenType)
   at FellowOakDicom.Serialization.Utf8JsonReaderExtensions.AssumeAndSkip(Utf8JsonReader& reader, JsonTokenType tokenType)
   at FellowOakDicom.Serialization.DicomJsonConverter.ReadJsonInlineBinary(Utf8JsonReader& reader)
   at FellowOakDicom.Serialization.DicomJsonConverter.ReadJsonOX(Utf8JsonReader& reader)
   at FellowOakDicom.Serialization.DicomJsonConverter.ReadJsonDicomItem(DicomTag tag, Utf8JsonReader& reader)
   at FellowOakDicom.Serialization.DicomJsonConverter.ReadJsonDataset(Utf8JsonReader& reader)
```

Example code:
```
private const string Text408 = "{\"00080005\":{\"vr\":\"CS\",\"Value\":[\"ISO_IR 100\"]},\"00080008\":{\"vr\":\"CS\",\"Value\":[\"ORIGINAL\",\"PRIMARY\",\"M\",\"ND\",\"NORM\"]},\"00080013\":{\"vr\":\"TM\",\"Value\":[\"143457.625000\"]},\"00080016\":{\"vr\":\"UI\",\"Value\":[\"1.2.840.10008.5.1.4.1.1.4\"]},\"00080018\":{\"vr\":\"UI\",\"Value\":[\"2.16.124.113543.6006.99.06724864526113343401\"]},\"00080020\":{\"vr\":\"DA\",\"Value\":[\"20110725\"]},\"00080021\":{\"vr\":\"DA\",\"Value\":[\"20110725\"]},\"00080022\":{\"vr\":\"DA\",\"Value\":[\"20110725\"]},\"00080023\":{\"vr\":\"DA\",\"Value\":[\"20110725\"]},\"00080030\":{\"vr\":\"TM\",\"Value\":[\"142156\"]},\"00080031\":{\"vr\":\"TM\",\"Value\":[\"143457\"]},\"00080032\":{\"vr\":\"TM\",\"Value\":[\"142543.390000\"]},\"00080033\":{\"vr\":\"TM\",\"Value\":[\"143457.625000\"]},\"00080060\":{\"vr\":\"CS\",\"Value\":[\"MR\"]},\"00080070\":{\"vr\":\"LO\",\"Value\":[\"SIEMENS\"]},\"00080080\":{\"vr\":\"LO\",\"Value\":[\"Diagnostic Cntr\"]},\"00080090\":{\"vr\":\"PN\"},\"00081030\":{\"vr\":\"LO\",\"Value\":[\"Head^ADNI\"]},\"0008103E\":{\"vr\":\"LO\",\"Value\":[\"MPRAGE\"]},\"00081060\":{\"vr\":\"PN\"},\"00081070\":{\"vr\":\"PN\"},\"00081090\":{\"vr\":\"LO\",\"Value\":[\"Verio\"]},\"00100010\":{\"vr\":\"PN\",\"Value\":[{\"Alphabetic\":\"072_S_4131\"}]},\"00100020\":{\"vr\":\"LO\",\"Value\":[\"072_S_4131\"]},\"00100030\":{\"vr\":\"DA\",\"Value\":[\"19290215\"]},\"00100040\":{\"vr\":\"CS\",\"Value\":[\"M\"]},\"00101010\":{\"vr\":\"AS\",\"Value\":[\"082Y\"]},\"00101030\":{\"vr\":\"DS\",\"Value\":[90.71848554]},\"00180015\":{\"vr\":\"CS\",\"Value\":[\"HEAD\"]},\"00180020\":{\"vr\":\"CS\",\"Value\":[\"GR\",\"IR\"]},\"00180021\":{\"vr\":\"CS\",\"Value\":[\"SP\",\"MP\"]},\"00180022\":{\"vr\":\"CS\",\"Value\":[\"IR\"]},\"00180023\":{\"vr\":\"CS\",\"Value\":[\"3D\"]},\"00180024\":{\"vr\":\"SH\",\"Value\":[\"*tfl3d1_ns\"]},\"00180025\":{\"vr\":\"CS\",\"Value\":[\"N\"]},\"00180050\":{\"vr\":\"DS\",\"Value\":[1.1999999284744]},\"00180080\":{\"vr\":\"DS\",\"Value\":[2300]},\"00180081\":{\"vr\":\"DS\",\"Value\":[2.98]},\"00180082\":{\"vr\":\"DS\",\"Value\":[900]},\"00180083\":{\"vr\":\"DS\",\"Value\":[1]},\"00180084\":{\"vr\":\"DS\",\"Value\":[123.202168]},\"00180085\":{\"vr\":\"SH\",\"Value\":[\"1H\"]},\"00180086\":{\"vr\":\"IS\",\"Value\":[1]},\"00180087\":{\"vr\":\"DS\",\"Value\":[3]},\"00180089\":{\"vr\":\"IS\",\"Value\":[240]},\"00180091\":{\"vr\":\"IS\",\"Value\":[1]},\"00180093\":{\"vr\":\"DS\",\"Value\":[100]},\"00180094\":{\"vr\":\"DS\",\"Value\":[93.75]},\"00180095\":{\"vr\":\"DS\",\"Value\":[238]},\"00181000\":{\"vr\":\"LO\",\"Value\":[\"4qARRy6n7izw\"]},\"00181020\":{\"vr\":\"LO\",\"Value\":[\"syngo MR B17\"]},\"00181030\":{\"vr\":\"LO\",\"Value\":[\"MPRAGE\"]},\"00181251\":{\"vr\":\"SH\",\"Value\":[\"Body\"]},\"00181310\":{\"vr\":\"US\",\"Value\":[0,256,240,0]},\"00181312\":{\"vr\":\"CS\",\"Value\":[\"ROW\"]},\"00181314\":{\"vr\":\"DS\",\"Value\":[9]},\"00181315\":{\"vr\":\"CS\",\"Value\":[\"N\"]},\"00181316\":{\"vr\":\"DS\",\"Value\":[0.02979412242508]},\"00181318\":{\"vr\":\"DS\",\"Value\":[0]},\"00185100\":{\"vr\":\"CS\",\"Value\":[\"HFS\"]},\"00190010\":{\"vr\":\"LO\",\"Value\":[\"SIEMENS MR HEADER\"]},\"0020000D\":{\"vr\":\"UI\",\"Value\":[\"2.16.124.113543.6006.99.04141957255720241367\"]},\"0020000E\":{\"vr\":\"UI\",\"Value\":[\"2.16.124.113543.6006.99.4124240299532997428\"]},\"00200010\":{\"vr\":\"SH\",\"Value\":[\"494430\"]},\"00200011\":{\"vr\":\"IS\",\"Value\":[2]},\"00200012\":{\"vr\":\"IS\",\"Value\":[1]},\"00200013\":{\"vr\":\"IS\",\"Value\":[115]},\"00200032\":{\"vr\":\"DS\",\"Value\":[31.799999540502,-121.35593223572,128]},\"00200037\":{\"vr\":\"DS\",\"Value\":[0,1,0,0,0,-1]},\"00200052\":{\"vr\":\"UI\",\"Value\":[\"2.16.124.113543.6006.99.02942329729120267962\"]},\"00201040\":{\"vr\":\"LO\"},\"00201041\":{\"vr\":\"DS\",\"Value\":[31.799999540502]},\"00280002\":{\"vr\":\"US\",\"Value\":[1]},\"00280004\":{\"vr\":\"CS\",\"Value\":[\"MONOCHROME2\"]},\"00280010\":{\"vr\":\"US\",\"Value\":[256]},\"00280011\":{\"vr\":\"US\",\"Value\":[240]},\"00280030\":{\"vr\":\"DS\",\"Value\":[1,1]},\"00280100\":{\"vr\":\"US\",\"Value\":[16]},\"00280101\":{\"vr\":\"US\",\"Value\":[12]},\"00280102\":{\"vr\":\"US\",\"Value\":[11]},\"00280103\":{\"vr\":\"US\",\"Value\":[0]},\"00280106\":{\"vr\":\"US\",\"Value\":[0]},\"00280107\":{\"vr\":\"US\",\"Value\":[963]},\"00281050\":{\"vr\":\"DS\",\"Value\":[348]},\"00281051\":{\"vr\":\"DS\",\"Value\":[760]},\"00291010\":{\"vr\":\"UN\",\"InlineBinary\":\"U1YxMAQDAgFTAAAATQAAAEVjaG9MaW5lUG9zaXRpb24AAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABNAAAATQAAAP////ClWQzwpVkMAQAAAElTAAAGAAAAAAAAAM0AAABRQ0RhdGEACiAgfQogIAogIDxQYXJhbU1hcC4iIiIiPiAKICB7CiAgICAKICAgIDxQYXJhbUxvbmcuIiJMb2FkAAAAAEZEAAAEAAAAAAAAAM0AAAAAAAAA\"},\"00291020\":{\"vr\":\"UN\",\"InlineBinary\":\"U1YxMAQDAgFBAAAATQAAAFVzZWRQYXRpZW50V2VpZ2h0AHsKICAgIAogICAgPFBhcmFtQm9vbC4iSXNJbmxpbmVDb21wb3NlZCI+IHsiIk11bHRpU3RlcC5Jc00BAAAAVVQAABsAAAAAAAAAzQAAAFJGU1dET3BlcmF0aW9uTW9kZQBDb2RlTWVhbmluZyIiICIiRE1XTC5NZWFzLkNvZGVWYWx1ZSIiICIiRE1XTC4BAAAAU1MAAAgAAAAGAAAATQAAAAkAAAAJAAAATQAAAAkAAAArMCAgICAgIAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAFJGU1dETW9zdENyaXRpY2FsQXNwZWN0AHVuZF9VSSIiPiB7IiJQcm9wZXJ0aWVzLlNvdW5kLlBvc3RTb3VuZE8BAAAAU0gAABYAAAAGAAAATQAAAAwAAAAMAAAATQAAAAwAAABUb3JzbyBMb2NhbAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAFNBUk1vc3RDcml0aWNhbEFzcGVjdAAuIlBhdGllbnQiPiAgeyAiMTAuMC4yMjczMDAwMTQiICB9CiAgICAgICADAAAARFMAAAMAAAAGAAAATQAAAAwAAAAMAAAATQAAAAwAAAAxMC4wMDAwMDAwMAALAAAACwAAAE0AAAALAAAAMC44NTU2NTAwOAAACwAAAAsAAABNAAAACwAAADAuNjM3OTgwODIAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAFRhYmxlUG9zaXRpb25PcmlnaW4AICAgICAgfQogICAgfQogIH0KfQpiA5kIBD0pbgAAAAAAAAAAiEp6TgAAAAADAAAAU0wAAAcAAAAGAAAATQAAAAkAAAAJAAAATQAAAAkAAAAwICAgICAgIAAAAAAJAAAACQAAAE0AAAAJAAAAMCAgICAgICAAAAAACQAAAAkAAABNAAAACQAAAC0xMDY1ICAgAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAE1yUHJvdG9jb2wAAHBJ7hR8S1YMfEtWDAxMVgwAAAAAAAAAAAAAAAAITFYMCExWDAAAAAAAAAAAAAAAAGhnl04BAAAAVU4AAAAAAAAAAAAAzQAAAE1yRXZhUHJvdG9jb2wAAAAAAAAAiEp6TgAAAAAAAAAAZE1WDABf8xRYTVYMWE1WDAAAAAAAAAAAAAAAAAAAAAABAAAAVU4AAAAAAAAAAAAAzQAAAFZGTW9kZWxJbmZvAAAAAAAEPSluAAAAAAAAAACISnpOAAAAAAAAAACoTlYMOE5WDDhOVgzITlYMAAAAAP5d8xQBAAAAVU4AAAAAAAAAAAAAzQAAAFZGU2V0dGluZ3MAAP1c8xTgT1YM4E9WDAAAAAAAAAAAAAAAAAQ9KW4AAAAAAAAAAIhKek4AAAAAAAAAACBQVgwBAAAAVU4AAAAAAAAAAAAAzQAAAEF1dG9BbGlnbkRhdGEAl04wUVYMMFFWDAAAAAAAAAAAAAAAAL1b8xRIUVYMBD0pbgAAAAAAAAAAiEp6TgAAAAABAAAATFQAABQAAAAAAAAAzQAAAEZtcmlNb2RlbFBhcmFtZXRlcnMADFJWDJxSVgwAAAAAAAAAAGhnl06YUlYMmFJWDAAAAAAAAAAAAAAAAGpa8xQBAAAAVVQAABsAAAAAAAAAzQAAAEZtcmlNb2RlbEluZm8AAAAAAAAAiEp6TgAAAAAAAAAA9FNWDAAAAADoU1YM6FNWDAAAAAAAAAAAAAAAAGhnl04BAAAAVVQAABsAAAAAAAAAzQAAAEZtcmlFeHRlcm5hbFBhcmFtZXRlcnMAAAAAAACISnpOAAAAAAAAAAA4VVYMyFRWDMhUVgxYVVYMAAAAAEhVVgwBAAAAVVQAABsAAAAAAAAAzQAAAEZtcmlFeHRlcm5hbEluZm8AVlYMcFZWDAAAAAAAAAAAAAAAAAQ9KW4AAAAAAAAAAIhKek4AAAAAAAAAALBWVgwBAAAAVVQAABsAAAAAAAAAzQAAAEIxcm1zAFYMAAAAALhXVgzAV1YMwFdWDAAAAAAAAAAAAAAAANBXVgzYV1YMBD0pbgAAAAAAAAAAiEp6TgAAAAACAAAARFMAAAMAAAAGAAAATQAAAAsAAAALAAAATQAAAAsAAAA3LjA3MTA2NzgxAAALAAAACwAAAE0AAAALAAAAMC44MTI3MTgwNgAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAEIxcm1zU3VwZXJ2aXNpb24AWFYMnFhWDCxZVgwAAAAAAAAAACBZVgwoWVYMKFlWDAAAAAAAAAAAAAAAADhZVgwBAAAAQ1MAABAAAAAGAAAATQAAAAMAAAADAAAATQAAAAMAAABOTwAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAABUYWxlc1JlZmVyZW5jZVBvd2VyAIhKek4AAAAAAAAAAIRaVgwAWlYMeFpWDHhaVgwAAAAAAAAAAAAAAACIWlYMAQAAAERTAAADAAAABgAAAE0AAAAOAAAADgAAAE0AAAAOAAAAMjk0MS42NzA0ODk4MgAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAA==\"},\"00400245\":{\"vr\":\"TM\",\"Value\":[\"142156.125000\"]},\"00511016\":{\"vr\":\"UN\",\"InlineBinary\":\"TS9ORC9OT1JNIA==\"}}";

private const string Text503 = "{\"00080005\":{\"vr\":\"CS\",\"Value\":[\"ISO_IR 100\"]},\"00080008\":{\"vr\":\"CS\",\"Value\":[\"ORIGINAL\",\"PRIMARY\",\"M\",\"ND\",\"NORM\"]},\"00080013\":{\"vr\":\"TM\",\"Value\":[\"143457.625000\"]},\"00080016\":{\"vr\":\"UI\",\"Value\":[\"1.2.840.10008.5.1.4.1.1.4\"]},\"00080018\":{\"vr\":\"UI\",\"Value\":[\"2.16.124.113543.6006.99.06724864526113343401\"]},\"00080020\":{\"vr\":\"DA\",\"Value\":[\"20110725\"]},\"00080021\":{\"vr\":\"DA\",\"Value\":[\"20110725\"]},\"00080022\":{\"vr\":\"DA\",\"Value\":[\"20110725\"]},\"00080023\":{\"vr\":\"DA\",\"Value\":[\"20110725\"]},\"00080030\":{\"vr\":\"TM\",\"Value\":[\"142156\"]},\"00080031\":{\"vr\":\"TM\",\"Value\":[\"143457\"]},\"00080032\":{\"vr\":\"TM\",\"Value\":[\"142543.390000\"]},\"00080033\":{\"vr\":\"TM\",\"Value\":[\"143457.625000\"]},\"00080060\":{\"vr\":\"CS\",\"Value\":[\"MR\"]},\"00080070\":{\"vr\":\"LO\",\"Value\":[\"SIEMENS\"]},\"00080080\":{\"vr\":\"LO\",\"Value\":[\"Diagnostic Cntr\"]},\"00080090\":{\"vr\":\"PN\"},\"00081030\":{\"vr\":\"LO\",\"Value\":[\"Head^ADNI\"]},\"0008103E\":{\"vr\":\"LO\",\"Value\":[\"MPRAGE\"]},\"00081060\":{\"vr\":\"PN\"},\"00081070\":{\"vr\":\"PN\"},\"00081090\":{\"vr\":\"LO\",\"Value\":[\"Verio\"]},\"00100010\":{\"vr\":\"PN\",\"Value\":[{\"Alphabetic\":\"072_S_4131\"}]},\"00100020\":{\"vr\":\"LO\",\"Value\":[\"072_S_4131\"]},\"00100030\":{\"vr\":\"DA\",\"Value\":[\"19290215\"]},\"00100040\":{\"vr\":\"CS\",\"Value\":[\"M\"]},\"00101010\":{\"vr\":\"AS\",\"Value\":[\"082Y\"]},\"00101030\":{\"vr\":\"DS\",\"Value\":[90.71848554]},\"00180015\":{\"vr\":\"CS\",\"Value\":[\"HEAD\"]},\"00180020\":{\"vr\":\"CS\",\"Value\":[\"GR\",\"IR\"]},\"00180021\":{\"vr\":\"CS\",\"Value\":[\"SP\",\"MP\"]},\"00180022\":{\"vr\":\"CS\",\"Value\":[\"IR\"]},\"00180023\":{\"vr\":\"CS\",\"Value\":[\"3D\"]},\"00180024\":{\"vr\":\"SH\",\"Value\":[\"*tfl3d1_ns\"]},\"00180025\":{\"vr\":\"CS\",\"Value\":[\"N\"]},\"00180050\":{\"vr\":\"DS\",\"Value\":[1.1999999284744]},\"00180080\":{\"vr\":\"DS\",\"Value\":[2300]},\"00180081\":{\"vr\":\"DS\",\"Value\":[2.98]},\"00180082\":{\"vr\":\"DS\",\"Value\":[900]},\"00180083\":{\"vr\":\"DS\",\"Value\":[1]},\"00180084\":{\"vr\":\"DS\",\"Value\":[123.202168]},\"00180085\":{\"vr\":\"SH\",\"Value\":[\"1H\"]},\"00180086\":{\"vr\":\"IS\",\"Value\":[1]},\"00180087\":{\"vr\":\"DS\",\"Value\":[3]},\"00180089\":{\"vr\":\"IS\",\"Value\":[240]},\"00180091\":{\"vr\":\"IS\",\"Value\":[1]},\"00180093\":{\"vr\":\"DS\",\"Value\":[100]},\"00180094\":{\"vr\":\"DS\",\"Value\":[93.75]},\"00180095\":{\"vr\":\"DS\",\"Value\":[238]},\"00181000\":{\"vr\":\"LO\",\"Value\":[\"4qARRy6n7izw\"]},\"00181020\":{\"vr\":\"LO\",\"Value\":[\"syngo MR B17\"]},\"00181030\":{\"vr\":\"LO\",\"Value\":[\"MPRAGE\"]},\"00181251\":{\"vr\":\"SH\",\"Value\":[\"Body\"]},\"00181310\":{\"vr\":\"US\",\"Value\":[0,256,240,0]},\"00181312\":{\"vr\":\"CS\",\"Value\":[\"ROW\"]},\"00181314\":{\"vr\":\"DS\",\"Value\":[9]},\"00181315\":{\"vr\":\"CS\",\"Value\":[\"N\"]},\"00181316\":{\"vr\":\"DS\",\"Value\":[0.02979412242508]},\"00181318\":{\"vr\":\"DS\",\"Value\":[0]},\"00185100\":{\"vr\":\"CS\",\"Value\":[\"HFS\"]},\"00190010\":{\"vr\":\"LO\",\"Value\":[\"SIEMENS MR HEADER\"]},\"0020000D\":{\"vr\":\"UI\",\"Value\":[\"2.16.124.113543.6006.99.04141957255720241367\"]},\"0020000E\":{\"vr\":\"UI\",\"Value\":[\"2.16.124.113543.6006.99.4124240299532997428\"]},\"00200010\":{\"vr\":\"SH\",\"Value\":[\"494430\"]},\"00200011\":{\"vr\":\"IS\",\"Value\":[2]},\"00200012\":{\"vr\":\"IS\",\"Value\":[1]},\"00200013\":{\"vr\":\"IS\",\"Value\":[115]},\"00200032\":{\"vr\":\"DS\",\"Value\":[31.799999540502,-121.35593223572,128]},\"00200037\":{\"vr\":\"DS\",\"Value\":[0,1,0,0,0,-1]},\"00200052\":{\"vr\":\"UI\",\"Value\":[\"2.16.124.113543.6006.99.02942329729120267962\"]},\"00201040\":{\"vr\":\"LO\"},\"00201041\":{\"vr\":\"DS\",\"Value\":[31.799999540502]},\"00280002\":{\"vr\":\"US\",\"Value\":[1]},\"00280004\":{\"vr\":\"CS\",\"Value\":[\"MONOCHROME2\"]},\"00280010\":{\"vr\":\"US\",\"Value\":[256]},\"00280011\":{\"vr\":\"US\",\"Value\":[240]},\"00280030\":{\"vr\":\"DS\",\"Value\":[1,1]},\"00280100\":{\"vr\":\"US\",\"Value\":[16]},\"00280101\":{\"vr\":\"US\",\"Value\":[12]},\"00280102\":{\"vr\":\"US\",\"Value\":[11]},\"00280103\":{\"vr\":\"US\",\"Value\":[0]},\"00280106\":{\"vr\":\"US\",\"Value\":[0]},\"00280107\":{\"vr\":\"US\",\"Value\":[963]},\"00281050\":{\"vr\":\"DS\",\"Value\":[348]},\"00281051\":{\"vr\":\"DS\",\"Value\":[760]},\"00291010\":{\"vr\":\"UN\",\"InlineBinary\":[\"U1YxMAQDAgFTAAAATQAAAEVjaG9MaW5lUG9zaXRpb24AAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABNAAAATQAAAP////ClWQzwpVkMAQAAAElTAAAGAAAAAAAAAM0AAABRQ0RhdGEACiAgfQogIAogIDxQYXJhbU1hcC4iIiIiPiAKICB7CiAgICAKICAgIDxQYXJhbUxvbmcuIiJMb2FkAAAAAEZEAAAEAAAAAAAAAM0AAAAAAAAA\"]},\"00291020\":{\"vr\":\"UN\",\"InlineBinary\":[\"U1YxMAQDAgFBAAAATQAAAFVzZWRQYXRpZW50V2VpZ2h0AHsKICAgIAogICAgPFBhcmFtQm9vbC4iSXNJbmxpbmVDb21wb3NlZCI+IHsiIk11bHRpU3RlcC5Jc00BAAAAVVQAABsAAAAAAAAAzQAAAFJGU1dET3BlcmF0aW9uTW9kZQBDb2RlTWVhbmluZyIiICIiRE1XTC5NZWFzLkNvZGVWYWx1ZSIiICIiRE1XTC4BAAAAU1MAAAgAAAAGAAAATQAAAAkAAAAJAAAATQAAAAkAAAArMCAgICAgIAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAFJGU1dETW9zdENyaXRpY2FsQXNwZWN0AHVuZF9VSSIiPiB7IiJQcm9wZXJ0aWVzLlNvdW5kLlBvc3RTb3VuZE8BAAAAU0gAABYAAAAGAAAATQAAAAwAAAAMAAAATQAAAAwAAABUb3JzbyBMb2NhbAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAFNBUk1vc3RDcml0aWNhbEFzcGVjdAAuIlBhdGllbnQiPiAgeyAiMTAuMC4yMjczMDAwMTQiICB9CiAgICAgICADAAAARFMAAAMAAAAGAAAATQAAAAwAAAAMAAAATQAAAAwAAAAxMC4wMDAwMDAwMAALAAAACwAAAE0AAAALAAAAMC44NTU2NTAwOAAACwAAAAsAAABNAAAACwAAADAuNjM3OTgwODIAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAFRhYmxlUG9zaXRpb25PcmlnaW4AICAgICAgfQogICAgfQogIH0KfQpiA5kIBD0pbgAAAAAAAAAAiEp6TgAAAAADAAAAU0wAAAcAAAAGAAAATQAAAAkAAAAJAAAATQAAAAkAAAAwICAgICAgIAAAAAAJAAAACQAAAE0AAAAJAAAAMCAgICAgICAAAAAACQAAAAkAAABNAAAACQAAAC0xMDY1ICAgAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAE1yUHJvdG9jb2wAAHBJ7hR8S1YMfEtWDAxMVgwAAAAAAAAAAAAAAAAITFYMCExWDAAAAAAAAAAAAAAAAGhnl04BAAAAVU4AAAAAAAAAAAAAzQAAAE1yRXZhUHJvdG9jb2wAAAAAAAAAiEp6TgAAAAAAAAAAZE1WDABf8xRYTVYMWE1WDAAAAAAAAAAAAAAAAAAAAAABAAAAVU4AAAAAAAAAAAAAzQAAAFZGTW9kZWxJbmZvAAAAAAAEPSluAAAAAAAAAACISnpOAAAAAAAAAACoTlYMOE5WDDhOVgzITlYMAAAAAP5d8xQBAAAAVU4AAAAAAAAAAAAAzQAAAFZGU2V0dGluZ3MAAP1c8xTgT1YM4E9WDAAAAAAAAAAAAAAAAAQ9KW4AAAAAAAAAAIhKek4AAAAAAAAAACBQVgwBAAAAVU4AAAAAAAAAAAAAzQAAAEF1dG9BbGlnbkRhdGEAl04wUVYMMFFWDAAAAAAAAAAAAAAAAL1b8xRIUVYMBD0pbgAAAAAAAAAAiEp6TgAAAAABAAAATFQAABQAAAAAAAAAzQAAAEZtcmlNb2RlbFBhcmFtZXRlcnMADFJWDJxSVgwAAAAAAAAAAGhnl06YUlYMmFJWDAAAAAAAAAAAAAAAAGpa8xQBAAAAVVQAABsAAAAAAAAAzQAAAEZtcmlNb2RlbEluZm8AAAAAAAAAiEp6TgAAAAAAAAAA9FNWDAAAAADoU1YM6FNWDAAAAAAAAAAAAAAAAGhnl04BAAAAVVQAABsAAAAAAAAAzQAAAEZtcmlFeHRlcm5hbFBhcmFtZXRlcnMAAAAAAACISnpOAAAAAAAAAAA4VVYMyFRWDMhUVgxYVVYMAAAAAEhVVgwBAAAAVVQAABsAAAAAAAAAzQAAAEZtcmlFeHRlcm5hbEluZm8AVlYMcFZWDAAAAAAAAAAAAAAAAAQ9KW4AAAAAAAAAAIhKek4AAAAAAAAAALBWVgwBAAAAVVQAABsAAAAAAAAAzQAAAEIxcm1zAFYMAAAAALhXVgzAV1YMwFdWDAAAAAAAAAAAAAAAANBXVgzYV1YMBD0pbgAAAAAAAAAAiEp6TgAAAAACAAAARFMAAAMAAAAGAAAATQAAAAsAAAALAAAATQAAAAsAAAA3LjA3MTA2NzgxAAALAAAACwAAAE0AAAALAAAAMC44MTI3MTgwNgAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAEIxcm1zU3VwZXJ2aXNpb24AWFYMnFhWDCxZVgwAAAAAAAAAACBZVgwoWVYMKFlWDAAAAAAAAAAAAAAAADhZVgwBAAAAQ1MAABAAAAAGAAAATQAAAAMAAAADAAAATQAAAAMAAABOTwAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAABUYWxlc1JlZmVyZW5jZVBvd2VyAIhKek4AAAAAAAAAAIRaVgwAWlYMeFpWDHhaVgwAAAAAAAAAAAAAAACIWlYMAQAAAERTAAADAAAABgAAAE0AAAAOAAAADgAAAE0AAAAOAAAAMjk0MS42NzA0ODk4MgAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAAAAAADNAAAAAAAAAAAAAAAAAAAAzQAAAAAAAAAAAAAAAAAAAM0AAAAAAAAAAAAAAA==\"]},\"00400245\":{\"vr\":\"TM\",\"Value\":[\"142156.125000\"]},\"00511016\":{\"vr\":\"UN\",\"InlineBinary\":[\"TS9ORC9OT1JNIA==\"]}}";

// This succeeds
DicomJson.ConvertJsonToDicom(Text503, false); 

// This fails
DicomJson.ConvertJsonToDicom(Text408, false); 
```
**Expected behavior**
I would expect the JSON created with 4.0.8 to be de-serialized successfully with 5.0.3

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 11 x64
Platform: .NET 6

**Comment by gofal** [comment]
I see, the InlineBinary seems to make the difference.
I found this: https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.7.html

So would you also agree, that the format from the database, where the InlineBinary is represented as a single string, is standard conformant and the parser now has a bug?

**Comment by jussimattila** [comment]
Thanks for that link! Yes, I interpret the spec like you do. Based on the text, the tag should contain a single string, not an array. 

If this is fixed, I think the parser should tolerate data generated by 5.0.x, which outputs an array. Or what do you think?

**Comment by akojo** [comment]
I just ran into the same issue trying to read DICOM JSON generated by dcmtk. comp.protocols.dicom has discussion about InlineBinary which confirms that plain string is the correct interpretation https://groups.google.com/g/comp.protocols.dicom/c/8UtEzW5hlp0/m/eAc3OGKUAAAJ

Is there anything happening with this or should I take a stab at it?

**Comment by mrbean-bremen** [comment]
> Is there anything happening with this or should I take a stab at it?

Looks like nobody is on this yet - I would say, go ahead!
