### ISSUE TITLE
The uncompress for jepg2000 error on windows

### ISSUE THREAD

**Issue by 1009058470** [fo-dicom/fo-dicom#1496]
**Describe the bug**
when i try to decopresss a jepg2000 dcm using ``` tmpDicomFile.Clone(DicomTransferSyntax.ExplicitVRLittleEndian);```
it show the error like this 
```
Unable to load DLL 'Dicom.Native-win64.dll' or one of its dependencies:  (0x8007007E)
   at FellowOakDicom.Native.Codec.DicomJpeg2000NativeCodec.Memset_Windows64(Void* ptr, Int32 value, UInt32 num)
   at FellowOakDicom.Native.Codec.DicomJpeg2000NativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomFile file)
   at FellowOakDicom.Imaging.Codec.DicomCodecExtensions.Clone(DicomFile file, DicomTransferSyntax syntax, DicomCodecParams parameters)
   at iMedPACSStreaming.Program.Main(String[] args) in E:\w\00000\AllServer\ConsoleApp1\Program.cs:line 36
```

**Environment**
Fellow Oak DICOM version: (5.0.3)
OS: (Windows 10 x64)
Platform: (NET 5)

**Comment by gofal** [comment]
It's just as the error message tells you. Make sure, the files "Dicom.Native-win64.dll" (and "Dicom.Native-winx86.dll") are located in your application directory.
This should be done automatically by visual studio if you compile explicitly as 64bit application. If you compile "anycpu", then maybe your build envioronment did not copy those file to output directory.

**Comment by 1009058470** [comment]
thanks when i move that fill in my app and it can be ok
