### ISSUE TITLE
Error opening DICOM file "FellowOakDicom.DicomFileException: 'Not a valid DICOM file: DICOM File [DICOM3]'"

### ISSUE THREAD

**Issue by bmurf17** [fo-dicom/fo-dicom#1516]
### Expected behavior
I am trying to load a dicom file from azure blob storage, and then open it so I can convert the dicom file to a png to use in our front end. I don't know if the problem is my DICOM file or the way I am loading it from blob storage. I will include the zipped dicom file since it is just dummy data anyway. 

var dicomFile = DicomFile.Open(stream);  succeeds (raw data is a Stream)

### Actual behavior

> FellowOakDicom.DicomFileException: Not a valid DICOM file: DICOM File [DICOM3]

Stack Trace

>   Error uploading files:  FellowOakDicom.DicomFileException: Not a valid DICOM file: DICOM File [DICOM3]
>    ---> FellowOakDicom.DicomFileException: Not a valid DICOM file: DICOM File [DICOM3]
>      at FellowOakDicom.DicomFile.HandleOpenError(DicomFile dicomFile, DicomReaderResult result)
>      at FellowOakDicom.DicomFile.Open(Stream stream, Encoding fallbackEncoding, Func`2 stop, FileReadOption readOption, Int32 largeObjectSize)
>      --- End of inner exception stack trace ---
>      at FellowOakDicom.DicomFile.Open(Stream stream, Encoding fallbackEncoding, Func`2 stop, FileReadOption readOption, Int32 largeObjectSize)
>      at FellowOakDicom.DicomFile.Open(Stream stream, FileReadOption readOption, Int32 largeObjectSize)
>      at Zomedica.Functions.Dicom.DicomProcessor.UploadThumbnail(Stream stream, String folderName, String fileName, BlobContainerClient processedContainer)
>      at Zomedica.Functions.Dicom.DicomProcessor.UploadFiles(Stream zipFile, String folderName)

### Steps to reproduce the behavior
You will need to set up an azure storage account and container

`
        [FunctionName("dicom-processor")]
        public async Task RunAsync([EventGridTrigger] EventGridEvent eventGridEvent, ILogger log)
        {

            //this just grabs the blob reference ex series_1.1.11.1.1111.1.1.1.111111111111111.11111111.111111.1_1111_1111111111_1111-11-11T111114.zip
            var blobName = ExtractZipArchiveFileName(eventGridEvent.Subject);

            if (!blobName.StartsWith("series_"))
            {
                return;
            }

            try
            {
                var storageAccount = CloudStorageAccount.Parse(Environment.GetEnvironmentVariable("StorageAccountName"));
                var blobClient = storageAccount.CreateCloudBlobClient();
                var container = blobClient.GetContainerReference(Environment.GetEnvironmentVariable("BlobContainerIotStorage"));

                var blob = container.GetBlockBlobReference(blobName);
                Stream stream = await blob.OpenReadAsync();

                UploadFiles(stream, Path.GetFileNameWithoutExtension(blobName));
            }
            catch (Exception ex)
            {
            }
        }

        private void UploadFiles(Stream zipFile, string folderName)
        {
            Stopwatch stopWatch = new Stopwatch();

            try
            {
                BlobServiceClient blobServiceClient = new BlobServiceClient("connection string");
                BlobContainerClient processedContainer = blobServiceClient.GetBlobContainerClient("container name");

                using ZipArchive archive = new ZipArchive(zipFile, ZipArchiveMode.Read);

                stopWatch.Start();
                foreach (ZipArchiveEntry entry in archive.Entries)
                {
                    using var stream = entry.Open();

                    if (entry.Name.Contains(".dcm"))
                    {
                        using (var ms = new MemoryStream())
                        {
                            stream.CopyTo(ms);
                            UploadThumbnail(ms, folderName, entry.FullName, processedContainer);
                        }
                    }

                    Response<BlobContentInfo> res = processedContainer.UploadBlob($"{folderName}/{entry.FullName}", stream);

                    if (res.GetRawResponse().IsError)
                    {
                        throw new Exception(res.GetRawResponse().ReasonPhrase);
                    }
                }
            }
            catch (Exception e)
            {
                return;
            }

            stopWatch.Stop();
        }

        private void UploadThumbnail(Stream stream, string folderName, string fileName, BlobContainerClient processedContainer)
        {
            new DicomSetupBuilder()
                 .RegisterServices(s => s
                     .AddFellowOakDicom()
                     .AddTranscoderManager<NativeTranscoderManager>()
                     .AddImageManager<ImageSharpImageManager>())
             .Build();

            var dicomFile = DicomFile.Open(stream);
            var dImage = new DicomImage(dicomFile.Dataset);
            using var img = dImage.RenderImage();
            using var sharpImage = img.AsSharpImage();

            using var ms = new MemoryStream();
            sharpImage.Save(ms, new SixLabors.ImageSharp.Formats.Png.PngEncoder());

            Response<BlobContentInfo> res = processedContainer.UploadBlob($"{folderName}/{fileName}", stream);
        }

        private string ExtractZipArchiveFileName(string blobUrl)
        {
            var substring = "blobs/";
            var index = blobUrl.IndexOf(substring);
            return blobUrl[(index + substring.Length)..];
        }
`

I attached the zip file that would be existing out in blob storage
[series_1.1.11.1.1111.1.1.1.111111111111111.11111111.111111.1_1111_1111111111_1111-11-11T111114.zip](https://github.com/fo-dicom/fo-dicom/files/10709472/series_1.1.11.1.1111.1.1.1.111111111111111.11111111.111111.1_1111_1111111111_1111-11-11T111114.zip)

example body to send 

>   {
    "topic": "/subscriptions/{subscription-id}/resourceGroups/Storage/providers/Microsoft.Storage/storageAccounts/devzomiotstorage1",
    "subject": "/blobServices/default/containers/dicom-files-raw/blobs/series_1.1.11.1.1111.1.1.1.111111111111111.11111111.111111.1_1111_1111111111_1111-11-11T111114.zip",
    "eventType": "Microsoft.Storage.BlobCreated",
    "eventTime": "2017-06-26T18:41:00.9584103Z",
    "id": "831e1650-001e-001b-66ab-eeb76e069631",
    "data": {
      "api": "PutBlockList",
      "clientRequestId": "6d79dbfb-0e37-4fc4-981f-442c9ca65760",
      "requestId": "831e1650-001e-001b-66ab-eeb76e000000",
      "eTag": "0x8D4BCC2E4835CD0",
      "contentType": "application/octet-stream",
      "contentLength": 524288,
      "blobType": "BlockBlob",
      "url": "https://devzomiotstorage1.blob.core.windows.net/dicom-files-raw/series_1_1234_0002458499_2022-12-15T16.22.41.zip",
      "sequencer": "00000000000004420000000000028963",
      "storageDiagnostics": {
        "batchId": "b68529f3-68cd-4744-baa4-3c0498ec19f0"
      }
    },
    "dataVersion": "",
    "metadataVersion": "1"
  }

example end point to hit http://localhost:7071/runtime/webhooks/EventGrid?functionName=dicom-processor

### fo-dicom version and OS/platform
fo-dicom 5.03
Windows 10 Enterprise Version 21h2

**Comment by bmurf17** [comment]
I was loading from cosmos incorrectly and my dicom file was actually fine. This is a classic example of I go through the effort to open an issue and all that jazz just to figure it out like an hour later. If it is helpful for people I can show what I did to fix this up.
