### ISSUE TITLE
Logging through NLogManager after Fo-DICOM 5.1.0 throws error about not finding NameFormatToPositionalFormat

### ISSUE THREAD

**Issue by JonMitri** [fo-dicom/fo-dicom#1605]
**Describe the bug**
Logging through the NLogManager in Fo-DICOM 5.1.1 throws an exception about not finding FellowOakDicom.Log.Logger.NameFormatToPositionalFormat

Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (Method not found: 'System.String FellowOakDicom.Log.Logger.NameFormatToPositionalFormat(System.String)'.)
 ---> System.MissingMethodException: Method not found: 'System.String FellowOakDicom.Log.Logger.NameFormatToPositionalFormat(System.String)'.
   at FellowOakDicom.Log.NLogManager.NLogger.Log(LogLevel level, String msg, Object[] args)
   at FellowOakDicom.Log.Logger.Error(String msg, Object[] args)
   at FellowOakDicom.Log.FellowOakDicomLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, Exception exception, String message, Object[] args)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at ConsoleApp.Program.Main(String[] args) in ...\Program.cs:line 23
   at ConsoleApp.Program.<Main>(String[] args)

**To Reproduce**
1. Setup Fo-DICOM with the NLog Manager.
2. Perform some action that would log like storing a file through the DicomClient.

**Expected behavior**
NLogManager can still be used while people switch to Microsoft.Extensions.Logging

**Screenshots or test DICOM files**
N/A

**Environment**
Fellow Oak DICOM version: 5.1.1
OS: Any
Platform: Any

A little more details:
NameFormatToPositionalFormat was removed in the pull request #1331, but its still referenced in [Logging/FO-DICOM.NLog/NLogManager.cs
](https://github.com/fo-dicom/fo-dicom/blob/master/Logging/FO-DICOM.NLog/NLogManager.cs)

**Comment by amoerie** [comment]
Hi @JonMitri 

This has been an oversight. The NameToPositionalFormat should have been embedded in the package itself, and not in the base class which is now removed. 
I will apologize for not documenting this anywhere. I did not foresee the package breaking this way.

That being said, we will no longer be publishing these log library specific packages, so I only see these two solutions:

1) Use Microsoft.Extensions.Logging and configure it to use NLog underneath. If you're on .NET Core, it's quite likely you're already using this, and in that case Fellow Oak DICOM will work out of the box.

2) Remove the dependency on fo-dicom.NLog and embed the implementation as source code in your application. Then you can also copy the required NameFormatToPositionalFormat function. We have dropped support for this NLog manager, so this means you will have to maintain it yourself, until you move to Microsoft.Extensions.Logging.

**Comment by JonMitri** [comment]
Thank you for your time and help @amoerie .  I'm able to proceed with the suggestion 2 for now and will make the switch to Microsoft.Extensions.Logging long-term as recommended.

**Comment by amoerie** [comment]
You're welcome, and thank you for reaching out and possibly helping others in the process with this issue. Best of luck!
