### ISSUE TITLE
C-Echo SCU/SCP Not working

### ISSUE THREAD

**Issue by vjbollavarapu** [fo-dicom/fo-dicom#1633]
Hi.. I am new to fo-dicom. anyone's guidance on this is really appreciated 

Following the code of C-Echo SCU/SCP is giving error after running on net 6

using FellowOakDicom.Network;
using FellowOakDicom.Network.Client;

public class Program
{
    public static async Task Main(string[] args)
    {
        var client = DicomClientFactory.Create("127.0.0.1", 1002, false, "SCU", "ANY-SCP");
        client.NegotiateAsyncOps();

        client.NegotiateUserIdentity(new DicomUserIdentityNegotiation {
            UserIdentityType = DicomUserIdentityType.Jwt,
            PositiveResponseRequested = true,
            PrimaryField = "JWT_TOKEN"
        });

        for(int i = 0; i < 10; i++)
        {
            await client.AddRequestAsync(new DicomCEchoRequest());
        }

        await client.SendAsync();
    }
}

Unhandled exception. System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it.)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at FellowOakDicom.Network.DesktopNetworkStream..ctor(NetworkStreamCreationOptions options)
   at FellowOakDicom.Network.DesktopNetworkManager.CreateNetworkStreamImpl(NetworkStreamCreationOptions options)
   at FellowOakDicom.Network.NetworkManager.FellowOakDicom.Network.INetworkManager.CreateNetworkStream(NetworkStreamCreationOptions options)
   at FellowOakDicom.Network.Client.Advanced.Connection.DefaultAdvancedDicomClientConnectionFactory.<>c__DisplayClass5_0.<OpenConnectionAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at FellowOakDicom.Network.Client.Advanced.Connection.DefaultAdvancedDicomClientConnectionFactory.OpenConnectionAsync(AdvancedDicomClientConnectionRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at Program.Main(String[] args) in Program.cs:line 22
   at Program.<Main>(String[] args)

Could you please help me??

**Comment by mrbean-bremen** [comment]
This looks like a configuration problem. Are you sure that your SCP is running at your local machine at the correct port and the AE Title "ANY-SCP", and that it accepts ECHO requests rom anyone?

**Comment by vjbollavarapu** [comment]
Hi, The SCP "ANY-SCP" is running.. But I found out that the IP address was showing when I print on console "0.0.0.0". May be this is the reason. Can you guide me how to set the IP address for SCP?? 

I am using below code

using FellowOakDicom.Network;
using FellowOakDicom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;

namespace Vcs.Dicom.CStoreSCP
{
    internal class MainClass : DicomService, IDicomServiceProvider, IDicomCStoreProvider, IDicomCEchoProvider
    {
        private readonly string _storagePath = "";
        private static readonly DicomTransferSyntax[] _acceptedTransferSyntaxes = new DicomTransferSyntax[]
        {
               DicomTransferSyntax.ExplicitVRLittleEndian,
               DicomTransferSyntax.ExplicitVRBigEndian,
               DicomTransferSyntax.ImplicitVRLittleEndian
        };

        private static readonly DicomTransferSyntax[] _acceptedImageTransferSyntaxes = new DicomTransferSyntax[]
        {
               // Lossless
               DicomTransferSyntax.JPEGLSLossless,
               DicomTransferSyntax.JPEG2000Lossless,
               DicomTransferSyntax.JPEGProcess14SV1,
               DicomTransferSyntax.JPEGProcess14,
               DicomTransferSyntax.RLELossless,
               // Lossy
               DicomTransferSyntax.JPEGLSNearLossless,
               DicomTransferSyntax.JPEG2000Lossy,
               DicomTransferSyntax.JPEGProcess1,
               DicomTransferSyntax.JPEGProcess2_4,
               // Uncompressed
               DicomTransferSyntax.ExplicitVRLittleEndian,
               DicomTransferSyntax.ExplicitVRBigEndian,
               DicomTransferSyntax.ImplicitVRLittleEndian
        };


        public MainClass(INetworkStream stream, Encoding fallbackEncoding, ILogger log, DicomServiceDependencies dependencies)
            : base(stream, fallbackEncoding, log, dependencies)
        {
        }


        public Task OnReceiveAssociationRequestAsync(DicomAssociation association)
        {
            if (association.CalledAE != "ANY-SCP")
            {
                return SendAssociationRejectAsync(
                    DicomRejectResult.Permanent,
                    DicomRejectSource.ServiceUser,
                    DicomRejectReason.CalledAENotRecognized);
            }

            foreach (var pc in association.PresentationContexts)
            {
                if (pc.AbstractSyntax == DicomUID.Verification)
                {
                    pc.AcceptTransferSyntaxes(_acceptedTransferSyntaxes);
                }
                else if (pc.AbstractSyntax.StorageCategory != DicomStorageCategory.None)
                {
                    pc.AcceptTransferSyntaxes(_acceptedImageTransferSyntaxes);
                }
            }

            return SendAssociationAcceptAsync(association);
        }


        public Task OnReceiveAssociationReleaseRequestAsync()
        {
            return SendAssociationReleaseResponseAsync();
        }


        public void OnReceiveAbort(DicomAbortSource source, DicomAbortReason reason)
        {
            /* nothing to do here */
        }


        public void OnConnectionClosed(Exception exception)
        {
            /* nothing to do here */
        }


        public async Task<DicomCStoreResponse> OnCStoreRequestAsync(DicomCStoreRequest request)
        {
            var studyUid = request.Dataset.GetSingleValue<string>(DicomTag.StudyInstanceUID).Trim();
            var instUid = request.SOPInstanceUID.UID;

            var path = Path.GetFullPath(_storagePath);
            path = Path.Combine(path, studyUid);

            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            path = Path.Combine(path, instUid) + ".dcm";

            await request.File.SaveAsync(path);

            return new DicomCStoreResponse(request, DicomStatus.Success);
        }


        public Task OnCStoreRequestExceptionAsync(string tempFileName, Exception e)
        {
            // let library handle logging and error response
            return Task.CompletedTask;
        }


        public Task<DicomCEchoResponse> OnCEchoRequestAsync(DicomCEchoRequest request)
        {
            return Task.FromResult(new DicomCEchoResponse(request, DicomStatus.Success));
        }

    }
}

-------------------

using FellowOakDicom;
using FellowOakDicom.Network;
using System.Net.Sockets;
using System.Text;
using Vcs.Dicom.CStoreSCP;

// start DICOM server on port from command line argument or 11112
var port = 1002;
Console.WriteLine($"Starting C-Store SCP server on port {port}");

using (var server = DicomServerFactory.Create<MainClass>(port))
{
    // end process
    Console.WriteLine(server.IPAddress + " Is Listening?? : " + server.IsListening);
    Console.WriteLine("Press <return> to end...");
    Console.ReadLine();
}

**Comment by vjbollavarapu** [comment]
Thank you very much for responding to me.

**Comment by vjbollavarapu** [comment]
I have figured it out to set the IP address all is well except the below error. Please check for me. TQ..

FellowOakDicom.Network.ConnectionClosedPrematurelyException: The connection closed prematurely
   at FellowOakDicom.Network.Client.Advanced.Connection.ConnectionClosedEvent.ThrowException()
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+MoveNext()
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at Program.Main(String[] args) in Vijay.Practice.Lessons\Vijay.Practice.SendDicom\Program.cs:line 12

**Comment by gofal** [comment]
your client has the UserIdentityNegotation of type JWT configured and you set the property PositiveResponseRequested  set to 'true'. so the client expecs an explicit positive response from the server. but your server code does not handle the UserIdneityNegotionation.

I wonder, if you can activiate the logging in your client and find some log-output like"Successful user identity negotiation with type JWT was required but server response was null"

**Comment by vjbollavarapu** [comment]
I am really sorry for the late reply. As I did not see the response, I gave up on this. If I can get it done it will be great. I will check and reply as soon as possible. Thank you.

**Comment by gofal** [comment]
closing this now due to inactivity. If you continue on this story, then please reopen the issue and provide actual informations.
