### ISSUE TITLE
DllNotFoundException Dicom.Native fo-dicom 5.1.1 fo-dicom.Codecs 5.10.6

### ISSUE THREAD

**Issue by sylvainb31** [fo-dicom/fo-dicom#1826]
**Describe the bug**
```
System.DllNotFoundException: Unable to load shared library 'Dicom.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDicom.Native: cannot open shared object file: No such file or directory
   at FellowOakDicom.Imaging.NativeCodec.DicomJpeg2000NativeCodec.Opj_create_compress(OPJ_CODEC_FORMAT format)
   at FellowOakDicom.Imaging.NativeCodec.DicomJpeg2000NativeCodec.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Encode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomFile file)
```

**To Reproduce**
Application NET 5.0
Nuget packages :
fo-dicom 5.1.1
fo-dicom.Codecs 5.10.6

Added the following line at the start of my Startup.cs :

```
new DicomSetupBuilder()
  .RegisterServices(s => s.AddFellowOakDicom().AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>())
  .SkipValidation()
  .Build();
```

Trying to change the transfer syntax of a dicom file by using DicomFile.Clone() method.

It works on windows, but doesn't work in a linux docker container.

**Expected behavior**
To work in my linux docker container.

**Screenshots or test DICOM files**

Dlls in my container :
![image](https://github.com/user-attachments/assets/88f7b838-4ebb-4371-852c-373d9a334a84)

GLIBC library runtime version 2.27:
![image](https://github.com/user-attachments/assets/9d3ed06e-1d15-4542-ada1-361a3c06fa5f)

GLIBCXX version 3.4 :
![image](https://github.com/user-attachments/assets/a860cb32-d209-402f-910a-b46ce4677d8f)

**Environment**
Application NET 5.0
Nuget packages :
fo-dicom 5.1.1
fo-dicom.Codecs 5.10.6

Do you have any idea of why it isn't working ?

Thanks for the help :)

**Comment by jaime-olivares** [comment]
Looking at the section "Dlls in my container"...

It is weird that you are including Efferent.Native which belongs to version 4, and you are missing the entire `runtimes` folder structure, that contains the native (C++) codecs.

**Comment by jaime-olivares** [comment]
I suggest to close this question. There are not other similar claims from other users.

**Comment by gofal** [comment]
closing this issue due to inactivity. If there is still a problem with latest versions, then please feel free to reopen this issue and provide actual informations.
