### ISSUE TITLE
C-Echo request exception with printer in 5.0.3 version

### ISSUE THREAD

**Issue by HanaSongem** [fo-dicom/fo-dicom#1831]
**Describe the bug**
C-Echo request exception, 
An error occurred while sending DICOM requests: FellowOakDicom.Network.DicomAssociationAbortedException: Association Abort [source: ServiceUser; reason: NotSpecified]

**Code**
```
IDicomClient client1 = DicomClientFactory.Create("***", ***, false, "MYAE", "DV6850");
client1.AdditionalPresentationContexts.Add(DicomPresentationContext.GetScpRolePresentationContext(DicomUID.Verification));
client1.AdditionalPresentationContexts.Add(DicomPresentationContext.GetScpRolePresentationContext(DicomUID.BasicGrayscalePrintManagementMeta));
client1.AdditionalPresentationContexts.Add(DicomPresentationContext.GetScpRolePresentationContext(DicomUID.BasicColorPrintManagementMeta));

var request = new DicomCEchoRequest();

await client1.AddRequestAsync(request);
await client1.SendAsync();

```

**To Reproduce**
```
func: MoveNext Msg: case PRINT
[DEBUG] [IDLE] --> [CONNECTING]
***
[DEBUG] Sending association request from MYAE to DV6850
[INFO] DV6850 -> Association request:
Calling AE Title:       MYAE
Called AE Title:        DV6850
Remote host:            
Remote port:            0
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  4
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [Proposed]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] DV6850 <- Association accept:
Calling AE Title:       MYAE
Called AE Title:        DV6850
Remote host:            
Remote port:            0
Implementation Class:   Unknown [1.2.840.113564.3.3.2]
Implementation Version: DV685010v1.05
Maximum PDU Length:     131072
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  4
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [RejectUser]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [RejectAbstractSyntaxNotSupported]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[DEBUG] Association request from MYAE to DV6850 has been accepted
[DEBUG] [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
[DEBUG] Queueing 1 requests
[DEBUG] C-Echo request [1] is being enqueued for sending
[INFO] DV6850 -> C-Echo request [1]
[INFO] DV6850 <- Abort: ServiceUser - NotSpecified
[INFO] Tried to close connection but queues are not empty, PDUs: 0, messages: 0, pending requests: 1
[DEBUG] Request [1]: Aborted
[DEBUG] C-Echo request [1]: Association was aborted
[ERROR] An error occurred while sending DICOM requests: FellowOakDicom.Network.DicomAssociationAbortedException: Association Abort [source: ServiceUser; reason: NotSpecified]
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+MoveNext()
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
[DEBUG] [SENDING REQUESTS] --> [ABORTING ASSOCIATION]
[INFO] DV6850 -> Abort [source: ServiceUser; reason: NotSpecified]
[DEBUG] Read 0 bytes from network stream while reading PDU header, connection will be marked as closed
[DEBUG] Connection closed
[INFO] Connection closed
[DEBUG] Waiting for association from MYAE to DV6850 @<no remote host>:0 to be released
[DEBUG] Association from MYAE to DV6850 @<no remote host>:0 has been aborted
[DEBUG] [ABORTING ASSOCIATION] --> [IDLE]

2024-07-25 09:36:49,162 >>[18] ERROR file: func: MoveNext Msg: Failed to check sopclassuid with ex:FellowOakDicom.Network.DicomAssociationAbortedException: Association Abort [source: ServiceUser; reason: NotSpecified]
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+MoveNext()
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
```

**Expected behavior**
C-Echo request is sucessfully completed

**Environment**
Fellow Oak DICOM version: 5.0.3 (5.1.2 has same problem)
OS: Windows 10 x64/ Debian GNU/Linux 11
Platform: net6.0

If my description is not clear enough or there are any misunderstandings, please let me know, and I will supplement or correct it as soon as possible. 
Thank you so much for your support.

**Comment by HanaSongem** [comment]
Role Selection: SCU-role: no, SCP-role: yes
                Item Type: SCP/SCU Role Selection (0x54)
                Item Length: 21
                SOP Class UID Length: 17
                SOP Class UID: Verification SOP Class (1.2.840.10008.1.1)
                SCU-role: 0x00
                SCP-role: 0x01
            Role Selection: SCU-role: no, SCP-role: yes
                Item Type: SCP/SCU Role Selection (0x54)
                Item Length: 25
                SOP Class UID Length: 21
                SOP Class UID: Basic Grayscale Print Management Meta SOP Class (1.2.840.10008.5.1.1.9)
                SCU-role: 0x00
                SCP-role: 0x01
            Role Selection: SCU-role: no, SCP-role: yes
                Item Type: SCP/SCU Role Selection (0x54)
                Item Length: 26
                SOP Class UID Length: 22
                SOP Class UID: Basic Color Print Management Meta SOP Class (1.2.840.10008.5.1.1.18)
                SCU-role: 0x00
                SCP-role: 0x01
