### ISSUE TITLE
How to correctly implement Presentation Contexts Negotiation

### ISSUE THREAD

**Issue by HanaSongem** [fo-dicom/fo-dicom#1832]
**Environment**
Fellow Oak DICOM version: 5.1.2
OS: Windows 10 x64
Platform: .net 6.0

**Describe the question**
First of all: thank you very much for your work on fo-dicom. It has been a great pleasure using your library so far.

we are trying to start a Presentation Contexts Negotiation with a printer entity with the follow code, but it does not work properly,

```
IDicomClient client1 = DicomClientFactory.Create("***", ***, false, "MYAE", "DV6850");
client1.AdditionalPresentationContexts.Add(DicomPresentationContext.GetScpRolePresentationContext(DicomUID.Verification));
client1.AdditionalPresentationContexts.Add(DicomPresentationContext.GetScpRolePresentationContext(DicomUID.BasicGrayscalePrintManagementMeta));
client1.AdditionalPresentationContexts.Add(DicomPresentationContext.GetScpRolePresentationContext(DicomUID.BasicColorPrintManagementMeta));

var request = new DicomCEchoRequest();

await client1.AddRequestAsync(request);
await client1.SendAsync();
```
it will throw a exception through method SendAsync()

```
func: MoveNext Msg: case PRINT
[DEBUG] [IDLE] --> [CONNECTING]
***
[DEBUG] Sending association request from MYAE to DV6850
[INFO] DV6850 -> Association request:
Calling AE Title:       MYAE
Called AE Title:        DV6850
Remote host:            
Remote port:            0
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  4
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [Proposed]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] DV6850 <- Association accept:
Calling AE Title:       MYAE
Called AE Title:        DV6850
Remote host:            
Remote port:            0
Implementation Class:   Unknown [1.2.840.113564.3.3.2]
Implementation Version: DV685010v1.05
Maximum PDU Length:     131072
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  4
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [RejectUser]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [RejectAbstractSyntaxNotSupported]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[DEBUG] Association request from MYAE to DV6850 has been accepted
[DEBUG] [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
[DEBUG] Queueing 1 requests
[DEBUG] C-Echo request [1] is being enqueued for sending
[INFO] DV6850 -> C-Echo request [1]
[INFO] DV6850 <- Abort: ServiceUser - NotSpecified
[INFO] Tried to close connection but queues are not empty, PDUs: 0, messages: 0, pending requests: 1
[DEBUG] Request [1]: Aborted
[DEBUG] C-Echo request [1]: Association was aborted
[ERROR] An error occurred while sending DICOM requests: FellowOakDicom.Network.DicomAssociationAbortedException: Association Abort [source: ServiceUser; reason: NotSpecified]
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+MoveNext()
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
[DEBUG] [SENDING REQUESTS] --> [ABORTING ASSOCIATION]
[INFO] DV6850 -> Abort [source: ServiceUser; reason: NotSpecified]
[DEBUG] Read 0 bytes from network stream while reading PDU header, connection will be marked as closed
[DEBUG] Connection closed
[INFO] Connection closed
[DEBUG] Waiting for association from MYAE to DV6850 @<no remote host>:0 to be released
[DEBUG] Association from MYAE to DV6850 @<no remote host>:0 has been aborted
[DEBUG] [ABORTING ASSOCIATION] --> [IDLE]

2024-07-25 09:36:49,162 >>[18] ERROR file: func: MoveNext Msg: Failed to check sopclassuid with ex:FellowOakDicom.Network.DicomAssociationAbortedException: Association Abort [source: ServiceUser; reason: NotSpecified]
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+MoveNext()
   at FellowOakDicom.Network.Client.Advanced.Association.AdvancedDicomClientAssociation.SendRequestAsync(DicomRequest dicomRequest, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendRequestAsync(IAdvancedDicomClientAssociation association, DicomRequest request, CancellationToken cancellationToken)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
```

When I use the following code, it works properly
```
IDicomClient client1 = DicomClientFactory.Create("*", *, false, "*", "DV6850");

var pc = new DicomPresentationContext(0, DicomUID.Verification);
pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
client1.AdditionalPresentationContexts.Add(pc);
pc = new DicomPresentationContext(0, DicomUID.BasicGrayscalePrintManagementMeta);
pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
client1.AdditionalPresentationContexts.Add(pc);
pc = new DicomPresentationContext(0, DicomUID.BasicColorPrintManagementMeta);
pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
client1.AdditionalPresentationContexts.Add(pc);

await client1.AddRequestAsync(request);
await client1.SendAsync();
```
I used Wireshark tool to capture TCP package and compared the contents of the requests. I found that these contents were added to the failed requests

```
             Role Selection: SCU-role: no, SCP-role: yes
                Item Type: SCP/SCU Role Selection (0x54)
                Item Length: 21
                SOP Class UID Length: 17
                SOP Class UID: Verification SOP Class (1.2.840.10008.1.1)
                SCU-role: 0x00
                SCP-role: 0x01
            Role Selection: SCU-role: no, SCP-role: yes
                Item Type: SCP/SCU Role Selection (0x54)
                Item Length: 25
                SOP Class UID Length: 21
                SOP Class UID: Basic Grayscale Print Management Meta SOP Class (1.2.840.10008.5.1.1.9)
                SCU-role: 0x00
                SCP-role: 0x01
            Role Selection: SCU-role: no, SCP-role: yes
                Item Type: SCP/SCU Role Selection (0x54)
                Item Length: 26
                SOP Class UID Length: 22
                SOP Class UID: Basic Color Print Management Meta SOP Class (1.2.840.10008.5.1.1.18)
                SCU-role: 0x00
                SCP-role: 0x01
```

I have searched for many examples of fo dicam online, but I am still confused about how to correctly use c-echo to implement Presentation Contexts Negotiation. Could you please help me provide an example.

Thank you so much for your support...

**Comment by gofal** [comment]
The difference of the two methods is, that DicomPresentationContext.GetScpRolePresentationContext also adds the optional SCP/SCU Role Selection negotiation.
It seems as if the printer, that you send the requests, seems to have troubles with that. I wonder if you could send the echo request to some other Dicom-Nodes, like a Archive or some other workstations. Of course, they all will reject the printmanagement-contexts, but the requests should work without exception.
Can you very that?

https://dicom.nema.org/medical/dicom/current/output/chtml/part07/sect_D.3.3.4.html

**Comment by HanaSongem** [comment]
I sent a c-echo request to an SCP service implemented by fo-dicom, It works fine.
```
[DEBUG] [IDLE] --> [CONNECTING]
[DEBUG] [CONNECTING] --> [REQUESTING ASSOCIATION]
[DEBUG] Sending association request from MYAE to CALLEDAE
[INFO] CALLEDAE -> Association request:
Calling AE Title:       MYAE
Called AE Title:        CALLEDAE
Remote host:            
Remote port:            0
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  3
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] CALLEDAE <- Association accept:
Calling AE Title:       MYAE
Called AE Title:        CALLEDAE
Remote host:            
Remote port:            0
Implementation Class:   Unknown [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 5.0.3
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  3
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [RejectAbstractSyntaxNotSupported]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [RejectAbstractSyntaxNotSupported]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[DEBUG] Association request from MYAE to CALLEDAE has been accepted
[DEBUG] [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
[DEBUG] Queueing 1 requests
[DEBUG] C-Echo request [4] is being enqueued for sending
[INFO] CALLEDAE -> C-Echo request [4]
[INFO] CALLEDAE <- C-Echo response [4]: Success
[DEBUG] Request [4]: Success
[DEBUG] C-Echo request [4]: C-Echo response [4]: Success
[DEBUG] C-Echo request [4] has completed
[DEBUG] Lingering on open association for 50ms
[DEBUG] [SENDING REQUESTS] --> [LINGERING ASSOCIATION]
[DEBUG] [LINGERING ASSOCIATION] --> [RELEASING ASSOCIATION]
[INFO] CALLEDAE -> Association release request
[DEBUG] Waiting for association from MYAE to CALLEDAE @<no remote host>:0 to be released
[INFO] CALLEDAE <- Association release response
[INFO] Connection closed
[DEBUG] Association from MYAE to CALLEDAE @<no remote host>:0 released
[DEBUG] Connection closed
[DEBUG] Association from MYAE to CALLEDAE @<no remote host>:0 has been released
[DEBUG] [RELEASING ASSOCIATION] --> [IDLE]
```

Sorry for the misunderstanding, i tried sending a c-echo request with the following code to the printer DV6850, adding the roles setting in the construcrtor method. It didn't throw an excpetion. So I'm guessing that's probably not what caused the exception.
```
var pc = new DicomPresentationContext(0, DicomUID.BasicGrayscalePrintManagementMeta, false, true);
pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
client1.AdditionalPresentationContexts.Add(pc);
pc = new DicomPresentationContext(0, DicomUID.BasicColorPrintManagementMeta, false, true);
pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
client1.AdditionalPresentationContexts.Add(pc);
var request = new DicomCEchoRequest();
await client1.AddRequestAsync(request);
await client1.SendAsync();
```

Thank you very much for your reply, I found out that this may be caused by improper use of the problem, when I try to use c-echo to establish a connection,  PresentationContext "Verification" will be present in the Presentation Context by default, at this time, if you add the "Verification" will throw the above exception.(as in the following code)

```
var pc = new DicomPresentationContext(0, DicomUID.Verification);
pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
client1.AdditionalPresentationContexts.Add(pc);
```

**Comment by gofal** [comment]
Thanks for the update.
The exception is, because the association is aborted and the network stream is not available any more where the DicomClient wanted to read/write on the stream.
So the Printer aborts the connection, if the Context "Verification" is contained twice with Role Negotiation.
Other SCPs do not behave this way. So the issue is only with the printer? Did I sum this up correctly?

**Comment by HanaSongem** [comment]
Yes, Other SCP do not behave this way, only with the printer.
Thanks for your response. Appreciate it.
