### ISSUE TITLE
Getting `DicomAssociationRequestTimedOutException` when sending query requests

### ISSUE THREAD

**Issue by Grenkin1988** [fo-dicom/fo-dicom#1860]
**Describe the bug**
Getting `DicomAssociationRequestTimedOutException` even though I've attached to the event: `client.AssociationRequestTimedOut`

Exception:
```
FellowOakDicom.Network.DicomAssociationRequestTimedOutException: The association request timed out 3 times, waiting 5000ms each time for the association response
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
   at FellowOakDicom.Network.Client.DicomClient.SendAsync(CancellationToken cancellationToken, DicomClientCancellationMode cancellationMode)
```

**To Reproduce**
I am not 100% sure how to reproduce this, this is not happening on the Conquest PACS test environment, but it is happening from time to time on production with Sectra PACS
I am doing queries to the PACS:
Client is created:
```
let client = DicomClientFactory.Create(
    host,
    configuration.RemoteTCPPort.PortNumber,
    false,
    QueryRetrieve,
    configuration.TargetAETitle)
```

Then when calling:
```
var request = DicomCFindRequest(DicomQueryRetrieveLevel.Study);
request.Dataset.Add(DicomTag.AccessionNumber, an);
request.Dataset.Add(DicomTag.StudyInstanceUID, "");
request.OnResponseReceived += .....

await client.AddRequestAsync(request);
await client.SendAsync(cancelToken.Token);
```

**Expected behavior**
Given that there is such event present on API I would expect it to be called instead of the exception crash

**Environment**
Fellow Oak DICOM version: 5.1.2
OS: Windows Server 2019 Datacenter
Platform: .NET 8

**Comment by gofal** [comment]
the event is fired, but still the SendAsync failes with an exception.
But you will receive the events several times and can add some logging or other UI-updates on status. So this is intended to be informative. It will not replace the exception.

There is some pattern, that when events are fired, then the EventArgs contains a `Handled` property. and in case some eventhandler of the application reacts on the event and sets the `Handled` property to `true`, then the event is not further bubled or the retry-mechanism is canceld or whatever. So you would expect some behavior like that?

You always should wrap `client.SendAsync` in a try-catch-block at a certain level in production, because there can be several exceptions. Not only those that fo-dicom throws, but also some System.Io.Network exceptions or else.

**Comment by gofal** [comment]
The issue seems to be answered, so closing thins. If there is still some issue, then please reopen it and provide actual informations
