### ISSUE TITLE
RenderImage "Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by weiyouren** [fo-dicom/fo-dicom#1865]
**Describe the bug**
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FellowOakDicom.Imaging.LUT.OutputLUT.get_Item(Double value)
   at FellowOakDicom.Imaging.LUT.CompositeLUT.get_Item(Double value)
   at FellowOakDicom.Imaging.LUT.PrecalculatedLUT.Recalculate()
   at FellowOakDicom.Imaging.Render.ImageGraphic.RenderImage(ILUT lut)
   at FellowOakDicom.Imaging.DicomImage.RenderImage(Int32 frame)

**To Reproduce**
```c#
var dicomImage = new DicomImage("D:\\Dicom\\1.2.826.0.1.3680043.2.461.6056843.2072890052\\1.2.840.113619.2.55.3.604688119.978.1359562614.942.5.DCM")
{
    //WindowWidth = detectParams.WindowWidth,
    //WindowCenter = detectParams.WindowCenter
};
await dicomImage.RenderImage().AsSharpImage().SaveAsBmpAsync("test.bmp");
```

**Expected behavior**
render image to bitmap

**Screenshots or test DICOM files**
[1.2.840.113619.2.55.3.604688119.978.1359562614.942.5.dcm.zip](https://github.com/user-attachments/files/17349532/1.2.840.113619.2.55.3.604688119.978.1359562614.942.5.dcm.zip)

**Environment**
Fellow Oak DICOM version: (e.g. 5.1.3)
OS: (e.g. Windows10 x64)
Platform: (e.g. .NET8 Core Web Api)

**Comment by weiyouren** [comment]
I solved it
```c#
builder.Services
    .AddFellowOakDicom()
    .AddImageManager<ImageSharpImageManager>()
    .AddTranscoderManager<NativeTranscoderManager>()
    .AddHostedService<CStoreScpAndCEchoScpHostedService>();
```
