### ISSUE TITLE
Unsupported OS Platform

### ISSUE THREAD

**Issue by VETWorks** [fo-dicom/fo-dicom#1883]
**Describe the bug**
Compiling a project in VS 2022 on Windows ARM64 with the output set to X64 results in an error when running the application on a X64 windows. 

I checked the binary, and it's compiled for X64. The OS running the app is X64. Task manager also shows the process as X64. We're using .NET 9.

I would expect this error when running the application on a Windows ARM64, but not on a Windows X64.

```
System.InvalidOperationException: Unsupported OS Platform
   at FellowOakDicom.Imaging.NativeCodec.Jpeg.JpegCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomJpegParams jpegParams, Int32 frame)
   at FellowOakDicom.Imaging.NativeCodec.DicomJpegNativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.DecodePixelData(DicomDataset dataset, Int32 frame)
   at FellowOakDicom.Imaging.DicomImage.GetFrameData(Int32 frame)
   at FellowOakDicom.Imaging.DicomImage.<GetOrCreateCachedPixelData>b__57_0(Int32 f)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at FellowOakDicom.Imaging.DicomImage.GetOrCreateCachedPixelData(Int32 frame)
   at FellowOakDicom.Imaging.DicomImage.RenderImage(Int32 frame)
```

**To Reproduce**
Compile a simple project that renders an image using the WinFormsImageManager compiled on Windows ARM64 for X64 and run on X64 windows.

**Expected behavior**
No error on Windows X64 machine.

**Environment**
Fellow Oak DICOM version: 5.1.4
OS: Windows 11 ARM64 to compile, Windows Server 2022 Data center to run the app
Platform: .NET 9

**Comment by jaime-olivares** [comment]
This seems to be related to https://github.com/Efferent-Health/fo-dicom.Codecs/issues/83

We are are working on a solution a.s.a.p.

**Comment by jaime-olivares** [comment]
This fixed now and published in nuget: https://www.nuget.org/packages/fo-dicom.Codecs/5.15.3
Please provide feedback in https://github.com/Efferent-Health/fo-dicom.Codecs/issues/83

**Comment by gofal** [comment]
Closing this issue here, as it is handled on Efferent-Health repository.
