### ISSUE TITLE
"Index was outside the bounds of the array" in PrecalculatedLUT indexer

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#219]
Under specific circumstances, I have received the following error message and stack trace:

> Index was outside the bounds of the array.
   at Dicom.Imaging.LUT.PrecalculatedLUT.get_Item(Int32 value) in \DICOM\Imaging\LUT\PrecalculatedLUT.cs:line 70
   at Dicom.Imaging.Render.GrayscalePixelDataU32.<>c__DisplayClass16_0.<Render>b__1(Int32 y) in \DICOM\Imaging\Render\PixelData.cs:line 1060
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()

The problem appears to be caused by the following code:

    int p = value + _offset;
    if (p < 0) return _table[0];
    if (p >= _table.Length) p = _table[_table.Length - 1];
    return _table[p];

when `p` exceeds the `_table.Length`. 

As far as I can tell, the re-assignment in the third line is incorrect; correct behavior would be to *return* the right-hand-side value instead:

    if (p >= _table.Length) return _table[_table.Length - 1];

Please comment if you disagree with my conclusion.

**Comment by IanYates** [comment]
@anders9ustafsson - I think you're absolutely right
