### ISSUE TITLE
DicomCFindRequest

### ISSUE THREAD

**Issue by veriturus** [fo-dicom/fo-dicom#228]
Hi to all, and thanks for creating FO-Dicom. I'm new at programming and trying my hardest to learn, so I apologize in advance if I say something which might is naive.

I just wanted to ask if anyone else is having problems with the DicomCFindRequest (either Patient, Study or Series) with certain dicomservers or pacs, like ONIS25 or Sectra? As in it just does nothing from what I can see, no patient list is returned. The same code works fine with a different dicomserver called Mirage.

Am I missing something? 

p.s. is this the wrong place for this question?

**Comment by anders9ustafsson** [comment]
@veriturus It's perfectly OK to ask questions here. For the time being I'll label it as such.

Could you please show some of your code? Also, which *fo-dicom* version are you using?

**Comment by veriturus** [comment]
@anders9ustafsson Thank you for your time and understanding.  It is basically the example from the README.TXT and the version is FO_DICOM_2.0.2. I also warn you it not pretty.

        private void showList()
        {
            Dispatcher.BeginInvoke((Action)(() =>
            {
                if (counter < 999)
                {
                    for (int i = 0; i < counter; i++)
                    {
                        listView.Items.Add(new PatientList
                        {
                            Name = patientList[i, 0],
                            PatientId = patientList[i, 1],
                            StudyIUid = patientList[i, 2],
                            SeriesIUid = patientList[i, 3],
                            sopInstUid = patientList[i, 4],
                            sopClassUID = patientList[i, 5]
                        });
                    }
                }
            }));
        }

        public void FindResponseCallback(DicomCFindRequest request, DicomCFindResponse response)
        {
            string name = response.Dataset.Get<string>(DicomTag.PatientName);
            string patientId = response.Dataset.Get<string>(DicomTag.PatientID);
            string studyIUid = response.Dataset.Get<string>(DicomTag.StudyInstanceUID);
            string seriesIUid = response.Dataset.Get<string>(DicomTag.SeriesInstanceUID);
            string sopClassUid = response.Dataset.Get<string>(DicomTag.SOPClassUID);
            string sopInst = response.Dataset.Get<string>(DicomTag.SOPInstanceUID);

            if (counter < 1000)
            {
                patientList[counter, 0] = name;
                patientList[counter, 1] = patientId;
                patientList[counter, 2] = studyIUid;
                patientList[counter, 3] = seriesIUid;
                patientList[counter, 4] = sopInst;
                patientList[counter, 5] = sopClassUid;
            }

            showList();

            counter++;
        }

        public void FindOnDicomServer()
        {
            searchName = "*" + textBoxName.Text + "*";
            searchID = "*" + textBoxID.Text + "*";

            counter = 0;

            listView.Items.Clear();
            Array.Clear(patientList, 0, patientList.Length);

            var cfind = DicomCFindRequest.CreatePatientQuery(searchID, searchName);
            cfind.OnResponseReceived = FindResponseCallback;
            
            var client = new DicomClient();
            client.AddRequest(cfind);
            client.Send(ipAddress, portAE, false, callingAE, calledAE);
           
        }//Find Patient Level

**Comment by anders9ustafsson** [comment]
@veriturus Have you verified that the problem is in the request/response and not in the WPF control update? Have you checked whether `FindResponseCallback` is invoked?

**Comment by veriturus** [comment]
@anders9ustafsson FindResponseCallback is never invoked, I have tried Patient, Study and Series level. 

It could also just be that the Onis server is not replying or wants extra information, I contacted them a week ago but they have still not replied.

I managed to get a list from the Mirage Server but only when I use the Study level.

I don't want to waste your time, I will try to use other pacs or dicom servers and see if I can get lists from them. Do you have any servers to suggest that you work with, that are not too expensive?

**Comment by anders9ustafsson** [comment]
@veriturus Can you access the log from the Onis server so that you at least know if the *CFindRequest* reaches the server?

In my line of work I normally only test network services via DCMTK software. But maybe someone else can recommend a suitable and inexpensive PACS server?

**Comment by veriturus** [comment]
@anders9ustafsson 

The ONIS logs are as follows:

//_______CFIND REQUEST!
13:00:15 02/19/2016 [DICOMSRV] ( <--> ONIS25)  | Received Connection Request on Dicom Port...
13:00:15 02/19/2016 [DICOMSRV] ( <--> ONIS25)  | Thread created (0x5BD54D8  threads: 1)
13:00:15 02/19/2016 [DICOMSRV] ( <--> ONIS25)  | 	Connection Accepted (0x5BD5520 / 192.168.1.85:57178)
13:00:15 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | Associate Request received from FODICOM (192.168.1.85:57178)
13:00:15 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | Associate Response has been sent (accepted)
13:00:15 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | OnClose socket message received
13:00:15 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | Thread Deleted (0x5BD54D8  threads: 0)

//_______CECHO REQUEST!
13:00:18 02/19/2016 [DICOMSRV] ( <--> ONIS25)  | Received Connection Request on Dicom Port...
13:00:18 02/19/2016 [DICOMSRV] ( <--> ONIS25)  | Thread created (0x5BD54D8  threads: 1)
13:00:18 02/19/2016 [DICOMSRV] ( <--> ONIS25)  | 	Connection Accepted (0x5BD5520 / 192.168.1.85:57180)
13:00:18 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | Associate Request received from FODICOM (192.168.1.85:57180)
13:00:18 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | Associate Response has been sent (accepted)
13:00:18 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | CECHO Request received
13:00:19 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | Received release request
13:00:19 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | Release Response has been sent
13:00:19 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | OnClose socket message received
13:00:19 02/19/2016 [DICOMSRV] (FODICOM <--> ONIS25)  | Thread Deleted (0x5BD54D8  threads: 0)

**Comment by anders9ustafsson** [comment]
@veriturus Maybe you could switch on extended logging to see what is being sent back and forth over the network by setting the `Options` property of the `DicomClient`?

    client.Options = new DicomServiceOptions { LogDataPDUs = true, LogDimseDatasets = true };

**Comment by veriturus** [comment]
@anders9ustafsson I have not implemented logging yet in the code. I did try all possible PDU configurations on ONIS 8k, 16k, 32k and 64k. But still nothing.

I will try to get the logging to work with what i have so far and as soon as that works I'll will post to here.

Thank you for you time and interest.

**Comment by IanYates** [comment]
It's definitely worth turning on logging and even digging a little under the covers to inspect the network using WireShark if necessary just to make sure you have some packets going back and forth as expected.

**Comment by anders9ustafsson** [comment]
Closing this issue now since there has been no activity for a while. @veriturus Please feel free to re-open it if you have additional concerns.

**Comment by veriturus** [comment]
I'm still trying to get the logs to work, this might take some time as I'm not a code guru like you guys. Thanks for the understanding. **@FODICOM_GURUS**

**Comment by jongo** [comment]
Ok, here are the logs when fo-dicom 1.1.0 sends C-Find to Onis25:

![image](https://cloud.githubusercontent.com/assets/1005993/16042133/8e4943e6-3239-11e6-8308-7cc00cb78603.png)

**Comment by jongo** [comment]
Same if you try to search Onis25 via Clear Canvas:

nexpected exception when processing PDU.
ClearCanvas.Dicom.Network.DicomNetworkException: Pdu[type=A-Associate-AC (02), length=150] (offset=150, bytes=1, field="Item-Type") Requested offset out of range!
   at ClearCanvas.Dicom.Network.RawPDU.CheckOffset(Int32 bytes, String name)
   at ClearCanvas.Dicom.Network.AAssociateAC.Read(RawPDU raw)
   at ClearCanvas.Dicom.Network.NetworkBase.ProcessRawPDU(RawPDU raw)
2016-06-14 14:19:04,576 [DicomClient: 127.0.0.1:1112 Read [5]] ERROR - Unexpected error processing PDU.  Aborting Association from ClearCanvas to ONIS26
2016-06-14 14:19:04,576 [11] ERROR - Exception thrown

Failed to query server 'ONIS'.
System.ServiceModel.FaultException`1[ClearCanvas.Dicom.ServiceModel.Query.QueryFailedFault]: An unexpected network error has occurred. (Fault Detail is equal to ClearCanvas.Dicom.ServiceModel.Query.QueryFailedFault).
2016-06-14 14:19:04,576 [DicomClient: 127.0.0.1:1112 Read [5]] WARN  - Unexpected network error: Pdu[type=A-Associate-AC (02), length=150] (offset=150, bytes=1, field="Item-Type") Requested offset out of range!

**Comment by anders9ustafsson** [comment]
But do I understand correctly, @jongo , that this appears to be a general issue for the *Onis 25* server? Then I strongly recommend that you direct the question to the *Onis* manufacturer, or post a question on their community forum if there is one.

**Comment by jongo** [comment]
@anders9ustafsson Yep, it is up to Onis25, because it works in Onis26.

**Comment by anders9ustafsson** [comment]
@jongo OK, thanks for the clarification. I'll leave this issue closed then.
