### ISSUE TITLE
Print SCP sample reports exception due to missing ActionTypeID in N-ACTION response

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#298]
### Expected behavior
When executing *Print SCU* sample while *Print SCP* sample is running, print should perform without error messages.

### Actual behavior
Following exception is displayed in the *Print SCP* log:
> Exception processing P-Data-TF PDU: Dicom.DicomDataException: Tag: (0000,1008) not found in dataset
   at Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) in \DICOM\DicomDataset.cs:line 659
   at Dicom.Network.DicomNActionResponse.ToString() in \DICOM\Network\DicomNActionResponse.cs:line 49
   at Dicom.Network.DicomMessage.ToString(Boolean printDatasets) in \DICOM\Network\DicomMessage.cs:line 125
   at Dicom.Network.DicomService.SendNextMessage() in \DICOM\Network\DicomService.cs:line 908
   at Dicom.Network.DicomService.SendMessage(DicomMessage message) in \DICOM\Network\DicomService.cs:line 796
   at Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) in \DICOM\Network\DicomService.cs:line 738
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__49.MoveNext() in \DICOM\Network\DicomService.cs:line 570

### Steps to reproduce the behavior
Start *Print SCP*, then run *Print SCU*.

### fo-dicom version and OS/platform
3.0.0-beta1, Windows Desktop

### Troubleshooting
Tag (0000,1008) is *Action Type ID*. In `DicomNActionResponse.ToString` this tag is requested without existing in the command dataset. Due to stricter `Dataset.Get` rules a tag not found exception is now reported, cf. #231.

**Comment by anders9ustafsson** [comment]
Issue directly applies to the following types, that all override `ToString`:

    DicomNActionRequest
    DicomNActionResponse
    DicomNEventReportRequest
    DicomNEventReportResponse
