### ISSUE TITLE
Exception if Storage Commitment N-Event Report response does not contain EventID tag (0000,1002)

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#323]
### Expected behavior
Should process the N-Event Report Response successfully.

### Actual behavior
From Logging
06-22-2016 09:19:41 Error: Exception processing P-Data-TF PDU: Dicom.DicomDataException: Tag: (0000,1002) not found in dataset
   at Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) in D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom]\DICOM\DicomDataset.cs:line 704
   at Dicom.Network.DicomNEventReportResponse.ToString() in D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom]\DICOM\Network\DicomNEventReportResponse.cs:line 93
   at Dicom.Network.DicomMessage.ToString(Boolean printDatasets) in D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom]\DICOM\Network\DicomMessage.cs:line 151
   at Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) in D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom]\DICOM\Network\DicomService.cs:line 685
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__52.MoveNext() in D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom]\DICOM\Network\DicomService.cs:line 605

### Steps to reproduce the behavior
Use DicomClient to send a Storage Commitment N-Event Report to a SCP.

### fo-dicom version and OS/platform
Tested in Beta 3 too.  In Beta 3 had to add Additional Presentation Context in DicomCliient to bypass issue 316.
Code Snippet
            DicomClient client = new DicomClient();
            var pc = DicomPresentationContext.GetScpRolePresentationContext(DicomUID.StorageCommitmentPushModelSOPClass);
            client.AdditionalPresentationContexts.Add(pc);          
            client.AddRequest(report);
            client.Send(destination.IP, (int)destination.Port, false, destination.AE, calledAE);

**Comment by BobSter3000** [comment]
Potential fix in DicomNEventEeportResponse.CS
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendFormat("{0} [{1}]: {2}", ToString(Type), RequestMessageID, Status.Description);
            **if (Command.Contains(DicomTag.EventTypeID))
                sb.AppendFormat("\n\t\tEvent Type:	{0:x4}", EventTypeID);**
            if (Status.State != DicomState.Pending && Status.State != DicomState.Success)
            {
                if (!String.IsNullOrEmpty(Status.ErrorComment)) sb.AppendFormat("\n\t\tError:		{0}", Status.ErrorComment);
            }
            return sb.ToString();
        }

**Comment by anders9ustafsson** [comment]
I assume that an analogous exception is thrown when `ActionTypeID` is missing in `DicomNActionResponse`.

**Question:** Should missing `EventTypeID`/`ActionTypeID` simply be ignored like in the proposed fix above, or should an exception be thrown already when trying to initialize the response from an arbitrary command dataset?

**Comment by BobSter3000** [comment]
I looked at the standard and the EventTypeID/ActionTypeID does not appear to be required in the N-Event Report response.  I personally think it should be ignored and let the consumer code handle the missing tags if required.
