### ISSUE TITLE
Modality Worklist Error -  Abort [source: ServiceUser; reason: NotSpecified]

### ISSUE THREAD

**Issue by hashitha** [fo-dicom/fo-dicom#341]
### Expected behavior

Modality Worklist Request 
### Actual behavior

Throws NullReference exception 
Only happens with manufacturer Shimadzu - screening modality

![capture](https://cloud.githubusercontent.com/assets/10569142/17723591/ca9f5086-646d-11e6-971d-89a2ebf84eac.PNG)
### Steps to reproduce the behavior

Send a modality request to fo-dicom
### fo-dicom version and OS/platform

3.0 beta 4

**Comment by hashitha** [comment]
A similar error happens with Worklist  on Toshiba Aplio 500. 

But on this one calling AE Title = *
See attached.

![capture2](https://cloud.githubusercontent.com/assets/10569142/17723637/2f589500-646e-11e6-9e04-d30d802fe5cf.PNG)


Any idea how I can debug this.

Its working fine on all the other modalities

**Comment by hashitha** [comment]
Toshiba technicians came and they played with the modality settings and it worked. They said they didn't do anything it just started working.

**Comment by Ravenheart** [comment]
I have the same problem with an HP AW workstation on a CFIND.

```
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" <- Association request:
"Calling AE Title:       AW02
Called AE Title:        JOYSTICK
Remote host:            10.0.5.35
Remote port:            42912
Implementation Class:   Implementation Class UID [1.2.840.113619.6.264]
Implementation Version: AW4_5_03_024_CTT
Maximum PDU Length:     64234
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Study Root Query/Retrieve Information Model - FIND
       Transfer Syntax:  Explicit VR Little Endian
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
       Transfer Syntax:  Explicit VR Big Endian (Retired)"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" -> Association accept:
"Calling AE Title:       AW02
Called AE Title:        JOYSTICK
Remote host:            10.0.5.35
Remote port:            42912
Implementation Class:   Implementation Class UID [1.2.840.113619.6.264]
Implementation Version: AW4_5_03_024_CTT
Maximum PDU Length:     64234
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Study Root Query/Retrieve Information Model - FIND
       Transfer Syntax:  Explicit VR Little Endian"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" <- "C-Find request [12]"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.371 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.387 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.402 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Pending"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> "C-Find response [12]: Success"
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> Abort [source: ServiceUser; reason: NotSpecified]
2016-09-07 15:45:18.418 +03:00 [Error] Exception processing P-Data-TF PDU: DicomDataException { Message: "Tag: (0000,0110) not found in dataset", Data: [], InnerException: null, TargetSite: T Get[T](Dicom.DicomTag, Int32, Boolean, T), StackTrace: "   at Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue)
   at Dicom.Network.DicomMessage.ToString()
   at Dicom.Network.DicomMessage.ToString(Boolean printDatasets)
   at Dicom.Network.DicomService.PerformDimse(DicomMessage dimse)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__52.MoveNext()", HelpLink: null, Source: "Dicom.Core", HResult: -2146233088 }
2016-09-07 15:45:18.636 +03:00 [Information] Connection closed
```

**Comment by anders9ustafsson** [comment]
@hashitha If I understand correctly, this issue has been resolved for you?
@Ravenheart Is this still an issue for you?

**Comment by hashitha** [comment]
@anders9ustafsson yes I got the Toshiba ones working after the service technicians played with the settings (no idea what they changed). Still having issues with Shimadzu. This machine is at one of my client's sites, so I can't debug directly, and the logs are not helpful in this case.

**Comment by aerik** [comment]
@hashitha looking at your logs, it looks like your code is sending an abort after the success.  Do you want to post your worklist handling code?

**Comment by hashitha** [comment]
@aerik I don't think I am sending an abort. The code works with all other modalities.

```


public IEnumerable<DicomCFindResponse> OnCFindRequest(DicomCFindRequest request)
        {
            List<DicomCFindResponse> responses = new List<DicomCFindResponse>();

            // Logger.Info(request.Dataset.WriteToString());     //this log function crashes on OPG studies!


            //Study Query FIND
            if (request.SOPClassUID == DicomUID.StudyRootQueryRetrieveInformationModelFIND)
            {
                //Logger.Error(request.Dataset.WriteToString());     //this log function crashes on OPG studies!
                string level = request.Dataset.Get<string>(DicomTag.QueryRetrieveLevel);

                DicomQueryRetrieveLevel requestLevel = DicomQueryRetrieveLevel.Study;

                if (level.Contains("IMAGE"))
                {
                    requestLevel = DicomQueryRetrieveLevel.Image;
                }

                if (level.Contains("STUDY"))
                {
                    requestLevel = DicomQueryRetrieveLevel.Study;
                }

                if (level.Contains("SERIES"))
                {
                    requestLevel = DicomQueryRetrieveLevel.Series;
                }

                //if requesting studies
                if (requestLevel == DicomQueryRetrieveLevel.Study)
                {

                    //Search params
                    //Patient Name
                    //Patient ID
                    //Accession
                    //StudyDescription
                    //Referring Physician
                    //Institution
                    //Bithdate
                    //Modality
                    //StudyDate
                    //Logger.Error("requestLevel STUDY");
                    //Logger.Error(request.Dataset.WriteToString());

                    List<DicomDataset> studyDataset = getStudies(request.Dataset);
                    Logger.Info("studies in dataset {0}", studyDataset.Count);


                    foreach (DicomDataset result in studyDataset)
                    {
                        result.Add(DicomTag.QueryRetrieveLevel, level); //need to be same as incomming request
                        result.Add(DicomTag.RetrieveAETitle, LocalAETitle);
                        DicomCFindResponse response = new DicomCFindResponse(request, DicomStatus.Pending);
                        response.Dataset = result;
                        responses.Add(response);
                    }
                }

                //if requesting series study
                if (requestLevel == DicomQueryRetrieveLevel.Series)
                {

                    List<DicomDataset> seriesDataset = getSeriesForStudyInstanceUID(request.Dataset.Get<string>(DicomTag.StudyInstanceUID));
                    Logger.Info("series in dataset {0}", seriesDataset.Count);
                    foreach (DicomDataset result in seriesDataset)
                    {
                        result.Add(DicomTag.QueryRetrieveLevel, level); //need to be same as incomming request
                        result.Add(DicomTag.RetrieveAETitle, LocalAETitle);
                        DicomCFindResponse response = new DicomCFindResponse(request, DicomStatus.Pending);
                        response.Dataset = result;

                        responses.Add(response);
                    }
                }

                if (requestLevel == DicomQueryRetrieveLevel.Image)
                {
                    // Logger.Error("Image level");
                    // Logger.Error(request.Dataset.WriteToString());

                    string studyInstanceUid = request.Dataset.Get<string>(DicomTag.StudyInstanceUID);
                    string seriesInstanceUid = request.Dataset.Get<string>(DicomTag.SeriesInstanceUID);

                    List<DicomDataset> imagesDataset = getImagesForSeriesInstanceUID(studyInstanceUid, seriesInstanceUid);
                    Logger.Info("Images in dataset {0}", imagesDataset.Count);
                    foreach (DicomDataset result in imagesDataset)
                    {
                        result.Add(DicomTag.QueryRetrieveLevel, level); //need to be same as incomming request
                        result.Add(DicomTag.RetrieveAETitle, LocalAETitle);
                        DicomCFindResponse response = new DicomCFindResponse(request, DicomStatus.Pending);
                        response.Dataset = result;

                        responses.Add(response);
                    }
                }

                responses.Add(new DicomCFindResponse(request, DicomStatus.Success));
            }
```

**Comment by aerik** [comment]
I had an issue with a similar symptom, my SCP was mysteriously sending an Abort.  For me, it turned out the problem was it couldn't parse an enum due to a string having a null character at the end.  See #359.

FYI, my exception bubbled up and manifested as this error:
"Exception processing P-Data-TF PDU: System.ArgumentException: Requested value 'STUDY ' was not found"

However, your issue may be something else.  I suspect you will have to step through the debugger...

**Comment by anders9ustafsson** [comment]
@hashitha @Ravenheart @aerik Do I understand correctly, that this issue boils down to *fo-dicom* STORE SCP sending invalid ABORTs?

**Comment by aerik** [comment]
I don't think we can generalize it to that.  It appears that an exception inside of processing pdus results in an abort being sent, like in Ravenheart's example:

```
2016-09-07 15:45:18.418 +03:00 [Information] "AW02" -> Abort [source: ServiceUser; reason: NotSpecified]
2016-09-07 15:45:18.418 +03:00 [Error] Exception processing P-Data-TF PDU: DicomDataException { Message: "Tag: (0000,0110) not found in dataset", Data: [], InnerException: null, TargetSite: T Get[T](Dicom.DicomTag, Int32, Boolean, T), StackTrace: "   at Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue)
   at Dicom.Network.DicomMessage.ToString()
   at Dicom.Network.DicomMessage.ToString(Boolean printDatasets)
   at Dicom.Network.DicomService.PerformDimse(DicomMessage dimse)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__52.MoveNext()", HelpLink: null, Source: "Dicom.Core", HResult: -2146233088 }
2016-09-07 15:45:18.636 +03:00 [Information] Connection closed
```

**Comment by anders9ustafsson** [comment]
Thanks @aerik. OK, that's right, this is a specific issue. Will try to look more closely into the code to identify the root cause. @Ravenheart, which *fo-dicom* version were you using when you got the September 7 exception?

**Comment by anders9ustafsson** [comment]
Mental note: tag (0000,0110) corresponds to *Message ID*.
