### ISSUE TITLE
DicomServer stops listening to messages after exception occurs

### ISSUE THREAD

**Issue by jmiglietta-inc** [fo-dicom/fo-dicom#403]
Using Dicom.Core 2.0.2

We have a windows service that runs DicomServer in a worker thead.  Normally it runs fine, however, recently we have been finding that although the service is running it is not listening for connections.  This happens after a SocketException occurs.  The code for the service is show below:

 ```               
Task.Run(() => {
  try
  {
    using (DicomServer<CStoreSCP> server = new DicomServer<CStoreSCP>(port: _serverInfo.LocalIpPort, logger: _logger))
    {
      _logger.Info("PacsListener::Pacs Service listening on port: {0}", _serverInfo.LocalIpPort);
      _isListening = true;

      // Wait for a kill signal
      _taskEvent.Wait();

      // Stop listening
      server.Stop();
      _isListening = false;
    }
  }
  catch(Exception e)
  {
    ExitWithError = true;
    _logger.Error("PacsListener::Fatal error reported:{0}", e.Message);
  }
  finally
  {
    _logger.Info("PacsListener::Pacs Service stopped");
    _isListening = false;
    _exitEvent.Set();
  }
});
```

The exception appears in our log file as:

>Exception listening for clients, System.AggregateException: One or more errors occurred. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Dicom.Network.DesktopNetworkListener.<AcceptNetworkStreamAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dicom.Network.DicomServer`1.<ListenAsync>d__26.MoveNext()
---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndAccept(Byte[]& buffer, Int32& bytesTransferred, IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndAccept(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpListener.EndAcceptTcpClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

The problem is, once this exception occurs the server no longer listens for connections and there is no way of knowing that the DicomServer has stopped as the exception is trapped in a code location not accessible to me.  I realize that I can perhaps add a watchdog to attempt connecting to the service but that's not an optimal solution.  Is there something I'm missing?

**Comment by anders9ustafsson** [comment]
@jmiglietta-inc In 3.0, we have added several utilities to help out with these issues. There is a boolean property `IsListening`, and there is an `Exception` property providing any exception occurring during the listening process. There is also a handle to the listener task, `BackgroundWorker`.

So my recommendation is that you move over to 3.0 (currently at Beta 4) and try it out to see if it meets your requirements. If not, please feel free to post suggestions on how it can be further improved.
