### ISSUE TITLE
DicomClient proposes wrong presentation context in .NET core with codec that does not support 16 bit encoding

### ISSUE THREAD

**Issue by npnelson** [fo-dicom/fo-dicom#538]
### Expected behavior
When sending two files via '''DicomClient.Send()''' one with 8 bit encoding, one with 16 bit encoding in .NET Core, it should propose two Presentation Contexts, each with supported .NET codecs

### Actual behavior

It will only propose one and then an InvalidOperationException will be thrown with "JPEG codec does not support Bits allocated == 16"

### Steps to reproduce the behavior

See unit test added as part of https://github.com/fo-dicom/fo-dicom/issues/525

### fo-dicom version and OS/platform

3.1.0-alpha .NET core (Windows and Ubuntu)

### Discussion

Unfortunately, the codec and association code is mostly foreign to me. I'm afraid I don't have any ideas as to the best way to fix it right now

**Comment by anders9ustafsson** [comment]
@npnelson I have made a recent fix to #525 (PR #584) that should prevent the `Send(Async)` call from hanging, so I hope that at least that part is covered now.

When it comes to the issue with missing codecs, I am still not sure where the problem lies. JPEG Baseline (Process 1) is intended for lossy 8 bit JPEGs only. 16 bit JPEGs are only possible with JPEG Process 14 and 14 SV1, if I am not mistaken. The 16 bit image in your #525 unit test, which transfer syntax does it currently use?

My suspicion is that *fo-dicom* is trying to transcode it into a supported transfer syntax, which will fail on .NET Core since it doesn't have encoding of JPEG Process 14 (SV1) images. It would be great if you could provide the entire stack trace for the `InvalidOperationException`.

**Comment by npnelson** [comment]
When I look at  AssociationErrorFile1.dcm DICOM Dump shows it as 8 bit  and the transfer syntax as JPEG Baseline (Process 1)
AssociationErrorFile2.dcm is 16bit with a transfer syntax of Implicit VR Little Endian.

I bet you are right, AssociationErrorFile2.dcm is probably really a JPEG Process 14 or 14 SV1 that I was somehow able to receive via .NET Core, but then can't send via .NET Core. Sorry I am not being much help, the codecs are still mysterious to me.

It might well be that there is no action to take.

Here is the stacktrace (from commit cb3dfa97) I have updated my fork to cb3dfa97 and used the same test https://github.com/npnelson/fo-dicom/blob/development/Tests/Desktop/Network/DicomClientTest.cs#L44-L65

JPEG codec does not support Bits Allocated == 16

 at Dicom.Imaging.Codec.DicomJpegCodecImpl.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomJpegParams parameters) in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Imaging\Codec\DicomJpegCodecImpl.cs:line 149
   at Dicom.Imaging.Codec.DicomJpegProcess1Codec.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters) in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Imaging\Codec\DicomJpegProcess1Codec.Mono.cs:line 15
   at Dicom.Imaging.Codec.DicomTranscoder.Encode(DicomDataset oldDataset, DicomTransferSyntax inSyntax, IDicomCodec codec, DicomCodecParams parameters) in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Imaging\Codec\DicomTranscoder.cs:line 249
   at Dicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset) in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Imaging\Codec\DicomTranscoder.cs:line 147
   at Dicom.Imaging.Codec.DicomCodecExtensions.Clone(DicomDataset dataset, DicomTransferSyntax syntax, DicomCodecParams parameters) in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Imaging\Codec\DicomCodecExtensions.cs:line 42
   at Dicom.Network.DicomService.<DoSendMessageAsync>d__64.MoveNext() in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Network\DicomService.cs:line 1051
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.DicomService.<SendNextMessageAsync>d__63.MoveNext() in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Network\DicomService.cs:line 924
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__60.MoveNext() in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Network\DicomService.cs:line 757
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__59.MoveNext() in C:\Users\Nicho\Source\Repos\fo-dicom6\DICOM\Network\DicomService.cs:line 476

**Comment by anders9ustafsson** [comment]
@npnelson I have now dug deeper into this particular issue. As long as the negotiated accepted transfer syntax is equal to the transfer syntax of the individual DICOM file/dataset, no local transcoding will be applied and the dataset will be forward to the server without changes.

If the accepted transfer syntax is different from the dataset's transfer syntax, and there is no codec available either to decode the dataset or to encode it to the accepted transfer syntax, the pixel data will be removed from the dataset before sending to ensure that transcoding is always possible.

I am also considering to implement a flag in the service options to allow for *fo-dicom* to ignore the accepted transfer syntax if transcoding is not possible. That would in that case mean that the dataset is sent as-is to the service provider, hoping for the dataset to be accepted even though the transfer syntax is not the negotiated one.
