### ISSUE TITLE
The directory name is invalid.

### ISSUE THREAD

**Issue by Ravenheart** [fo-dicom/fo-dicom#548]
### Exception
2017-06-16 11:08:58.011 +03:00 [Error] Exception processing P-Data-TF PDU: IOException { Message: "The directory name is invalid.
", Data: [], InnerException: null, TargetSite: Void WinIOError(Int32, System.String), StackTrace: "   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Dicom.IO.DesktopPath.GetTempFileName()
   at Dicom.IO.TemporaryFile.Create()
   at Dicom.Network.DicomService.CreateCStoreReceiveStream(DicomFile file)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__58.MoveNext()", HelpLink: null, Source: "mscorlib", HResult: -2147024629 }
2017-06-16 11:08:58.042 +03:00 [Error] I/O exception while reading PDU: IOException { Message: "The directory name is invalid.
", Data: [], InnerException: null, TargetSite: Void WinIOError(Int32, System.String), StackTrace: "   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
   at Dicom.IO.DesktopPath.GetTempFileName()
   at Dicom.IO.TemporaryFile.Create()
   at Dicom.Network.DicomService.CreateCStoreReceiveStream(DicomFile file)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__57.MoveNext()", HelpLink: null, Source: "mscorlib", HResult: -2147024629 }
2017-06-16 11:08:58.089 +03:00 [Information] Connection closed
2017-06-16 11:08:58.089 +03:00 [Error] Error during close attempt: IOException { Message: "The directory name is invalid.
", Data: [], InnerException: null, TargetSite: Void WinIOError(Int32, System.String), StackTrace: "   at Dicom.Network.DicomService.TryCloseConnection(Exception exception, Boolean force)", HelpLink: null, Source: "mscorlib", HResult: -2147024629 }

### fo-dicom version and OS/platform
3.0.2.0, Windows Server 2016 Essentials

I am getting the following error, not sure if its missing permissions or because C: drive has low disk space. Anybody encountered this error before?

**Comment by Ravenheart** [comment]
Upon further research it turns out its a permissions issue, closing the issue.
