### ISSUE TITLE
Is there a paradigm for reading a DICOM folder and creating the DICOMDIR

### ISSUE THREAD

**Issue by KoutsopoulosKostas** [fo-dicom/fo-dicom#551]

**Comment by PantelisGeorgiadis** [comment]
Hello Kostas!
You can use the following snippet:
```
var studyDir = new DirectoryInfo(path);
var dicomDirPath = Path.Combine(path, "DICOMDIR");
var dicomDir = new DicomDirectory();
foreach (var file in studyDir.GetFiles("*.*", SearchOption.AllDirectories))
{
      var dicomFile = DicomFile.Open(file.FullName);
      dicomDir.AddFile(dicomFile, file.Name);
}
dicomDir.Save(dicomDirPath);
```


Regards,
Pantelis

**Comment by KoutsopoulosKostas** [comment]
Panteli Hi 

Thank you for your insight. i tried the sniped and got the following exception. Can you have a look?

BR
Kostas

**System.TypeInitializationException occurred
   HResult=0x80131534
   Message=The type initializer for 'Dicom.DicomEncoding' threw an exception.
   Source=Dicom.Core
   StackTrace:
    at Dicom.DicomMultiStringElement..ctor(DicomTag tag, String[] values)
    at Dicom.DicomUniqueIdentifier..ctor(DicomTag tag, DicomUID[] values)
    at Dicom.DicomDataset.DoAdd[T](DicomVR vr, DicomTag tag, IList`1 values, Boolean allowUpdate)
    at Dicom.DicomDataset.DoAdd[T](DicomTag tag, IList`1 values, Boolean
allowUpdate)
    at
Dicom.DicomFileMetaInformation.set_MediaStorageSOPClassUID(DicomUID
value)
    at Dicom.Media.DicomDirectory..ctor(Boolean explicitVr)
    at GDCMDICOMDIR.Form1.button2_Click(Object sender, EventArgs e) in C:\Users\nikalog\Documents\Visual Studio 2017\Projects\GDCMDICOMDIR\GDCMDICOMDIR\Form1.cs:line 37
    at System.Windows.Forms.Control.OnClick(EventArgs e)
    at System.Windows.Forms.Button.OnClick(EventArgs e)
    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
    at System.Windows.Forms.Control.WndProc(Message& m)
    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
    at System.Windows.Forms.Button.WndProc(Message& m)
    at
System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&
m)
    at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd,
Int32 msg, IntPtr wparam, IntPtr lparam)
    at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG&
msg)
    at
System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr
dwComponentID, Int32 reason, Int32 pvLoopData)
    at
System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32
reason, ApplicationContext context)
    at
System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32
reason, ApplicationContext context)
    at System.Windows.Forms.Application.Run(Form mainForm)
    at GDCMDICOMDIR.Program.Main() in C:\Users\nikalog\Documents\Visual Studio 2017\Projects\GDCMDICOMDIR\GDCMDICOMDIR\Program.cs:line 19

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an 
object.**









![untitled](https://user-images.githubusercontent.com/17967016/27862903-4440a708-6190-11e7-9fdf-ddab26999bb2.png)

**Comment by anders9ustafsson** [comment]
@KoutsopoulosKostas Which *fo-dicom* version are you using? 2.0.x?

**Comment by KoutsopoulosKostas** [comment]
I am using 3.0.2.0


Εστάλη από τη συσκευή μου Samsung

-------- Αρχικό μήνυμα --------
Από: Anders Gustafsson <notifications@github.com> 
Ημερομηνία: 5/7/17  23:36  (GMT+02:00) 
Προς: fo-dicom/fo-dicom <fo-dicom@noreply.github.com> 
Κοιν.: KoutsopoulosKostas <kostas@alphamedrix.com>, Mention <mention@noreply.github.com> 
Θέμα: Re: [fo-dicom/fo-dicom] Is there a paradigm for reading a DICOM
&nbsp; folder and creating the DICOMDIR (#551) 

@KoutsopoulosKostas Which fo-dicom version are you using? 2.0.x?

**Comment by anders9ustafsson** [comment]
@KoutsopoulosKostas Which NuGet package are you using then? If you use the main *fo-dicom* package, be sure to target .NET Framework 4.5.2 or higher. If you are targeting .NET 4.5 or 4.5.1, NuGet will select the PCL version of the *fo-dicom* Core assembly, which does not itself contain an implementation for the default encoding (and could result in the type initialization exception you are facing).

**Comment by anders9ustafsson** [comment]
Alternatively, use the *fo-dicom.Desktop* NuGet package directly. Then the NuGet package will not even install if you are using an earlier .NET Framework version than 4.5.2.

**Comment by anders9ustafsson** [comment]
@KoutsopoulosKostas I assume you have been able to solve the problem by now? If not, please re-open the issue and provide more details about what is not working.

**Comment by IdleLogic** [comment]
I had very similar problems with the TypeInitializationException and all my files coming back as invalid. I recommend making it more obvious that you need to target 4.5.2 and not simply 4.5. I was just about to abandon fo-dicom after a few hours banging my head against the while until I stumbled across this bug report.
