### ISSUE TITLE
CFind response NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by darthunix** [fo-dicom/fo-dicom#574]
### Expected behavior

I am testing CFind response method and return fake data on any findscu query. So on a findscu request like
```bash
findscu -S -k QueryRetrieveLevel=STUDY -k StudyDate=20160805  -k StudyInstanceUID -aec PACS localhost 4242 -v
```

I expect to get a valid result with some random study UID and date 20160805.
On a server side this request is processed by
```c#

        public IEnumerable<DicomCFindResponse> OnCFindRequest(DicomCFindRequest request)
        {
            //TODO: fix error (Object reference not set to an instance of an object)
            var command = new DicomDataset();
            command.Add(DicomTag.AffectedSOPClassUID, DicomUID.StudyRootQueryRetrieveInformationModelFIND)
                .Add(DicomTag.CommandField, (ushort)DicomCommandField.CFindResponse)
                .Add(DicomTag.MessageIDBeingRespondedTo, request.MessageID)
                .Add(DicomTag.CommandDataSetType, (ushort)0x0202)
                .Add(DicomTag.AffectedSOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID())
                .Add(DicomTag.QueryRetrieveLevel, DicomQueryRetrieveLevel.Study)
                .Add(DicomTag.StudyDate, "20160805")
                .Add(DicomTag.StudyInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID());
            var response = new DicomCFindResponse(command);   
            response.Status = DicomStatus.Success;   

            var results = new List<DicomCFindResponse>();      
            results.Add(response);

            return results;
        }
```

### Actual behavior

My server code crashes with an error
```
FINDSCU <- C-Find request [1]
Exception processing P-Data-TF PDU: System.NullReferenceException: Object reference not set to an instance of an object.
   at Dicom.IO.Writer.DicomDatasetExtensions.RemoveGroupLengths(DicomDataset dataset, Boolean firstLevelOnly)
   at Dicom.Network.DicomService.DoSendMessage(DicomMessage msg)
   at Dicom.Network.DicomService.SendNextMessage()
   at Dicom.Network.DicomService.SendMessage(DicomMessage message)
   at Dicom.Network.DicomService.PerformDimse(DicomMessage dimse)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__58.MoveNext()
Connection closed
```

### fo-dicom version and OS/platform
fo-dicom 3.0.2, Ubuntu 17.04

**Comment by anders9ustafsson** [comment]
The C-FIND response is expected to contain a results dataset as well, in addition to the command. The API documentation could be clearer in this respect, will consider to add more details.
