### ISSUE TITLE
MPEG2 CMove

### ISSUE THREAD

**Issue by Ravenheart** [fo-dicom/fo-dicom#579]
For the life of me I cannot get a MPEG2 from the PACS to a client. I keep getting a "No codec registered for tranfer syntax: MPEG2 Main Profile / Main Level" exception.

Test client code:
```
            DicomClient client = new DicomClient();
            DicomCMoveRequest cmove = new DicomCMoveRequest("GINKGO", "2.16.124.113543.6021.1.1.2644569456.4380.1501767084.1");
            cmove.OnResponseReceived = (request, response) =>
                {
                    Console.WriteLine(request.ToString());
                    Console.WriteLine(response.ToString());
                };

            client.OnCStoreRequest = (request) =>
            {
                Console.WriteLine(request.ToString());

                return new DicomCStoreResponse(request, DicomStatus.Success);
            };

            cmove.CreatePresentationContext(DicomTransferSyntax.ImplicitVRLittleEndian);

            client.AddRequest(cmove);
            client.Send("localhost", 4343, false, "GINKGO", "JOYSTICK_SCP");
```

Error:
```
2017-08-04 10:41:11.467 +03:00 [Information] PACS @ 4343
2017-08-04 10:41:11.777 +03:00 [Information] HTTP @ http://*:8042/
2017-08-04 10:41:11.777 +03:00 [Information] Сървърите стартирани!
2017-08-04 10:41:15.721 +03:00 [Information] "GINKGO" <- Association request:
"Calling AE Title:       GINKGO
Called AE Title:        JOYSTICK_SCP
Remote host:            127.0.0.1
Remote port:            2607
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 3.0.2
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Study Root Query/Retrieve Information Model - MOVE
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM"
2017-08-04 10:41:15.943 +03:00 [Information] "GINKGO" -> Association accept:
"Calling AE Title:       GINKGO
Called AE Title:        JOYSTICK_SCP
Remote host:            127.0.0.1
Remote port:            2607
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 3.0.2
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Study Root Query/Retrieve Information Model - MOVE
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM"
2017-08-04 10:41:16.124 +03:00 [Information] "GINKGO" <- "C-Move request [1]"
2017-08-04 10:41:16.292 +03:00 [Information] "GINKGO" -> Association request:
"Calling AE Title:       JOYSTICK_SCP
Called AE Title:        GINKGO
Remote host:            127.0.0.1
Remote port:            11112
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 3.0.2
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Secondary Capture Image Storage
       Transfer Syntax:  MPEG2 Main Profile / Main Level
       Transfer Syntax:  Explicit VR Little Endian
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM"
2017-08-04 10:41:16.330 +03:00 [Information] "GINKGO" <- Association accept:
"Calling AE Title:       JOYSTICK_SCP
Called AE Title:        GINKGO
Remote host:            127.0.0.1
Remote port:            11112
Implementation Class:   Unknown [1.3.6.1.4.1.25403.1.1.1]
Implementation Version: Dicom 0.1
Maximum PDU Length:     116794
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Secondary Capture Image Storage
       Transfer Syntax:  Explicit VR Little Endian"
2017-08-04 10:41:16.345 +03:00 [Debug] Searching "D:\DEV\Joystick.Dicom\Joystick.Dicom.Server.ConsoleApplication\bin\Release"\"Dicom.Native*.dll" for Dicom codecs
2017-08-04 10:41:16.360 +03:00 [Warning] No Dicom codecs were found after searching "D:\DEV\Joystick.Dicom\Joystick.Dicom.Server.ConsoleApplication\bin\Release"\"Dicom.Native*.dll"
2017-08-04 10:41:16.364 +03:00 [Debug] Searching "D:\DEV\Joystick.Dicom\Joystick.Dicom.Server.ConsoleApplication\bin\Release"\"Dicom.Native*.dll" for Dicom codecs
2017-08-04 10:41:16.369 +03:00 [Warning] No Dicom codecs were found after searching "D:\DEV\Joystick.Dicom\Joystick.Dicom.Server.ConsoleApplication\bin\Release"\"Dicom.Native*.dll"
2017-08-04 10:41:16.388 +03:00 [Error] Failed to send due to: DicomCodecException { Message: "No codec registered for tranfer syntax: MPEG2 Main Profile / Main Level", Data: [], InnerException: null, TargetSite: Dicom.Imaging.Codec.IDicomCodec GetCodec(Dicom.DicomTransferSyntax), StackTrace: "   at Dicom.Imaging.Codec.TranscoderManager.GetCodec(DicomTransferSyntax syntax) in C:\fo-dicom\DICOM\Imaging\Codec\TranscoderManager.cs:line 60
   at Dicom.Imaging.Codec.DicomTranscoder.get_InputCodec() in C:\fo-dicom\DICOM\Imaging\Codec\DicomTranscoder.cs:line 53
   at Dicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset) in C:\fo-dicom\DICOM\Imaging\Codec\DicomTranscoder.cs:line 134
   at Dicom.Imaging.Codec.DicomCodecExtensions.Clone(DicomDataset dataset, DicomTransferSyntax syntax, DicomCodecParams parameters) in C:\fo-dicom\DICOM\Imaging\Codec\DicomCodecExtensions.cs:line 42
   at Dicom.Network.DicomService.DoSendMessage(DicomMessage msg) in C:\fo-dicom\DICOM\Network\DicomService.cs:line 992
   at Dicom.Network.DicomService.SendNextMessage() in C:\fo-dicom\DICOM\Network\DicomService.cs:line 866
   at Dicom.Network.DicomService.SendMessage(DicomMessage message) in C:\fo-dicom\DICOM\Network\DicomService.cs:line 828
   at Dicom.Network.DicomService.SendRequest(DicomRequest request) in C:\fo-dicom\DICOM\Network\DicomService.cs:line 175
   at Dicom.Network.DicomClient.<DoSendAsync>d__50.MoveNext() in C:\fo-dicom\DICOM\Network\DicomClient.cs:line 411", HelpLink: null, Source: "Dicom.Core", HResult: -2146233088 }
2017-08-04 10:41:16.401 +03:00 [Error] Exception processing P-Data-TF PDU: DicomCodecException { Message: "No codec registered for tranfer syntax: MPEG2 Main Profile / Main Level", Data: [], InnerException: null, TargetSite: Dicom.Imaging.Codec.IDicomCodec GetCodec(Dicom.DicomTransferSyntax), StackTrace: "   at Dicom.Network.DicomClient.Send(String host, Int32 port, Boolean useTls, String callingAe, String calledAe) in C:\fo-dicom\DICOM\Network\DicomClient.cs:line 206
   at Joystick.Dicom.Server.JoystickSCP.<OnCMoveRequest>d__d.MoveNext() in d:\DEV\Joystick.Dicom\Joystick.Dicom.Server\JoystickSCP.cs:line 306
   at Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) in C:\fo-dicom\DICOM\Network\DicomService.cs:line 772
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__58.MoveNext() in C:\fo-dicom\DICOM\Network\DicomService.cs:line 679", HelpLink: null, Source: "Dicom.Core", HResult: -2146233088 }
2017-08-04 10:41:16.406 +03:00 [Error] Exception processing PDU: DicomCodecException { Message: "No codec registered for tranfer syntax: MPEG2 Main Profile / Main Level", Data: [], InnerException: null, TargetSite: Dicom.Imaging.Codec.IDicomCodec GetCodec(Dicom.DicomTransferSyntax), StackTrace: "   at Dicom.Network.DicomClient.Send(String host, Int32 port, Boolean useTls, String callingAe, String calledAe) in C:\fo-dicom\DICOM\Network\DicomClient.cs:line 206
   at Joystick.Dicom.Server.JoystickSCP.<OnCMoveRequest>d__d.MoveNext() in d:\DEV\Joystick.Dicom\Joystick.Dicom.Server\JoystickSCP.cs:line 306
   at Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) in C:\fo-dicom\DICOM\Network\DicomService.cs:line 772
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__58.MoveNext() in C:\fo-dicom\DICOM\Network\DicomService.cs:line 688
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__57.MoveNext() in C:\fo-dicom\DICOM\Network\DicomService.cs:line 413", HelpLink: null, Source: "Dicom.Core", HResult: -2146233088 }
2017-08-04 10:41:16.414 +03:00 [Information] Connection closed
2017-08-04 10:41:16.416 +03:00 [Error] Error during close attempt: DicomCodecException { Message: "No codec registered for tranfer syntax: MPEG2 Main Profile / Main Level", Data: [], InnerException: null, TargetSite: Dicom.Imaging.Codec.IDicomCodec GetCodec(Dicom.DicomTransferSyntax), StackTrace: "   at Dicom.Network.DicomService.TryCloseConnection(Exception exception, Boolean force) in C:\fo-dicom\DICOM\Network\DicomService.cs:line 1065", HelpLink: null, Source: "Dicom.Core", HResult: -2146233088 }
```

**Comment by Ravenheart** [comment]
Serverside code:
```
        public IEnumerable<DicomCMoveResponse> OnCMoveRequest(DicomCMoveRequest request)
        {
            Utils.LogDataset(request.Dataset, "CMove");
            var dcm = request.Dataset;
            string studyUid = dcm.Get<string>(DicomTag.StudyInstanceUID);
            string distributedFolder = FileDistributor.ComputeStudyPath(studyUid);

            string studyPath = Path.Combine(Settings.Default.StorageFolder, distributedFolder);
            if (!Directory.Exists(studyPath))
            {
                yield return new DicomCMoveResponse(request, DicomStatus.ProcessingFailure);
                yield break;
            }

            if (!JoystickSCP.Modalities.ContainsKey(request.DestinationAE))
            {
                yield return new DicomCMoveResponse(request, DicomStatus.QueryRetrieveMoveDestinationUnknown);
                yield return new DicomCMoveResponse(request, DicomStatus.ProcessingFailure);
                yield break;
            }

            var files = Directory.GetFiles(studyPath, "*.dcm", SearchOption.TopDirectoryOnly);

            DicomClient client = new DicomClient();
            client.NegotiateAsyncOps(files.Length, files.Length);

            for (int i = 0; i < files.Length; i++)
            {
                string file = files[i];
                DicomFile dcmFile = DicomFile.Open(file);
                DicomCStoreRequest cstore = new DicomCStoreRequest(dcmFile);
                client.AddRequest(cstore);
            }
            var modality = JoystickSCP.Modalities[request.DestinationAE];
            client.Send(modality.ModalityHost, modality.ModalityPort, false, Settings.Default.ServerAET, modality.ModalityAET);

            yield return new DicomCMoveResponse(request, DicomStatus.Success);
        }
```

**Comment by anders9ustafsson** [comment]
@Ravenheart Please take a look at #526. Are there any commonalities between this and that issue?

**Comment by Ravenheart** [comment]
I suspect it may be something similar, in my case I can successfully receive the files from a machine, but trying to send them over (even if both SCP and SCU specify MPEG2 transfer syntax) it still searches for MPEG2 codec.

**Comment by anders9ustafsson** [comment]
Classified as duplicate. See [this](https://github.com/fo-dicom/fo-dicom/issues/526#issuecomment-325619340) comment for details; in particular look for the recently added Bugs/GH526 unit test.
