### ISSUE TITLE
Exception processing PDU: System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by PetrM1** [fo-dicom/fo-dicom#647]
I have several installations and I'm receiving various data from various PACS servers and on some of them I see time to time following error

```
Exception processing PDU: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   at Dicom.Network.DicomPresentationContext.AcceptTransferSyntaxes(DicomTransferSyntax[] acceptedTransferSyntaxes, Boolean scpPriority)
   at Dicom.Network.DicomPresentationContext.AcceptTransferSyntaxes(DicomTransferSyntax[] acceptedTransferSyntaxes)
   at PACS_Log_Utils.DicomServerSCP.OnReceiveAssociationRequest(DicomAssociation association)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__57.MoveNext()
```

Please let me know what can I do to bring more info - if needed.

I'm running it on windows using fo-dicom version 3.0.2.1

Thank you
Petr

**Comment by amoerie** [comment]
Closing due to inactivity
