### ISSUE TITLE
dicomClient.sendAsync exception behavior

### ISSUE THREAD

**Issue by buckstephenh** [fo-dicom/fo-dicom#662]
### Expected behavior

If a request in the queue (among potentially hundreds) encounters an exception, we should receive the exception in the DicomCStoreRequest.OnResponseReceived.DicomCStoreResponse or other object associated with the request.    We should also be able to view counts, and examine  and remove the offender in

private readonly ConcurrentQueue<DicomRequest> _requests;

### Actual behavior

Exceptions are returning to the caller of dicomClient.sendAsync with no context and the problem request stays in the queue, and not visible to the caller.

private readonly ConcurrentQueue<DicomRequest> _requests;  is private so we cannot view the remaining requests to locate the problem.  We also cannot remove the offending request.

### Steps to reproduce the behavior

Download ftp://medical.nema.org/MEDICAL/Dicom/DataSets/WG04/compsamples_jpeg.tar and with JPLY/MG1_JPLY or use any other file or condition that causes an exception that can bubble up to sendAsync instead of to OnResponseReceived.

dicomClient.AddRequest<DicomCStoreRequest>
dicomClient.sendAsync

### fo-dicom version and OS/platform

fo-dicom.NetCode 3.1.0-alpha on MacOS 10.13.4 Beta

**Comment by gofal** [comment]
What kind of exception is it that happens? And where does this exception happen? 
If the exception happens in network layer then it is ok that it is thrown in sendAsync, isn't it?

The ability to see the remaining requests and eventually to clear the queue has been asked several times and should be implemented anyway besides exception handling.

**Comment by gofal** [comment]
is the same as issue #661

**Comment by buckstephenh** [comment]
Hi, the example file to reproduce is the same as #661 , but the issues presented may be slightly different.  

Here's the exception I got this time which doesn't appear it is a network layer type of exception.  It's a codec exception. 

2018-03-05 13:21:53.0002 Error Logger.cs.Log:285 fo-dicom: Exception processing PDU:
{@error}
System.Exception: Unsupported JPEG data precision 12
at BitMiracle.LibJpeg.Classic.jpeg_error_mgr.error_exit()
at BitMiracle.LibJpeg.Classic.Internal.jpeg_decomp_master.master_selection()
at BitMiracle.LibJpeg.Classic.jpeg_decompress_struct.jpeg_start_decompress()
at BitMiracle.LibJpeg.Jpeg.Decompress(Stream jpeg, IDecompressDestination destination)
at Dicom.Imaging.Codec.DicomJpegCodecImpl.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomJpegParams parameters)
at Dicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
at Dicom.Network.DicomService.DoSendMessage(DicomMessage msg)
at Dicom.Network.DicomService.SendNextMessage()
at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__58.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__57.MoveNext() 
2018-03-05 13:21:53.0022 Information Logger.cs.Log:285 fo-dicom: Queue(s) not empty, PDUs:
{pduCount}
, messages:
{msgCount}
, pending requests:
{pendingCount}
0|2|1 

Thanks!
Stephen

**Comment by gofal** [comment]
is the same as defect #826 
this exception is caused in a third party library on NetCore platform. Need to find an other library. Please continue observing issue 826.
