### ISSUE TITLE
DicomFileException during C-STORE request resulting in tmp files left in temp folder

### ISSUE THREAD

**Issue by SrividyaTR** [fo-dicom/fo-dicom#711]
### Expected behavior
Cstore request succeeds and temp files are not left in c:\windows\temp folder

### Actual behavior
During cstore request, DicomFileException with below stack trace occurs and consequently the tmp file is left in c:\windows\temp folder resulting the disk getting filled up

Exception during C-STORE request. file: C:\Windows\TEMP\tmpD85C.tmp, Exception: Dicom.DicomFileException: An attempt was made to move the file pointer before the beginning of the file.

---> System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.FileStream.SeekCore(Int64 offset, SeekOrigin origin)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at Dicom.IO.FileByteSource.GetBuffer(UInt32 count)
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source)
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source)
   at Dicom.IO.Reader.DicomReader.Read(IByteSource source, IDicomReaderObserver observer, Func`2 stop)
   at Dicom.IO.Reader.DicomFileReader.DoParse(IByteSource source, IDicomReaderObserver fileMetasetInfoObserver, IDicomReaderObserver datasetObserver, Func`2 stop, DicomTransferSyntax& syntax, DicomFileFormat& fileFormat)
   at Dicom.IO.Reader.DicomFileReader.Parse(IByteSource source, IDicomReaderObserver fileMetasetInfoObserver, IDicomReaderObserver datasetObserver, Func`2 stop)
   at Dicom.IO.Reader.DicomFileReader.Read(IByteSource source, IDicomReaderObserver fileMetaInfo, IDicomReaderObserver dataset, Func`2 stop)
   at Dicom.DicomFile.Open(IFileReference file, Encoding fallbackEncoding)
   --- End of inner exception stack trace ---
   at Dicom.DicomFile.Open(IFileReference file, Encoding fallbackEncoding)
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__58.MoveNext()

### fo-dicom version and OS/platform
fo-dicom version: 3.0.2
OS/platform        : windows and .NET c# application

**Comment by gofal** [comment]
Fo-dicom does not create temp-files, so I try to guess the important "Steps to reproducte the behavior": 
* you create the DICOM files and store them inte temp-folder
* a CStoreRequest with the filesnames from the temp-folder is created
* you then call the DicomClient.Set method.

This is where the DicomClient first opens the files and reads them so that the DicomClient knows the Abstract- and TransferSyntaxes of the files to send.

Are you sure the DICOM files in temp-folder are not corrupt? Change your code, so that instead of sending you just open the files. Does that work? Where do this temp files come from?

**Comment by BobSter3000** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SrividyaTR** [comment]
The above mentioned error is coming in the method OnCStoreRequestException of IDicomCStoreProvider. 

We are not creating any Dicom files in the temp folder. 

Our scenario is as follows:
1. We start a Dicom StoreSCP node
2. Files are sent by a Dicom StoreSCU nodes to our node

What is the tempfile parameter in 

public interface IDicomCStoreProvider
    {
        void OnCStoreRequestException(string **tempFileName**, Exception e);
    }

**Comment by SrividyaTR** [comment]
Any update on this issue? We are waiting for some clue to know why these temp files are getting created

**Comment by gofal** [comment]
Sorry, no concrete update.
So maybe some questions that could give some hints: are the temporary dicom files valid dicom files? I mean, if you start the DicomDump application and read such a file, do you there get parser errors or does it work?
If it works, then there seems to be some problem with the network kommunication and the OnCStoreRequestException is called where you get access to the file that caused the exception.
If it does not work with the DicomDump application, what exactly is the parser error? And does it work with version 4.0.0?

**Comment by mia-san** [comment]
@SrividyaTR is this still happens with 4.0.0?

**Comment by jaime-olivares** [comment]
This issue seems to be related to #557 

fo-dicom.Codecs use temp files for processing large buffers.

It is expected that a crash would leave temp files orphan. It suggested to clean them up during restart.

**Comment by gofal** [comment]
closing this issue due to inactivity. If there is still an issue, then please reopen it and provide some actual informations
