### ISSUE TITLE
DicomImage.RenderImage() broken

### ISSUE THREAD

**Issue by Telexy** [fo-dicom/fo-dicom#734]
### Expected behavior
I have a sample DICOM (attached) with (0028,1201) (0028,1202) and (0028,1203) Tags (Palette color lookup tables). DicomImage.RenderImage() used to work fine on it on versions 3.x. Now it is broken in version 4. 

### Actual behavior
Exception: "Unable to convert DICOM OW value to 'Byte[]'"

   at Dicom.DicomValueElement`1.Get[T](Int32 item) in C:\fo-dicom\DICOM\DicomElement.cs:line 411
   at Dicom.DicomDataset.GetValues[T](DicomTag tag) in C:\fo-dicom\DICOM\DicomDataset.cs:line 327
   at Dicom.Imaging.DicomPixelData.GetPaletteColorLUT() in C:\fo-dicom\DICOM\Imaging\DicomPixelData.cs:line 213
   at Dicom.Imaging.Render.PaletteColorPipeline..ctor(DicomPixelData pixelData) in C:\fo-dicom\DICOM\Imaging\Render\PaletteColorPipeline.cs:line 22
   at Dicom.Imaging.DicomImage.CreatePipelineData(DicomDataset dataset, DicomPixelData pixelData) in C:\fo-dicom\DICOM\Imaging\DicomImage.cs:line 446
   at Dicom.Imaging.DicomImage.EstablishPipeline() in C:\fo-dicom\DICOM\Imaging\DicomImage.cs:line 307
   at Dicom.Imaging.DicomImage.GetFrameIndex(Int32 frame) in C:\fo-dicom\DICOM\Imaging\DicomImage.cs:line 269
   at Dicom.Imaging.DicomImage.RenderImage(Int32 frame) in C:\fo-dicom\DICOM\Imaging\DicomImage.cs:line 223

### Steps to reproduce the behavior

try DicomImage.RenderImage(0) on the attached file.

### fo-dicom version and OS/platform
4.0.0, Windows
[10200904.zip](https://github.com/fo-dicom/fo-dicom/files/2499810/10200904.zip)

**Comment by gofal** [comment]
I cannot find any attached file

**Comment by Telexy** [comment]
Sorry, I missed that message about not supported file. Attached now as zip.
Thanks.

**Comment by Telexy** [comment]
So it looks like this problem is specific to PALETTE COLOR photometric interpretation. Is it a quick way around? Is it possible to convert it to something else (YBR_FULL for example) and then call that RenderImage?

P.S. I already attached that file twice.  And still don't see it. How that attachment works here?

Thanks.

**Comment by gofal** [comment]
strange. Today morging I did not see any attached file. But now suddenly your post from 2 days ago includes a link to a zip file. Some big latency in github...
I will check the file now.

**Comment by gofal** [comment]
when switching from the old DicomDataset.Get method to the new DicomDataset.GetValue or .GetValues I did not notice that in the old methods there was a special handling when getting byte[] or IByteBuffer. Added this special handling to the new methods.

Can you download the code from the branch and test your files? I will merge into the development-branch after you have verified.

**Comment by Telexy** [comment]
Tested. The fix worked. Thanks.
