### ISSUE TITLE
Wrong interpretation and application of LUT for PALETTE COLOR images

### ISSUE THREAD

**Issue by PalminX** [fo-dicom/fo-dicom#817]
For some images with Photometric Interpretation (0028,0004) == PALETTE COLOR, we get the following crash when rendering the image:

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=Dicom.Core
  StackTrace:
   at Dicom.Imaging.LUT.PaletteColorLUT.get_Item(Int32 value) in .\fo-dicom\fo-dicom\DICOM\Imaging\LUT\PaletteColorLUT.cs:line 79
   at Dicom.Imaging.Render.GrayscalePixelDataU8.<>c__DisplayClass17_0.<Render>b__1(Int32 y) in .\fo-dicom\fo-dicom\DICOM\Imaging\Render\PixelData.cs:line 345
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
```

The code tries to read the LUT value for [255+1] here, which fails because `_lut` has only 256 entries:
https://github.com/fo-dicom/fo-dicom/blob/9f7810d1e60c303c5d11c8e49dce788805fe598f/DICOM/Imaging/LUT/PaletteColorLUT.cs#L79

We have traced this to the initialization code of the PaletteColorPipeline:
https://github.com/fo-dicom/fo-dicom/blob/9f7810d1e60c303c5d11c8e49dce788805fe598f/DICOM/Imaging/Render/PaletteColorPipeline.cs#L22

This code tries to read the DICOM element as one with multiplicity 1, which fails because DicomTag.RedPaletteColorLookupTableDescriptor has a multiplicity of 3. Therefore, this always returns 1 instead of the value of the second element (which, in most cases, will be 0).

This issue will only become apparent for PALETTE COLOR images where the image contains the largest LUT index value (typically 255).

So actually, there are two separate code issues, which together result in this crash:
#### Wrong initialization of PaletteColorLUT._first because of wrong reading from DicomTag.RedPaletteColorLookupTableDescriptor 
This needs to be fixed by changing from `GetSingleValueOrDefault(DicomTag.RedPaletteColorLookupTableDescriptor, 1)` to `GetValue<int>(DicomTag.RedPaletteColorLookupTableDescriptor, 1)`

#### Wrong interpretation and usage of PaletteColorLUT._first during application of the LUT
The DICOM standard C.7.6.3.1.5 says:
>   The second Palette Color Lookup Table Descriptor value is the first input value mapped.This input value is mapped to the first entry in the Lookup Table Data. All input values less than the first value mapped are also mapped to the first entry in the Lookup Table Data if the Photometric Interpretation is PALETTE COLOR. 

Therefore, the existing code `return _lut[value + _first].Value;` does not do the right thing, it basically discards all LUT entries before _first. To be correct, it should look more like this: `return _lut[(value - _first)>0 ? (value - _first) : 0].Value;`

### Expected behavior
Palette color images shall be rendered correctly

### Actual behavior
Code crashes

### Steps to reproduce the behavior
Try to render any PALETTE COLOR image which uses pixel values (indexes) of 255 (I will provide samples)

### fo-dicom version and OS/platform
fo-dicom 4.0.1, .NET Core

**Comment by PalminX** [comment]
# Color Test Pattern DICOM images

This archive contains three DICOM SecondaryCaptureImageStorage color test pattern images, the original file is available at https://pixabay.com/vectors/test-pattern-tv-tv-test-pattern-152459/.

The test pattern has been converted to DICOM RGB using [MeVisLab](https://www.mevislab.de/).
Subsequently, the RGB image was converted to 8 bit and 16 bit PALETTE COLOR images using [dcmquant](https://support.dcmtk.org/docs/dcmquant.html).

| File                       | Photometric Interpretation (0028,0004) | RedPaletteColorLookupTableDescriptor (0028,1101) |
|----------------------------|----------------------------------------|--------------------------------------------------|
| TestPattern_RGB.dcm        | RGB                                    | N.A.                                             |
| TestPattern_Palette.dcm    | PALETTE COLOR                          | 256\0\8                                          |
| TestPattern_Palette_16.dcm | PALETTE COLOR                          | 256\0\16                                         |

These test patterns can be used under a [Creative Commons Attribution 3.0 Unported License.](https://creativecommons.org/licenses/by/3.0/)

Bernd Kuemmerlen (bkuemmer@gmx.net)

[TestPattern_Samples.zip](https://github.com/fo-dicom/fo-dicom/files/2992664/TestPattern_Samples.zip)
