### ISSUE TITLE
DicomDataSetDumper crashes on long private tags

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#846]
### Expected behavior
The option 'LogDimseDatasets' in DicomServiceOptions causes every DICOM request that is sent (in DicomService) to be serialized into a string and then passed onto the Logger. Even if the log level is not enabled to actually flush this content, the string itself is materialized and can cause problems.

The expected behavior is that this always works, regardless of which request and regardless of which dataset is contained in the request.

### Actual behavior
When trying to serialize long private tags, the process crashes because at some point, it tries to `val.Substring(0, <some negative value>)` which throws an exception.

> 2019-04-18 11:18:09.0543: thread:9 - Error Error during logging of DICOM message: System.ArgumentOutOfRangeException: Length cannot be less than zero.
> Parameter name: length
>    at Dicom.DicomDatasetWalker.DoWalk(IDicomDatasetWalker walker, Queue`1 items) in ...\FellowOakDicom\DICOM\DicomDatasetWalker.cs:line 343
>    at Dicom.Log.Extensions.WriteToString(IEnumerable`1 dataset) in ...\FellowOakDicom\DICOM\Log\Extensions.cs:line 29
>    at Dicom.Network.DicomMessage.ToString(Boolean printDatasets) in ...\FellowOakDicom\DICOM\Network\DicomMessage.cs:line 185
>    at Dicom.Network.DicomService.<DoSendMessageAsync>d__64.MoveNext() in ...\FellowOakDicom\DICOM\Network\DicomService.cs:line 1203

### Steps to reproduce the behavior

```csharp
        [Fact]
        public void DicomDatasetDumper_ShallNotThrow_OnLongPrivateTags()
        {
            var dataSet = new DicomDataset(new List<DicomItem>
            {
                new DicomUniqueIdentifier(
                    new DicomTag(0x0029, 0x1009, "A VERY LONG PRIVATE CREATOR THAT SHOULD WORK BUT IT DOESN'T"),
                    "123456789.123456789.123456789")
            });

            var stringBuilder = new StringBuilder();
            var dumper = new DicomDatasetDumper(stringBuilder, 128, 64);
            var walker = new DicomDatasetWalker(dataSet);

            walker.Walk(dumper);

            var output = stringBuilder.ToString();

            Assert.NotNull(output);
            Assert.NotEmpty(output);
        }
```

### fo-dicom version and OS/platform
Latest (4.0.1)
Windows 10

**Comment by amoerie** [comment]
By the way, this actually has pretty severe consequences: C-Store requests are logged right before they are flushed into the PDataTFStream in DicomService. If the attempt to log the request crashes, the following happens:

- The C-Store request is never actually sent, even though it is added to the _pending queue
- Because it is never sent, none of the timeout mechanisms work
- The _sending flag is never set to false, so every subsequent call to SendNextMessageAsync is in vain, effectively rendering the DicomClient in a useless, stuck state.

Ask me how we found this bug.. :-)

**Comment by amoerie** [comment]
Added unit test. I'll make a PR with the appropriate fix for this problem.
