### ISSUE TITLE
DicomValidation for VR UI on reading datasets

### ISSUE THREAD

**Issue by hkoestin** [fo-dicom/fo-dicom#859]
Hello all,

I am facing some problems with my proxy application, which shall only forward files from a PACS to another instance.

It cannot forward some files, as validation of the VR UI fails for them, because of leading zeros in the components.
According to Chapter 9 of part 5 (http://dicom.nema.org/medical/dicom/current/output/chtml/part05/chapter_9.html), UID encoding rules are quite clear. However, there is one note given.

> Registration authorities may distribute components with non-significant leading zeroes. The leading zeroes should be ignored when being encoded (i.e.,"00029" would be encoded "29").

So maybe, when reading existing datasets, this shall be ignored then?
Otherwise, you cannot process such a file. Or can the reading process ignore it and encode it correctly? This however would mean alteration of the original file content.

What about matching such UIDs?
Is 1.2.3.004 == 1.2.3.4 ???

### Expected behavior
To be discussed.

### Actual behavior
That is the line throwing afterwards:
https://github.com/fo-dicom/fo-dicom/blob/9fbf71d81a8e1a30e48c2551d283e7208ee775fc/DICOM/DicomValidation.cs#L448

### Steps to reproduce the behavior
Take any UID which has leading zeros in components.

### fo-dicom version and OS/platform
current **Development** **branch,** windows 10, 64bit

Kind regards,
Harald

**Comment by gofal** [comment]
The validation only happens, if you add Tags manually to a dataset, eg by calling `dataset.AddOrUpdate(...)`. When reading from a file or from a network stream, this validation is turned off by default. The rule was "be tollerant when consuming, but be scrict when creating".

You can explicitly turn off validation before calling `AddOrUpdate` if you set the property `dataset.AutoValidate` to false.

So how does your calling code look like when you get the exception?

**Comment by gofal** [comment]
compaing uids is currently implemented by string equality internally. It is up to you if you implement CFind or similiar, how you apply the search criterias and do the comparision of UIDs.

**Comment by hkoestin** [comment]
I thought so as well, that validation only happens for newly added tags.

What I do when I get the exception?

I have an incoming C-STORE request from a PACS and only want to forward its content to another destination.

So I have 

```c#
DicomCStoreRequest request; // this is the incoming request, not modified

// I do create a new request to point at the destination
var forwardRequest = new DicomCStoreRequest(request.File);
// and then I add it at the client
m_client.AddRequest(forwardRequest);
m_client.SendAsync( ... );
```` 

This piece of code throws already.

Whole stack-trace:

```
22816 18 - Error 2019-05-09 13:22:38.8005 [Dicom.Network] Exception processing P-Data-TF PDU: Dicom.DicomValidationException: Content "1.2.826.0.1.3680043.8.1055.1.20111102150934903.36998620.06036449" does not validate VR UI: components must not have leading zeros
   at Dicom.DicomValidation.ValidateUI(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomValidation.cs:line 450
   at Dicom.DicomVR.ValidateString(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomVR.cs:line 61
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dicom.DicomMultiStringElement.ValidateString() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 212
   at Dicom.DicomElement.Validate() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 43
   at Dicom.DicomDataset.DoAdd(IEnumerable`1 items, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1185
   at Dicom.IO.Reader.DicomDatasetReaderObserver.OnElement(IByteSource source, DicomTag tag, DicomVR vr, IByteBuffer data) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomDatasetReaderObserver.cs:line 151
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 649
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 223
   at Dicom.IO.Reader.DicomReader.Read(IByteSource source, IDicomReaderObserver observer, Func`2 stop) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 75
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 625 Dicom.DicomValidationException: Content "1.2.826.0.1.3680043.8.1055.1.20111102150934903.36998620.06036449" does not validate VR UI: components must not have leading zeros
   at Dicom.DicomValidation.ValidateUI(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomValidation.cs:line 450
   at Dicom.DicomVR.ValidateString(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomVR.cs:line 61
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dicom.DicomMultiStringElement.ValidateString() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 212
   at Dicom.DicomElement.Validate() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 43
   at Dicom.DicomDataset.DoAdd(IEnumerable`1 items, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1185
   at Dicom.IO.Reader.DicomDatasetReaderObserver.OnElement(IByteSource source, DicomTag tag, DicomVR vr, IByteBuffer data) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomDatasetReaderObserver.cs:line 151
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 649
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 223
   at Dicom.IO.Reader.DicomReader.Read(IByteSource source, IDicomReaderObserver observer, Func`2 stop) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 75
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 625
22816 18 - Error 2019-05-09 13:22:38.8005 [Dicom.Network] Exception processing PDU: Dicom.DicomValidationException: Content "1.2.826.0.1.3680043.8.1055.1.20111102150934903.36998620.06036449" does not validate VR UI: components must not have leading zeros
   at Dicom.DicomValidation.ValidateUI(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomValidation.cs:line 450
   at Dicom.DicomVR.ValidateString(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomVR.cs:line 61
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dicom.DicomMultiStringElement.ValidateString() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 212
   at Dicom.DicomElement.Validate() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 43
   at Dicom.DicomDataset.DoAdd(IEnumerable`1 items, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1185
   at Dicom.IO.Reader.DicomDatasetReaderObserver.OnElement(IByteSource source, DicomTag tag, DicomVR vr, IByteBuffer data) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomDatasetReaderObserver.cs:line 151
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 649
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 223
   at Dicom.IO.Reader.DicomReader.Read(IByteSource source, IDicomReaderObserver observer, Func`2 stop) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 75
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 777
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 781
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__58.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 500 Dicom.DicomValidationException: Content "1.2.826.0.1.3680043.8.1055.1.20111102150934903.36998620.06036449" does not validate VR UI: components must not have leading zeros
   at Dicom.DicomValidation.ValidateUI(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomValidation.cs:line 450
   at Dicom.DicomVR.ValidateString(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomVR.cs:line 61
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dicom.DicomMultiStringElement.ValidateString() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 212
   at Dicom.DicomElement.Validate() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 43
   at Dicom.DicomDataset.DoAdd(IEnumerable`1 items, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1185
   at Dicom.IO.Reader.DicomDatasetReaderObserver.OnElement(IByteSource source, DicomTag tag, DicomVR vr, IByteBuffer data) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomDatasetReaderObserver.cs:line 151
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 649
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 223
   at Dicom.IO.Reader.DicomReader.Read(IByteSource source, IDicomReaderObserver observer, Func`2 stop) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\IO\Reader\DicomReader.cs:line 75
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 777
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 781
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__58.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 500

```

**Comment by hkoestin** [comment]
BTW: also the DICOM Validator toolkit says, that the UID is illegal
https://www.dclunie.com/dicom3tools/dciodvfy.html

**Comment by gofal** [comment]
Hm, the stack trace looks as if the exception was already thrown when you receive the image and not when you want to forward it. Anyway: when disabling validation I missed this dataset.

**Comment by gofal** [comment]
I tried hard, but I did not manage to get a unit test to reproduce this exception. Creating some invalid dataset and sending it through my own store scp... 
Anyway: the stacktrace showed me a Command-DicomDataset that is filled in method ProcessPDataTFAsync when receiving data. So turning off validation there is good in any case, but I cannot check if that fixed your issue. I commited it directly into development branch. Would you mind to check out latest version and give it a try?

**Comment by hkoestin** [comment]
Will forward merge the dev branch into my local repo and give it a try.

For my local builds, I just disabled these lines of validation so far in the DicomValidation class itself. ValdiateUI, last IF statement with the regex.

**Comment by hkoestin** [comment]
@gofal I did give the new validation a try, but it is still failing with the same errors. As far as I see, it is quite the same stack trace.

I will try to get a unit-test for the framework, which reproduces that error state.

```c#
19940 8 - Error 2019-05-13 09:45:46.7789 [Dicom.Network] Exception processing P-Data-TF PDU: Dicom.DicomValidationException: Content "1.2.826.0.1.3680043.8.1055.1.20111103111149651.05453119.38197201" does not validate VR UI: components must not have leading zeros
   at Dicom.DicomValidation.ValidateUI(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomValidation.cs:line 450
   at Dicom.DicomVR.ValidateString(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomVR.cs:line 61
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dicom.DicomMultiStringElement.ValidateString() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 212
   at Dicom.DicomElement.Validate() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 43
   at Dicom.DicomDataset.DoAdd(DicomItem item, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1224
   at Dicom.DicomDataset.DoAdd[T](DicomVR vr, DicomTag tag, Encoding encoding, IList`1 values, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1502
   at Dicom.DicomDataset.DoAdd[T](DicomTag tag, Encoding encoding, IList`1 values, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1259
   at Dicom.DicomFileMetaInformation.set_MediaStorageSOPInstanceUID(DicomUID value) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomFileMetaInformation.cs:line 118
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 603 Dicom.DicomValidationException: Content "1.2.826.0.1.3680043.8.1055.1.20111103111149651.05453119.38197201" does not validate VR UI: components must not have leading zeros
   at Dicom.DicomValidation.ValidateUI(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomValidation.cs:line 450
   at Dicom.DicomVR.ValidateString(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomVR.cs:line 61
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dicom.DicomMultiStringElement.ValidateString() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 212
   at Dicom.DicomElement.Validate() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 43
   at Dicom.DicomDataset.DoAdd(DicomItem item, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1224
   at Dicom.DicomDataset.DoAdd[T](DicomVR vr, DicomTag tag, Encoding encoding, IList`1 values, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1502
   at Dicom.DicomDataset.DoAdd[T](DicomTag tag, Encoding encoding, IList`1 values, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1259
   at Dicom.DicomFileMetaInformation.set_MediaStorageSOPInstanceUID(DicomUID value) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomFileMetaInformation.cs:line 118
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 603
19940 8 - Error 2019-05-13 09:45:46.7789 [Dicom.Network] Exception processing PDU: Dicom.DicomValidationException: Content "1.2.826.0.1.3680043.8.1055.1.20111103111149651.05453119.38197201" does not validate VR UI: components must not have leading zeros
   at Dicom.DicomValidation.ValidateUI(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomValidation.cs:line 450
   at Dicom.DicomVR.ValidateString(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomVR.cs:line 61
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dicom.DicomMultiStringElement.ValidateString() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 212
   at Dicom.DicomElement.Validate() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 43
   at Dicom.DicomDataset.DoAdd(DicomItem item, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1224
   at Dicom.DicomDataset.DoAdd[T](DicomVR vr, DicomTag tag, Encoding encoding, IList`1 values, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1502
   at Dicom.DicomDataset.DoAdd[T](DicomTag tag, Encoding encoding, IList`1 values, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1259
   at Dicom.DicomFileMetaInformation.set_MediaStorageSOPInstanceUID(DicomUID value) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomFileMetaInformation.cs:line 118
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 785
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 789
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__58.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 504 Dicom.DicomValidationException: Content "1.2.826.0.1.3680043.8.1055.1.20111103111149651.05453119.38197201" does not validate VR UI: components must not have leading zeros
   at Dicom.DicomValidation.ValidateUI(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomValidation.cs:line 450
   at Dicom.DicomVR.ValidateString(String content) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomVR.cs:line 61
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Dicom.DicomMultiStringElement.ValidateString() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 212
   at Dicom.DicomElement.Validate() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomElement.cs:line 43
   at Dicom.DicomDataset.DoAdd(DicomItem item, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1224
   at Dicom.DicomDataset.DoAdd[T](DicomVR vr, DicomTag tag, Encoding encoding, IList`1 values, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1502
   at Dicom.DicomDataset.DoAdd[T](DicomTag tag, Encoding encoding, IList`1 values, Boolean allowUpdate) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomDataset.cs:line 1259
   at Dicom.DicomFileMetaInformation.set_MediaStorageSOPInstanceUID(DicomUID value) in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\DicomFileMetaInformation.cs:line 118
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 785
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__59.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 789
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dicom.Network.DicomService.<ListenAndProcessPDUAsync>d__58.MoveNext() in C:\Projects\Samples\DICOM\fo-dicom (hkoestin fork)\DICOM\Network\DicomService.cs:line 504
19940 8 - Debug 2019-05-13 09:45:46.7889 [Dicom.Network] Connection closed: Content "1.2.826.0.1.3680043.8.1055.1.20111103111149651.05453119.38197201" does not validate VR UI: components must not have leading zeros 
19940 8 - Debug 2019-05-13 09:45:46.7889 [Dicom.Network] Connection closed 

```

**Comment by hkoestin** [comment]
I could add several tests now, reproducing that issue. 
The issue is actually related to the FileMetaInfo object, which itself is a DicomDataset.

The DicomService does read the stream and create a DicomFile for the incoming data. And there, the setting of the MediaStorage parts fail, as the UIDs are not valid.

https://github.com/fo-dicom/fo-dicom/blob/a87f5105c48c26f303b54aad0d97a801cdc33e21/DICOM/Network/DicomService.cs#L595-L601

I am not sure now, if the correct fix would involve just a local fix in the DicomService to disable validation for that file-meta-info object first, or if in general all file meta info objects shall be not validated.

When looking at the code, I very much dislike, that there is no explicit way of creating not-validated objects when reading from streams. You always have to manually do set the validation to false, which is error prone, as it could be forgotten.

Suggestion from my side:
* Constructed with default Ctor, validation is disabled, as this is the most common way of creation for reading files, streams, etc.
* Constructed via dataset: use the dataset.AutoValidated flag
* Constructed via copy-ctor: set same value again.

**Comment by hkoestin** [comment]
I created a small fix here: https://github.com/hkoestin/fo-dicom/pull/4.

However, this topic of validation is spanning across the whole project now:
* At reading elements from messages, validation must be turned off. Otherwise, incorrect data may not be accepted.
* At creation of a new dataset, file or the like, validation shall happen, to avoid invalid data. Agreed. But this is hard to control, as there are so many places in code now, where this happens.
* Elements, such as DicomFile, fail now when saving invalid data. E.g. through a C-Store request received data contains a File. When you try to save that, it will simply fail. Thus, DicomFile.Save overloads should disable that as well, right?

**Comment by hkoestin** [comment]
Branch https://github.com/hkoestin/fo-dicom/tree/GH859 now has also the fix for the C-STORE request.

**Comment by gofal** [comment]
Yes, this validation thing is not that easy. It took me quite some time to implement it and I have done several approaches. This solution finally worked best. 
The DicomDataset has to be validated by default, so that every Dataset, that a user creates is validated. I may not rely on that the user turns on validation himself by default. This means I have to turn off validation explicitly in many places - i know. but this I think is only a single time work now to find all this places, because the number of such places is quite stable, there have not been too much changes the last years.

Agree, that DicomFile.Save overloads should disable validation, because validation should already happen when the DicomDataset is built. So once the dataset is in memory (manually created and therefore validated, or received somehow and unvalidated) it should be able to be further processed.

**Comment by gofal** [comment]
already fixed this. If the problem is still happening with latest version, please reopen this issue.
