### ISSUE TITLE
Dicom.Network.DicomAssociationRejectedException PRINT SCU

### ISSUE THREAD

**Issue by yadavvirus** [fo-dicom/fo-dicom#892]
Message=Association rejected [result: Permanent; source: ServiceProviderPresentation; reason: 8]

[log.txt](https://github.com/fo-dicom/fo-dicom/files/3482527/log.txt)

**Comment by yadavvirus** [comment]
Dicom.Network.DicomAssociationRejectedException was unhandled
  HResult=-2146233088
  Message=Association rejected [result: Permanent; source: ServiceProviderPresentation; reason: 8]
  Source=Dicom
  StackTrace:
       at Dicom.Network.DicomClient.EndSend(IAsyncResult result) in D:\AllInONE\PrintDICOM\dicom-master\DICOM\Network\DicomClient.cs:line 195
       at Dicom.Network.DicomClient.Send(String host, Int32 port, Boolean useTls, String callingAe, String calledAe) in D:\AllInONE\PrintDICOM\dicom-master\DICOM\Network\DicomClient.cs:line 98
       at Dicom_Print_SCU.PrintClient.Print() in D:\AllInONE\PrintDICOM\dicom-master\Examples\Dicom Print SCU\PrintClient.cs:line 713
       at Dicom_Print_SCU.MainWindow.DicomPrint(List`1 filelist) in D:\AllInONE\PrintDICOM\dicom-master\Examples\Dicom Print SCU\MainWindow.xaml.cs:line 427
       at Dicom_Print_SCU.MainWindow.PrintButtonClick(Object sender, RoutedEventArgs e) in D:\AllInONE\PrintDICOM\dicom-master\Examples\Dicom Print SCU\MainWindow.xaml.cs:line 307
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.Controls.Primitives.ButtonBase.OnClick()
       at System.Windows.Controls.Button.OnClick()
       at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
       at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
       at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
       at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
       at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
       at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
       at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
       at System.Windows.Input.InputManager.ProcessStagingArea()
       at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
       at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
       at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
       at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at Dicom_Print_SCU.App.Main()
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by gofal** [comment]
I assume this might me similar to #667. There is a known bug with Abstract Syntax UID on association request. But to make it sure: which Print Server are you using? The server only returned "reason 8". I would like to take a look into the DICOM Conformance Statement of the print server to see if this is something like "no supported presentation context agreed" or so.

**Comment by yadavvirus** [comment]
Sir I was trying to print DICOM over Fujifilm DRYPIX PRIMA DICOM Printer.
Plz Help me to fix this issue.
Thank you Sir.
Regards

**Comment by yadavvirus** [comment]
Sir I am waiting for your responce. Please reply

**Comment by yadavvirus** [comment]
@gofal sir reply plz.

**Comment by yadavvirus** [comment]
@gofal sir plz can you send me 4.0.2 fo-dicom source at yadavvirus@yahoo.com
Thank you sir.

**Comment by gofal** [comment]
Of course I will help you and try to fix this issue. I already started with some code changes in a branch.

**Comment by gofal** [comment]
@yadavvirus You can get the code of fo-dicom 4.0.2 here on github. its the branch "4.0"

**Comment by yadavvirus** [comment]
@gofal  Thank you sir for reply. Sir please fix this so i can proceed further. Very Nice of you sir, Thank you.

**Comment by yadavvirus** [comment]
@gofal sir I have tried on another printer and also giving error log below plz help me understand this problem too.

DS5302 -> Association request:
Calling AE Title:       SCANRAD
Called AE Title:        DS5302
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 1.1.4
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  3
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Basic Film Session SOP Class
       Transfer Syntax:  Explicit VR Little Endian
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Basic Film Box SOP Class
       Transfer Syntax:  Explicit VR Little Endian
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Basic Grayscale Image Box SOP Class
       Transfer Syntax:  Explicit VR Little Endian
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
DS5302 <- Association accept:
Calling AE Title:       SCANRAD
Called AE Title:        DS5302
Implementation Class:   Unknown [1.3.51.0.1.3]
Implementation Version: AGFA DTF1.0.90
Maximum PDU Length:     65542
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  3
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Basic Film Session SOP Class
       Transfer Syntax:  Explicit VR Little Endian
  Presentation Context:  3 [Accept]
       Abstract Syntax:  Basic Film Box SOP Class
       Transfer Syntax:  Explicit VR Little Endian
  Presentation Context:  5 [Accept]
       Abstract Syntax:  Basic Grayscale Image Box SOP Class
       Transfer Syntax:  Explicit VR Little Endian
DS5302 -> N-Create request [1]
DS5302 <- N-Create response [1]: Success
DS5302 -> N-Create request [2]
DS5302 <- N-Create response [2]: Processing failure
DS5302 -> N-Set request [3]
DS5302 <- N-Set response [3]: Missing attribute
DS5302 -> N-Action request [4]
		Action Type:	0001
DS5302 <- N-Action response [4]: Film session SOP instance hierarchy does not contain image box SOP instances (empty page)
		Action Type:	0000
DS5302 -> Association release request
DS5302 <- Association release response
Connection closed

**Comment by gofal** [comment]
I created a pull request #907 from branch GH-667. Please give this code a try.

**Comment by yadavvirus** [comment]
@gofal  Hello Sir Actually I am trying to use this new Code. After building i have added in 
DICOM Print SCU earlier example. Sir I got Error as DIcom.Core.dll has changed 
as In 
1. ImageHelper--GenerateBitmap having problem of conversion if IImage type to System.drawing.Image.
2. ImageHelper--AnnotationVerticalAlignment-Having Problem with AnnotationItem could not be found and AnnotationItem .
Please sir help me to fix this issue.
Thank You

**Comment by yadavvirus** [comment]
@gofal Sir I am waiting for your reply plz help me.
Thank you

**Comment by gofal** [comment]
I do not understand your issues. The fix already has been released in version 4.0.3. Please try to update the fo-dicom via nuget and rebuild your solution.
If it happens that your dependencies do not work because of the update, clear the `bin` and `obj` folders within your project directories and do a complete new build of the projects.

**Comment by yadavvirus** [comment]
@gofal  Thank you sir for reply SIr I did so, Sir plz Check attached image sir, may be new dll iz missing these properties sir Do you have any other DICOM Print Demo Project which will work in new Library 4.0.3. Plz Sir.
![annotationText](https://user-images.githubusercontent.com/7027914/65858304-3ae7c700-e383-11e9-895d-34b1e5dec61a.jpg)
![image](https://user-images.githubusercontent.com/7027914/65858322-42a76b80-e383-11e9-85ed-c0300998c196.jpg)

**Comment by yadavvirus** [comment]
Both the error I am getting in ImageHelper.cs Class file.

**Comment by yadavvirus** [comment]
@gofal sir Please If possible then help me in DICOM Print. If you have any example of demo project. I am still locked in same proble. New version of dll is not working with earlier example. I have attached above error occuring. Plz give me any another demo or example project of DICOM Print If possible.
Thank You sir.

**Comment by yadavvirus** [comment]
@gofal Hello Sir,
Sir please help me in above please.
