### ISSUE TITLE
DicomFile.Open with SkipLargeTags throws "NullReferenceException", default mode works

### ISSUE THREAD

**Issue by jussimattila** [fo-dicom/fo-dicom#905]
### Expected behavior
`DicomFile.Open(fileName, FileReadOption.SkipLargeTags)` should return a dataset.

### Actual behavior
NullReferenceException is thrown here:
```
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source)
   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source)
   at Dicom.IO.Reader.DicomReader.Read(IByteSource source, IDicomReaderObserver observer, Func`2 stop)
   at Dicom.IO.Reader.DicomFileReader.DoParse(IByteSource source, IDicomReaderObserver fileMetasetInfoObserver, IDicomReaderObserver datasetObserver, Func`2 stop, DicomTransferSyntax& syntax, DicomFileFormat& fileFormat)
   at Dicom.IO.Reader.DicomFileReader.Parse(IByteSource source, IDicomReaderObserver fileMetasetInfoObserver, IDicomReaderObserver datasetObserver, Func`2 stop)
   at Dicom.IO.Reader.DicomFileReader.Read(IByteSource source, IDicomReaderObserver fileMetaInfo, IDicomReaderObserver dataset, Func`2 stop)
   at Dicom.DicomFile.Open(String fileName, Encoding fallbackEncoding, Func`2 stop, FileReadOption readOption)
   at Dicom.DicomFile.Open(String fileName, Encoding fallbackEncoding, Func`2 stop, FileReadOption readOption)
   at cNeuro.Dicom.DicomInfo.<Enumerate>d__18.MoveNext() in C:\Users\Jussi\Documents\GitHub\cNeuro\src\cNeuro.Dicom\DicomInfo.cs:line 65
```
### Steps to reproduce the behavior
Open file "NullPointerException.dcm" using `FileReadOptions.SkipLargeTags`. For comparison, the zip contains another file from the same series that loads correctly using `FileReadOptions.SkipLargeTags`.

[fo-dicom-SkipLargeTags.zip](https://github.com/fo-dicom/fo-dicom/files/3519095/fo-dicom-SkipLargeTags.zip)

The file in question has been used as a test file for a long time in many scenarios. I haven't had problems loading it before this so I don't think there should be anything seriously wrong with the file itself. This is the first time I'm making use of `FileReadOption.SkipLargeTags`, so it is definitely related to that.

### fo-dicom version and OS/platform
fo-dicom 4.0.2, .NET Standard 2.0, Windows 10

**Comment by gofal** [comment]
Maybe it is the same as #893 ? Can you give the latest development code a try?

**Comment by gofal** [comment]
I can reproduce the null point exception with code from some older branch, but with the code from the current development branch the files opens without problems. So I am pretty much sure that this issue has the same reason as the already fixed issue 893. 

Please verify.

**Comment by jussimattila** [comment]
Sorry, I haven't verified yet! I'll try to get around to doing that ASAP.

**Comment by gofal** [comment]
Have you managed to verify meanwhile?

**Comment by gofal** [comment]
its now released. Will close this issue. Feel free to reopen this issue if it still happens with version 4.0.3

**Comment by jussimattila** [comment]
I'm really sorry for not verifying the fix in time for the release! 😞 But, I tested it now with the latest binaries and the bug is indeed fixed. Happy to keep the PR closed! 😃
