### ISSUE TITLE
Can't render a Jpeg image

### ISSUE THREAD

**Issue by Evegeny** [fo-dicom/fo-dicom#911]
### Expected behavior
I'm trying to render the attached image. With `DicomImage.RenderImage()`.

### Actual behavior
Getting `MissingMethodException` - Method not found: 'Void Dicom.Imaging.DicomPixelData.set_BitsAllocated(UInt16)'.
`   at Dicom.Imaging.Codec.DicomJpegNativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   at Dicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters) in C:\Users\admin\source\repos\fo-dicom\DICOM\Imaging\Codec\DicomTranscoder.cs:line 233
   at Dicom.Imaging.Codec.DicomTranscoder.DecodeFrame(DicomDataset dataset, Int32 frame) in C:\Users\admin\source\repos\fo-dicom\DICOM\Imaging\Codec\DicomTranscoder.cs:line 175
   at Dicom.Imaging.DicomImage.GetFrameIndex(Int32 frame) in C:\Users\admin\source\repos\fo-dicom\DICOM\Imaging\DicomImage.cs:line 280
   at Dicom.Imaging.DicomImage.RenderImage(Int32 frame) in C:\Users\admin\source\repos\fo-dicom\DICOM\Imaging\DicomImage.cs:line 223

### Steps to reproduce the behavior
Try to render the attached image

### fo-dicom version and OS/platform
fo-dicom 4.0.1 on Windows 10 x64

[Spine-LAT_1861.zip](https://github.com/fo-dicom/fo-dicom/files/3556500/Spine-LAT_1861.zip)

**Comment by Evegeny** [comment]
@Isaac44 Indeed switching to x64 fixed the issue! Thank you!

@amoerie Agree.
