### ISSUE TITLE
If the new DicomClient cannot open a connection, it keeps infinitely trying

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#933]
### Expected behavior
Not sure yet. Perhaps we should give up after x attempts, where x is a configurable DicomServiceOption. The DicomClient supports cancellation through its cancellation token, so there is a workaround for existing consumers to prevent this behavior. But we can do better from the inside.

### Actual behavior
The new DicomClient goes from idle -> connecting -> requesting association -> completed with error -> idle -> connecting -> etc.

### Steps to reproduce the behavior
Try to send requests to an unknown server.

### fo-dicom version and OS/platform
4.0.3
Latest Windows 10

**Comment by amoerie** [comment]
Some more notes:

The IDLE state, which is what the DicomClient goes back to after completing its work, will automatically check if there are more requests to send. This is necessary in various scenarios, for example when an error for a single request occurred, or when the maximum number of requests per association has been reached. So we should not modify this behavior.

The best solution, it seems, would be to keep track of *subsequent* connection errors and give up after a preset number of times.

This would entail a new DicomServiceOption, e.g. MaxNumberOfSubsequentConnectAttempts.

Suggestions welcome!

**Comment by gofal** [comment]
The option MaxNumberOfSubsequentConnectAttempts sounds a good idea.

Does this issue happen if the dicomclient never establishes a connection? or does it also happen if the connection breaks while sending a request?

**Comment by amoerie** [comment]
Yes it happens in both scenarios. But now that I think about it, this might just be a bug in the flow. According to the documentation of https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/Client/States/DicomClientCompletedState.cs, the DicomClient should remain in the completed state if an exception occurred along the way. 

I will investigate further how this issue occurs.

**Comment by amoerie** [comment]
This is a false alarm. The test in which we detected this issue was wrongly configured. If anyone else encounters this, we can investigate the circumstances, but I cannot manage to replay this issue today.

**Comment by gofal** [comment]
Not sure if this is the same root cause, but @potatof opened an issue on the fo-dicom-samples repository (https://github.com/fo-dicom/fo-dicom-samples/issues/47):

In test project DICOM.Desktop  - DICOM.Tests.Desktop :

Dicom.Network.AsyncDicomCEchoProviderTests.OnCEchoRequestAsync_ShouldRespond
\AsyncDicomCEchoProviderTests.cs 

I've just change line 30
var client = new Network.Client.DicomClient("127.0.0.1", port, false, "SCU", "ANY-SCP")
by
var client = new Network.Client.DicomClient("www.google.com", 80, false, "SCU", "ANY-SCP")

Debug the test, and... loop indefinitely

How to manage Association Request retries ?

**Comment by amoerie** [comment]
I've tried doing this, but to me the behavior seems to be correct.
This is the test output:

```
System.Net.Sockets.SocketException
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 216.58.211.100:11112
   at Dicom.Network.Client.States.DicomClientCompletedState.<GetNextStateAsync>d__8.MoveNext() in D:\git\fo-dicom\DICOM\Network\Client\States\DicomClientCompletedState.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.Client.DicomClient.<Transition>d__94.MoveNext() in D:\git\fo-dicom\DICOM\Network\Client\DicomClient.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.Client.States.DicomClientConnectState.<GetNextStateAsync>d__5.MoveNext() in D:\git\fo-dicom\DICOM\Network\Client\States\DicomClientConnectState.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.Client.DicomClient.<Transition>d__94.MoveNext() in D:\git\fo-dicom\DICOM\Network\Client\DicomClient.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.Client.States.DicomClientIdleState.<SendAsync>d__5.MoveNext() in D:\git\fo-dicom\DICOM\Network\Client\States\DicomClientIdleState.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.Client.DicomClient.<SendAsync>d__112.MoveNext() in D:\git\fo-dicom\DICOM\Network\Client\DicomClient.cs:line 319
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Dicom.Network.AsyncDicomCEchoProviderTests.<OnCEchoRequestAsync_ShouldRespond>d__2.MoveNext() in D:\git\fo-dicom\Tests\Desktop\Network\AsyncDicomCEchoProviderTests.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 260
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext() in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90



    XUnitDicomLogger   DEBUG  12:47:36.521 # 16               DicomClient : [IDLE] --> [CONNECTING]
    XUnitDicomLogger   DEBUG  12:47:57.572 #  8               DicomClient : [CONNECTING] --> [COMPLETED]
    XUnitDicomLogger   DEBUG  12:47:57.575 #  8               DicomClient : [COMPLETED] DICOM client completed with an error
    XUnitDicomLogger WARNING  12:47:57.575 #  8               DicomClient : [COMPLETED] An error occurred and no active connection was detected, so no cleanup will happen!

```

**Comment by Potatof** [comment]
@amoerie 
Hi,
I will try to provide the logs and test environment, I hope to have time before Christmas ...

**Comment by amoerie** [comment]
There is now a  test in the development branch that also verifies  this behavior: 

https://github.com/fo-dicom/fo-dicom/blob/development/Tests/Desktop/Network/Client/DicomClientTest.cs#L1345

**Comment by ge-bus** [comment]
I was able to reproduce the issue. In case there no TCP handshake due to closed port or other issue indeed an error will be thrown:

- DicomClient state: CONNECTING
- DicomClient state: COMPLETED
- System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

In case the handshake succeeds, an A-ASSOCIATE request will be issued. If the the SCP doesn't respond to this request, fo-dicom will try to close the TCP connection after 60 seconds [FIN, ACK] (A hard reset of the TCP connection is forced another two minutes later [RST, ACK].).
Directly after the [FIN, ACK], a new socket connection is opened, repeating the cycle.
So in the case a socket connection can be established, but the SCP doesn't respond to the request, the SCU seems to keep trying.

**Comment by amoerie** [comment]
Hi @ge-bus 

Thanks for digging deeper on this issue!

We're currently busy with a considerable rework of fo-dicom to move it to .NET Standard (see https://github.com/fo-dicom/fo-dicom/pull/977 ) so any non-critical issues will probably have to wait until this is done.

I will take a look at this problem after the rework, but if this issue is very important to you, then you are of course welcome to open a PR.

**Comment by ge-bus** [comment]
Hi @amoerie, understand the priorities, just confirming the behavior you've initially seen.

**Comment by gofal** [comment]
I guess there will be 4.0.x releases for bug fixes. And if someone needs enhancements and does not want to switch to 5.0 and creates a pull request for version 4, then I will not reject this PR. But I will focus my work on 5.0.
5.0 introduces quite some breaking changes, so i assume some projects out there will stay on 4.0 for some time.

**Comment by amoerie** [comment]
@ge-bus When you have the time, could you try to repeat this issue with the latest 4.0.6 release? Some improvements have been made that might fix this issue.

**Comment by amoerie** [comment]
This issue should be fixed with the new behavior that detects a failed association request n consecutive times. See #1285.
Please reopen if this issue is still reproducible with the latest 5.x release.

**Comment by nagulandev** [comment]
{"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.32.45.67:104"}

this is just random IP and it takes 30 secs to return this exception. Help here to fix the issue.

https://github.com/fo-dicom/fo-dicom/issues/1875
